addSbtPlugin("org.scala-js"  % "sbt-scalajs"  % "1.17.0")
addSbtPlugin("org.typelevel" % "sbt-tpolecat" % "0.5.2")
addSbtPlugin("io.spray"      % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.eed3si9n"  % "sbt-assembly" % "0.14.10")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.12.1")
