addSbtPlugin("org.scala-js"              % "sbt-scalajs"         % "1.13.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.2")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"        % "0.14.10")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.4")
