import sbt.*
import scala.sys.process.*

object HtmlEntityGen {

  def template(moduleName: String, fullyQualifiedPath: String, contents: String): String =
    s"""package $fullyQualifiedPath
    |
    |// GENERATED by HtmlEntityGen.scala - DO NOT EDIT
    |trait $moduleName {
    |$contents
    |}
    """.stripMargin

  def gen(fullyQualifiedPath: String, sourceManagedDir: File): Seq[File] = {

    val name = "HtmlEntities"

    val file: File =
      sourceManagedDir / s"$name.scala"

    if (!file.exists()) {
      println("Generating Html Entities")

      val contents: String = {
        val all =
          CompleteHtmlEntityLists.all.map { case (safeName, entityValue) =>
            s"""  val _${safeName}_ = HtmlEntity("$entityValue")"""
          }

        s"""
        |${all.mkString("\n")}
        |""".stripMargin
      }

      val newContents: String =
        template(name, fullyQualifiedPath, contents)

      IO.write(file, newContents)

      println("Written: " + file.getCanonicalPath)
    }

    Seq(file)
  }

}
