addSbtPlugin("ch.epfl.scala"             % "sbt-scalajs-bundler" % "0.20.0")
addSbtPlugin("org.xerial.sbt"           %% "sbt-sonatype"        % "3.9.7")
addSbtPlugin("com.jsuereth"             %% "sbt-pgp"             % "2.0.1")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"          % "4.1.1")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"         % "1.5.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.17")
