let mdoc_js_run2,mdoc_js_run4,mdoc_js_run8,mdoc_js_run6,mdoc_js_run3,mdoc_js_run1,mdoc_js_run5,mdoc_js_run7;
(function(){
'use strict';var d,aa=Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.10.0",fileLevelThis:this}),ba;function ca(a){for(var b in a)return b}function da(a){this.gc=a}da.prototype.toString=function(){return String.fromCharCode(this.gc)};var fa=function ea(a,b,c){var g=new a.m(b[c]);if(c<b.length-1){a=a.cb;c+=1;for(var f=g.a,h=0;h<f.length;h++)f[h]=ea(a,b,c)}return g};
function ha(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"number"!==typeof a||a===a&&Math.fround(a)!==a?"java.lang.Double":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.Ff():a instanceof k?"java.lang.Long":a instanceof da?"java.lang.Character":a&&a.$classData?a.$classData.name:
null.rb.name}}function ia(a,b){switch(typeof a){case "string":return a===b;case "number":return Object.is(a,b);case "boolean":return a===b;case "undefined":return a===b;default:return a&&a.$classData||null===a?b=a.k(b):a instanceof k?b instanceof k?(a=ja(a),b=ja(b),b=a.u===b.u&&a.t===b.t):b=!1:b=a instanceof da?b instanceof da?ka(a)===ka(b):!1:m.prototype.k.call(a,b),b}}
function la(a){switch(typeof a){case "string":return ma(a);case "number":return na(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a=a.p():a instanceof k?(a=ja(a),a=a.u^a.t):a=a instanceof da?ka(a):m.prototype.p.call(a),a}}function oa(a){return void 0===a?"undefined":a.toString()}var pa=0,ra=new WeakMap;
function sa(a){switch(typeof a){case "string":return ma(a);case "number":return na(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:ma(a);default:if(null===a)return 0;b=ra.get(a);void 0===b&&(pa=b=pa+1|0,ra.set(a,b));return b}}function n(a){return new da(a)}function ka(a){return null===a?0:a.gc}
function ja(a){return null===a?ba:a}function m(){}m.prototype.constructor=m;function p(){}p.prototype=m.prototype;m.prototype.p=function(){return sa(this)};m.prototype.k=function(a){return this===a};m.prototype.l=function(){var a=this.p();return ha(this)+"@"+(+(a>>>0)).toString(16)};m.prototype.toString=function(){return this.l()};function q(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}q.prototype=new p;q.prototype.constructor=q;function ta(){}
ta.prototype=q.prototype;function ua(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}ua.prototype=new p;ua.prototype.constructor=ua;function va(a){this.a="number"===typeof a?new Uint16Array(a):a}va.prototype=new p;va.prototype.constructor=va;function wa(a){this.a="number"===typeof a?new Int8Array(a):a}wa.prototype=new p;wa.prototype.constructor=wa;function xa(a){this.a="number"===typeof a?new Int16Array(a):a}xa.prototype=new p;xa.prototype.constructor=xa;
function ya(a){this.a="number"===typeof a?new Int32Array(a):a}ya.prototype=new p;ya.prototype.constructor=ya;function za(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=ba}else this.a=a}za.prototype=new p;za.prototype.constructor=za;function Aa(a){this.a="number"===typeof a?new Float32Array(a):a}Aa.prototype=new p;Aa.prototype.constructor=Aa;function Ba(a){this.a="number"===typeof a?new Float64Array(a):a}Ba.prototype=new p;Ba.prototype.constructor=Ba;
function r(){this.m=void 0;this.Pa=this.cb=this.N=null;this.Qa=0;this.Ic=null;this.va="";this.xa=this.ab=this.Mb=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function Ca(a,b,c,e){var g=new r;g.N={};g.Ic=a;g.va=b;g.xa=f=>f===g;g.name=c;g.isPrimitive=!0;g.isInstance=()=>!1;void 0!==e&&(g.ab=Da(g,e));return g}
function t(a,b,c,e){var g=new r,f=ca(a);g.N=e;g.va="L"+c+";";g.xa=h=>!!h.N[f];g.name=c;g.isInterface=b;g.isInstance=h=>!!(h&&h.$classData&&h.$classData.N[f]);return g}function Da(a,b,c){var e=new r;b.prototype.$classData=e;var g="["+a.va;e.m=b;e.N={b:1,sb:1,c:1};e.cb=a;e.Pa=a;e.Qa=1;e.va=g;e.name=g;e.isArrayClass=!0;e.xa=c||(f=>e===f);e.isInstance=f=>f instanceof b;return e}
function Ea(a){function b(l){if("number"===typeof l){this.a=Array(l);for(var v=0;v<l;v++)this.a[v]=null}else this.a=l}var c=new r;b.prototype=new ta;b.prototype.constructor=b;var e=a.Pa||a,g=a.Qa+1;b.prototype.$classData=c;var f="["+a.va;c.m=b;c.N={b:1,sb:1,c:1};c.cb=a;c.Pa=e;c.Qa=g;c.va=f;c.name=f;c.isArrayClass=!0;var h=l=>{var v=l.Qa;return v===g?e.xa(l.Pa):v>g&&e===u};c.xa=h;c.isInstance=l=>{l=l&&l.$classData;return!!l&&(l===c||h(l))};return c}function w(a){a.ab||(a.ab=Ea(a));return a.ab}
function Fa(a){a.Mb||(a.Mb=new Ga(a));return a.Mb}r.prototype.isAssignableFrom=function(a){return this===a||this.xa(a)};r.prototype.checkCast=function(){};r.prototype.getSuperclass=function(){return this.yd?Fa(this.yd):null};r.prototype.getComponentType=function(){return this.cb?Fa(this.cb):null};r.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=w(b);return fa(b,a,0)};var u=new r;u.N={b:1};u.va="Ljava.lang.Object;";u.xa=a=>!a.isPrimitive;u.name="java.lang.Object";
u.isInstance=a=>null!==a;u.ab=Da(u,q,a=>{var b=a.Qa;return 1===b?!a.Pa.isPrimitive:1<b});m.prototype.$classData=u;Ca(void 0,"V","void",void 0);Ca(!1,"Z","boolean",ua);Ca(0,"C","char",va);Ca(0,"B","byte",wa);Ca(0,"S","short",xa);Ca(0,"I","int",ya);var Ha=Ca(null,"J","long",za);Ca(0,"F","float",Aa);Ca(0,"D","double",Ba);function Ga(a){this.rb=a}Ga.prototype=new p;Ga.prototype.constructor=Ga;Ga.prototype.l=function(){return(this.rb.isInterface?"interface ":this.rb.isPrimitive?"":"class ")+this.rb.name};
Ga.prototype.$classData=t({gd:0},!1,"java.lang.Class",{gd:1,b:1});function Ia(){this.kc=this.tb=this.eb=null;Ja=this;this.eb=new ArrayBuffer(8);this.tb=new Int32Array(this.eb,0,2);new Float32Array(this.eb,0,2);this.kc=new Float64Array(this.eb,0,1);this.tb[0]=16909060;new Int8Array(this.eb,0,8)}Ia.prototype=new p;Ia.prototype.constructor=Ia;function Ka(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.kc[0]=b;return(a.tb[0]|0)^(a.tb[1]|0)}
Ia.prototype.$classData=t({hd:0},!1,"java.lang.FloatingPointBits$",{hd:1,b:1});var Ja;function La(){Ja||(Ja=new Ia);return Ja}
function Ma(){this.nc=this.Qb=null;Na=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.Qb=a;this.nc=null}Ma.prototype=new p;Ma.prototype.constructor=Ma;function Oa(a,b,c){null!==a.Qb?(Pa||(Pa=new Qa),a=a.Qb,Ra||(Ra=new Sa),b=Ra.pc.call(a,b)?a[b]:c):b=Oa(a.nc,b,c);return b}Ma.prototype.$classData=t({od:0},!1,"java.lang.System$SystemProperties$",{od:1,b:1});var Na;function Qa(){}Qa.prototype=new p;Qa.prototype.constructor=Qa;Qa.prototype.$classData=t({td:0},!1,"java.lang.Utils$",{td:1,b:1});var Pa;function Sa(){this.pc=null;Ra=this;this.pc=Object.prototype.hasOwnProperty}
Sa.prototype=new p;Sa.prototype.constructor=Sa;Sa.prototype.$classData=t({ud:0},!1,"java.lang.Utils$Cache$",{ud:1,b:1});var Ra;function Ta(){}Ta.prototype=new p;Ta.prototype.constructor=Ta;Ta.prototype.$classData=t({vd:0},!1,"java.lang.reflect.Array$",{vd:1,b:1});var Ua;function Va(){}Va.prototype=new p;Va.prototype.constructor=Va;
function Wa(a,b,c){if(b===c)return!0;if(null===b||null===c)return!1;a=b.a.length;if(c.a.length!==a)return!1;for(var e=0;e!==a;){var g=b.a[e],f=g.u;g=g.t;var h=c.a[e],l=h.u;h=h.t;if(!x(y(),new k(f,g),new k(l,h)))return!1;e=1+e|0}return!0}function Xa(a,b,c){if(b===c)return!0;if(null===b||null===c)return!1;a=b.a.length;if(c.a.length!==a)return!1;for(var e=0;e!==a;){var g=b.a[e],f=c.a[e];if(!x(y(),g,f))return!1;e=1+e|0}return!0}
function Ya(a,b,c){if(b===c)return!0;if(null===b||null===c)return!1;a=b.a.length;if(c.a.length!==a)return!1;for(var e=0;e!==a;){var g=b.a[e],f=c.a[e];if(!x(y(),g,f))return!1;e=1+e|0}return!0}function Za(a,b,c){if(b===c)return!0;if(null===b||null===c)return!1;a=b.a.length;if(c.a.length!==a)return!1;for(var e=0;e!==a;){var g=b.a[e],f=c.a[e];if(!x(y(),n(g),n(f)))return!1;e=1+e|0}return!0}
function $a(a,b,c){if(b===c)return!0;if(null===b||null===c)return!1;a=b.a.length;if(c.a.length!==a)return!1;for(var e=0;e!==a;){var g=b.a[e],f=c.a[e];if(!x(y(),g,f))return!1;e=1+e|0}return!0}function ab(a,b,c){if(b===c)return!0;if(null===b||null===c)return!1;a=b.a.length;if(c.a.length!==a)return!1;for(var e=0;e!==a;){var g=b.a[e],f=c.a[e];if(!x(y(),g,f))return!1;e=1+e|0}return!0}
function bb(a,b,c){if(b===c)return!0;if(null===b||null===c)return!1;a=b.a.length;if(c.a.length!==a)return!1;for(var e=0;e!==a;){var g=b.a[e],f=c.a[e];if(!x(y(),g,f))return!1;e=1+e|0}return!0}function cb(a,b,c){if(b===c)return!0;if(null===b||null===c)return!1;a=b.a.length;if(c.a.length!==a)return!1;for(var e=0;e!==a;){var g=b.a[e],f=c.a[e];if(!x(y(),g,f))return!1;e=1+e|0}return!0}Va.prototype.$classData=t({wd:0},!1,"java.util.Arrays$",{wd:1,b:1});var db;function z(){db||(db=new Va);return db}
function eb(){this.ec=this.dc=null;fb=this;A();var a=gb("font-family","Arial, Helvetica, sans-serif");hb();this.dc=new ib("style",a);A();B();A();var b=C(B(),new (w(jb).m)([(A(),new D("This is some HTML in bold."))]));a=E().gb;F();b=G(H(),b);b=C(0,new (w(jb).m)([new I("b",a,b)]));a=E().gb;F();b=G(H(),b);this.ec=new I("p",a,b);A();a=C(B(),new (w(kb).m)([lb(A().Ya,"my-container")]));B();A();b=C(B(),new (w(kb).m)([this.dc]));B();var c=this.ec;A();var e=mb("Hello, world!");A();B();A();var g=nb(),f=C(0,
new (w(kb).m)([ob(g)]));g=w(jb).m;f=f.Xa();E();var h=C(B(),new (w(pb).m)([(A(),new D("Say hello!"))]));h=G(H(),h);c=C(0,new g([c,e,new I("button",f,h)]));F();b=G(H(),b);F();c=G(H(),c);b=C(0,new (w(jb).m)([new I("div",b,c)]));F();G(H(),a);F();G(H(),b)}eb.prototype=new p;eb.prototype.constructor=eb;eb.prototype.$classData=t({Jc:0},!1,"mdocjs$",{Jc:1,b:1});var fb;function qb(){fb||(fb=new eb)}function k(a,b){this.u=a;this.t=b}k.prototype=new p;k.prototype.constructor=k;
k.prototype.k=function(a){return a instanceof k?this.u===a.u&&this.t===a.t:!1};k.prototype.p=function(){return this.u^this.t};k.prototype.l=function(){rb();var a=this.u,b=this.t;return b===a>>31?""+a:0>b?"-"+sb(-a|0,0!==a?~b:-b|0):sb(a,b)};k.prototype.$classData=t({bd:0},!1,"org.scalajs.linker.runtime.RuntimeLong",{bd:1,b:1});
function sb(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+Math.clz32(1E9)|0)-(0!==b?Math.clz32(b):32+Math.clz32(a)|0)|0,e=c,g=0===(32&e)?1E9<<e:0;e=0===(32&e)?5E8>>>(31-e|0)|0|0<<e:1E9<<e;var f=a,h=b;for(a=b=0;0<=c&&0!==(-2097152&h);){var l=f,v=h,Hd=g,qa=e;if(v===qa?(-2147483648^l)>=(-2147483648^Hd):(-2147483648^v)>=(-2147483648^qa))l=h,v=e,h=f-g|0,l=(-2147483648^h)>(-2147483648^f)?-1+(l-v|0)|0:l-v|0,f=h,h=l,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;l=e>>>1|0;g=g>>>1|0|e<<31;e=l}c=h;if(0===
c?-1147483648<=(-2147483648^f):-2147483648<=(-2147483648^c))c=4294967296*h+ +(f>>>0),f=c/1E9,g=f/4294967296|0,e=b,b=f=e+(f|0)|0,a=(-2147483648^f)<(-2147483648^e)?1+(a+g|0)|0:a+g|0,f=c%1E9|0;c=""+f;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function tb(){this.ob=0}tb.prototype=new p;tb.prototype.constructor=tb;function ub(a,b,c){return 0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0)}
tb.prototype.$classData=t({cd:0},!1,"org.scalajs.linker.runtime.RuntimeLong$",{cd:1,b:1});var vb;function rb(){vb||(vb=new tb);return vb}function wb(a,b,c){if(a.e())a=""+b+")";else{var e=a.ua,g=new xb;g.fa=yb(new zb);a=e.call(a,g,b,c,")").fa.d}return a}function Ab(a,b,c,e,g){var f=b.fa;0!==(c.length|0)&&(f.d=""+f.d+c);a=a.n();if(a.q())for(c=a.h(),f.d=""+f.d+c;a.q();)f.d=""+f.d+e,c=a.h(),f.d=""+f.d+c;0!==(g.length|0)&&(f.d=""+f.d+g);return b}
function Bb(){this.Gc=null;Cb=this;this.Gc=new q(0);new (w(w(u)).m)(0);new (w(w(w(u))).m)(0);new (w(w(w(w(u)))).m)(0);new (w(w(w(w(w(u))))).m)(0);new (w(w(w(w(w(w(u)))))).m)(0)}Bb.prototype=new p;Bb.prototype.constructor=Bb;Bb.prototype.$classData=t({cf:0},!1,"scala.collection.immutable.VectorStatics$",{cf:1,b:1});var Cb;function Db(){Cb||(Cb=new Bb);return Cb}function Eb(){}Eb.prototype=new p;Eb.prototype.constructor=Eb;
Eb.prototype.$classData=t({ue:0},!1,"scala.collection.package$$colon$plus$",{ue:1,b:1});var Fb;function Gb(){}Gb.prototype=new p;Gb.prototype.constructor=Gb;Gb.prototype.$classData=t({ve:0},!1,"scala.collection.package$$plus$colon$",{ve:1,b:1});var Hb;function Ib(){}Ib.prototype=new p;Ib.prototype.constructor=Ib;Ib.prototype.$classData=t({Id:0},!1,"scala.math.Ordered$",{Id:1,b:1});var Jb;
function Kb(){this.gb=null;Lb=this;Mb||(Mb=new Nb);Mb||(Mb=new Nb);Ob||(Ob=new Pb);Qb||(Qb=new Rb);J();F();this.gb=H();Sb||(Sb=new Tb);Hb||(Hb=new Gb);Fb||(Fb=new Eb);Ub||(Ub=new Vb);Wb();Xb();Yb||(Yb=new Zb);$b||($b=new ac);bc||(bc=new cc);dc||(dc=new ec);fc||(fc=new gc);hc||(hc=new ic);Jb||(Jb=new Ib);jc||(jc=new kc);lc||(lc=new mc);nc||(nc=new oc);pc||(pc=new qc)}Kb.prototype=new p;Kb.prototype.constructor=Kb;Kb.prototype.$classData=t({Kd:0},!1,"scala.package$",{Kd:1,b:1});var Lb;
function E(){Lb||(Lb=new Kb);return Lb}function rc(){}rc.prototype=new p;rc.prototype.constructor=rc;function x(a,b,c){if(b===c)c=!0;else if(sc(b))a:if(sc(c))c=tc(b,c);else{if(c instanceof da){if("number"===typeof b){c=+b===ka(c);break a}if(b instanceof k){a=ja(b);b=a.t;c=ka(c);c=a.u===c&&b===c>>31;break a}}c=null===b?null===c:ia(b,c)}else c=b instanceof da?uc(b,c):null===b?null===c:ia(b,c);return c}
function tc(a,b){if("number"===typeof a){a=+a;if("number"===typeof b)return a===+b;if(b instanceof k){var c=ja(b);b=c.u;c=c.t;return a===ub(rb(),b,c)}return!1}if(a instanceof k){c=ja(a);a=c.u;c=c.t;if(b instanceof k){b=ja(b);var e=b.t;return a===b.u&&c===e}return"number"===typeof b?(b=+b,ub(rb(),a,c)===b):!1}return null===a?null===b:ia(a,b)}
function uc(a,b){if(b instanceof da)return ka(a)===ka(b);if(sc(b)){if("number"===typeof b)return+b===ka(a);if(b instanceof k){b=ja(b);var c=b.t;a=ka(a);return b.u===a&&c===a>>31}return null===b?null===a:ia(b,a)}return null===a&&null===b}rc.prototype.$classData=t({uf:0},!1,"scala.runtime.BoxesRunTime$",{uf:1,b:1});var vc;function y(){vc||(vc=new rc);return vc}function wc(){}wc.prototype=new p;wc.prototype.constructor=wc;
function xc(a,b,c){if(b instanceof q||b instanceof ya||b instanceof Ba||b instanceof za||b instanceof Aa)return b.a[c];if(b instanceof va)return n(b.a[c]);if(b instanceof wa||b instanceof xa||b instanceof ua)return b.a[c];if(null===b)throw new yc;throw new zc(b);}
function Ac(a,b){Ua||(Ua=new Ta);if(b instanceof q||b instanceof ua||b instanceof va||b instanceof wa||b instanceof xa||b instanceof ya||b instanceof za||b instanceof Aa||b instanceof Ba)a=b.a.length;else throw a=new Bc,K(a,"argument type mismatch"),a;return a}function Cc(a){B();var b=a.ia();return wb(b,a.$()+"(",",")}function C(a,b){return null===b?null:0===b.a.length?(a=Dc(),Ec||(Ec=new Fc),a.Ub||a.Ub||(a.zc=new Gc(new q(0)),a.Ub=!0),a.zc):new Gc(b)}
wc.prototype.$classData=t({xf:0},!1,"scala.runtime.ScalaRunTime$",{xf:1,b:1});var Hc;function B(){Hc||(Hc=new wc);return Hc}function Ic(){}Ic.prototype=new p;Ic.prototype.constructor=Ic;function Jc(a,b){a=b.u;b=b.t;return b===a>>31?a:a^b}
function L(a,b){a=2147483647<b?2147483647:-2147483648>b?-2147483648:b|0;if(a===b)return a;a=rb();if(-0x7fffffffffffffff>b){a.ob=-2147483648;var c=0}else if(0x7fffffffffffffff<=b)a.ob=2147483647,c=-1;else{c=b|0;var e=b/4294967296|0;a.ob=0>b&&0!==c?-1+e|0:e}a=a.ob;return ub(rb(),c,a)===b?c^a:Ka(La(),b)}function M(a,b){return null===b?0:"number"===typeof b?L(0,+b):b instanceof k?(a=ja(b),Jc(0,new k(a.u,a.t))):la(b)}function Kc(a,b){throw N(new O,""+b);}
Ic.prototype.$classData=t({Af:0},!1,"scala.runtime.Statics$",{Af:1,b:1});var Lc;function P(){Lc||(Lc=new Ic);return Lc}function Mc(){}Mc.prototype=new p;Mc.prototype.constructor=Mc;function Nc(a){Oc||(Oc=new Mc);return a instanceof Pc?a.nb:a}Mc.prototype.$classData=t({tf:0},!1,"scala.scalajs.runtime.package$",{tf:1,b:1});var Oc;function Qc(){}Qc.prototype=new p;Qc.prototype.constructor=Qc;function Rc(){}Rc.prototype=Qc.prototype;
function Q(a,b){a=Sc(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function Sc(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}function R(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function Tc(a){S();var b=a.Y();if(0===b)return ma(a.$());var c=Q(-889275714,ma(a.$()));for(var e=0;e<b;){var g=a.Z(e);c=Q(c,M(P(),g));e=1+e|0}return R(c^b)}
function Uc(a,b){var c=a.a.length;switch(c){case 0:return R(b^0);case 1:return R(Q(b,a.a[0])^1);default:var e=a.a[0],g=b=Q(b,e),f=a.a[1];e=f-e|0;for(var h=2;h<c;){b=Q(b,f);var l=a.a[h];if(e!==(l-f|0)){b=Q(b,l);for(h=1+h|0;h<c;)b=Q(b,a.a[h]),h=1+h|0;return R(b^c)}f=l;h=1+h|0}return R(Q(Q(g,e),f))}}var kb=t({Cb:0},!0,"tyrian.Attr",{Cb:1,b:1}),jb=t({Fb:0},!0,"tyrian.Elem",{Fb:1,b:1});function ob(a){return new Vc("click",new Wc((b=>()=>b)(a)))}function Xc(a){if(null===a)throw new yc;}Xc.prototype=new p;
Xc.prototype.constructor=Xc;Xc.prototype.$classData=t({Qc:0},!1,"tyrian.HtmlAttributes$AttributeNameBoolean",{Qc:1,b:1});function Yc(a){if(null===a)throw new yc;}Yc.prototype=new p;Yc.prototype.constructor=Yc;Yc.prototype.$classData=t({Rc:0},!1,"tyrian.HtmlAttributes$AttributeNameDouble",{Rc:1,b:1});function T(a){if(null===a)throw new yc;}T.prototype=new p;T.prototype.constructor=T;T.prototype.$classData=t({Sc:0},!1,"tyrian.HtmlAttributes$AttributeNameInt",{Sc:1,b:1});
function U(a,b){this.Uc=b;if(null===a)throw new yc;}U.prototype=new p;U.prototype.constructor=U;function lb(a,b){hb();return new ib(a.Uc,b)}U.prototype.$classData=t({Tc:0},!1,"tyrian.HtmlAttributes$AttributeNameString",{Tc:1,b:1});function Zc(a){if(null===a)throw new yc;}Zc.prototype=new p;Zc.prototype.constructor=Zc;Zc.prototype.$classData=t({Vc:0},!1,"tyrian.HtmlAttributes$PropertyNameBoolean",{Vc:1,b:1});function $c(a){if(null===a)throw new yc;}$c.prototype=new p;$c.prototype.constructor=$c;
$c.prototype.$classData=t({Wc:0},!1,"tyrian.HtmlAttributes$PropertyNameDouble",{Wc:1,b:1});function ad(a){if(null===a)throw new yc;}ad.prototype=new p;ad.prototype.constructor=ad;ad.prototype.$classData=t({Xc:0},!1,"tyrian.HtmlAttributes$PropertyNameString",{Xc:1,b:1});function mb(a){var b=E().gb;E();a=C(B(),new (w(pb).m)([(A(),new D(a))]));a=G(H(),a);return new I("p",b,a)}function bd(){cd=this;gb("","")}bd.prototype=new p;bd.prototype.constructor=bd;
function gb(a,b){dd();return""===a?""===b?"":ed(b)?b:b+";":""===b?ed(a)?a:a+";":a+":"+b+";"}function fd(a,b){dd();for(a=b;!a.e();)a.s(),a=a.y()}bd.prototype.$classData=t({Zc:0},!1,"tyrian.Style$package$Style$",{Zc:1,b:1});var cd;function dd(){cd||(cd=new bd);return cd}
function gd(a){0===(32&a.qb)<<24>>24&&0===(32&a.qb)<<24>>24&&(a.jc=new ya(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.qb=(32|a.qb)<<24>>24);return a.jc}function hd(){this.jc=null;this.qb=0}hd.prototype=new p;hd.prototype.constructor=hd;
hd.prototype.$classData=t({fd:0},!1,"java.lang.Character$",{fd:1,b:1,c:1});var id;function jd(a){throw new kd('For input string: "'+a+'"');}function ld(){}ld.prototype=new p;ld.prototype.constructor=ld;ld.prototype.$classData=t({id:0},!1,"java.lang.Integer$",{id:1,b:1,c:1});var md;function sc(a){return"number"===typeof a||a instanceof k}function nd(){}nd.prototype=new p;nd.prototype.constructor=nd;nd.prototype.$classData=t({ld:0},!1,"java.lang.String$",{ld:1,b:1,c:1});var od;
function K(a,b){a.oc=b;a.pd=null;a.qd=!0;a.rd=!0;a.ic()}
class pd extends Error{constructor(){super();this.pd=this.oc=null;this.rd=this.qd=!1}pb(){return this.oc}ic(){"[object Error]"!==Object.prototype.toString.call(this)&&void 0!==Error.captureStackTrace&&Error.captureStackTrace(this)}l(){var a=ha(this),b=this.pb();return null===b?a:a+": "+b}p(){return m.prototype.p.call(this)}k(a){return m.prototype.k.call(this,a)}get message(){var a=this.pb();return null===a?"":a}get name(){return ha(this)}toString(){return this.l()}}function qd(){}qd.prototype=new p;
qd.prototype.constructor=qd;qd.prototype.$classData=t({zd:0},!1,"scala.Array$",{zd:1,b:1,c:1});var ud;function Tb(){}Tb.prototype=new p;Tb.prototype.constructor=Tb;Tb.prototype.l=function(){return"::"};Tb.prototype.$classData=t({xe:0},!1,"scala.collection.immutable.$colon$colon$",{xe:1,b:1,c:1});var Sb;function ac(){}ac.prototype=new p;ac.prototype.constructor=ac;ac.prototype.$classData=t({Ye:0},!1,"scala.collection.immutable.Range$",{Ye:1,b:1,c:1});var $b;function Zb(){}Zb.prototype=new p;
Zb.prototype.constructor=Zb;Zb.prototype.$classData=t({nf:0},!1,"scala.collection.mutable.StringBuilder$",{nf:1,b:1,c:1});var Yb;function ec(){}ec.prototype=new p;ec.prototype.constructor=ec;ec.prototype.$classData=t({Fd:0},!1,"scala.math.Fractional$",{Fd:1,b:1,c:1});var dc;function gc(){}gc.prototype=new p;gc.prototype.constructor=gc;gc.prototype.$classData=t({Gd:0},!1,"scala.math.Integral$",{Gd:1,b:1,c:1});var fc;function ic(){}ic.prototype=new p;ic.prototype.constructor=ic;
ic.prototype.$classData=t({Hd:0},!1,"scala.math.Numeric$",{Hd:1,b:1,c:1});var hc;function vd(){}vd.prototype=new p;vd.prototype.constructor=vd;function wd(){}wd.prototype=vd.prototype;vd.prototype.l=function(){return"\x3cfunction0\x3e"};function xd(){}xd.prototype=new p;xd.prototype.constructor=xd;function yd(){}yd.prototype=xd.prototype;xd.prototype.l=function(){return"\x3cfunction1\x3e"};function zd(a){this.$b=a}zd.prototype=new p;zd.prototype.constructor=zd;zd.prototype.l=function(){return""+this.$b};
zd.prototype.$classData=t({vf:0},!1,"scala.runtime.IntRef",{vf:1,b:1,c:1});function Ad(a){this.ac=a}Ad.prototype=new p;Ad.prototype.constructor=Ad;Ad.prototype.l=function(){return""+this.ac};Ad.prototype.$classData=t({wf:0},!1,"scala.runtime.ObjectRef",{wf:1,b:1,c:1});function mc(){}mc.prototype=new p;mc.prototype.constructor=mc;mc.prototype.$classData=t({Nd:0},!1,"scala.util.Either$",{Nd:1,b:1,c:1});var lc;function oc(){}oc.prototype=new p;oc.prototype.constructor=oc;oc.prototype.l=function(){return"Left"};
oc.prototype.$classData=t({Od:0},!1,"scala.util.Left$",{Od:1,b:1,c:1});var nc;function qc(){}qc.prototype=new p;qc.prototype.constructor=qc;qc.prototype.l=function(){return"Right"};qc.prototype.$classData=t({Pd:0},!1,"scala.util.Right$",{Pd:1,b:1,c:1});var pc;
function Bd(){this.vc=this.J=0;Cd=this;this.J=ma("Seq");this.vc=ma("Map");ma("Set");var a=E().gb,b=this.vc,c=0,e=0,g=0,f=1;for(a=a.n();a.q();){var h=a.h();h=M(P(),h);c=c+h|0;e^=h;f=Math.imul(f,1|h);g=1+g|0}b=Q(b,c);b=Q(b,e);b=Sc(b,f);R(b^g)}Bd.prototype=new Rc;Bd.prototype.constructor=Bd;Bd.prototype.$classData=t({Qd:0},!1,"scala.util.hashing.MurmurHash3$",{Qd:1,Tf:1,b:1});var Cd;function S(){Cd||(Cd=new Bd);return Cd}class Dd extends pd{}function nb(){Ed||(Ed=new Fd);return Gd}
function Fd(){Ed=this;Gd=new Id(0,"Greet");new (w(Jd).m)([nb()])}Fd.prototype=new p;Fd.prototype.constructor=Fd;Fd.prototype.$classData=t({Lc:0},!1,"mdocjs$Msg$",{Lc:1,b:1,wb:1,Dd:1});var Ed;function Kd(){}Kd.prototype=new p;Kd.prototype.constructor=Kd;function Ld(){}Ld.prototype=Kd.prototype;function Md(){}Md.prototype=new p;Md.prototype.constructor=Md;function Nd(){}Nd.prototype=Md.prototype;function Od(){this.la=null;Pd=this;this.la=new Qd}Od.prototype=new p;Od.prototype.constructor=Od;
Od.prototype.$classData=t({ne:0},!1,"scala.collection.Iterator$",{ne:1,b:1,qa:1,c:1});var Pd;function J(){Pd||(Pd=new Od);return Pd}function Rd(a,b){this.Qe=a;this.Re=b}Rd.prototype=new p;Rd.prototype.constructor=Rd;Rd.prototype.s=function(){return this.Qe};Rd.prototype.w=function(){return this.Re};Rd.prototype.$classData=t({Pe:0},!1,"scala.collection.immutable.LazyList$State$Cons",{Pe:1,b:1,Oe:1,c:1});function Sd(){}Sd.prototype=new p;Sd.prototype.constructor=Sd;
Sd.prototype.Pb=function(){throw new Td("head of empty lazy list");};Sd.prototype.w=function(){throw new Ud("tail of empty lazy list");};Sd.prototype.s=function(){this.Pb()};Sd.prototype.$classData=t({Se:0},!1,"scala.collection.immutable.LazyList$State$Empty$",{Se:1,b:1,Oe:1,c:1});var Vd;function Wd(){Vd||(Vd=new Sd);return Vd}function cc(){}cc.prototype=new p;cc.prototype.constructor=cc;cc.prototype.$classData=t({Ed:0},!1,"scala.math.Equiv$",{Ed:1,b:1,Lf:1,c:1});var bc;function kc(){}
kc.prototype=new p;kc.prototype.constructor=kc;kc.prototype.$classData=t({Jd:0},!1,"scala.math.Ordering$",{Jd:1,b:1,Mf:1,c:1});var jc;function Xd(a){this.qf=a}Xd.prototype=new wd;Xd.prototype.constructor=Xd;Xd.prototype.$classData=t({pf:0},!1,"scala.scalajs.runtime.AnonFunction0",{pf:1,mg:1,b:1,Bf:1});function Wc(a){this.sf=a}Wc.prototype=new yd;Wc.prototype.constructor=Wc;Wc.prototype.v=function(a){return(0,this.sf)(a)};
Wc.prototype.$classData=t({rf:0},!1,"scala.scalajs.runtime.AnonFunction1",{rf:1,ng:1,b:1,A:1});function Yd(){Zd=this;hb()}Yd.prototype=new p;Yd.prototype.constructor=Yd;Yd.prototype.l=function(){return"Attribute"};Yd.prototype.$classData=t({Nc:0},!1,"tyrian.Attribute$",{Nc:1,b:1,wb:1,tc:1});var Zd;function hb(){Zd||(Zd=new Yd)}function $d(){(ae=this)||(ae=new $d)}$d.prototype=new p;$d.prototype.constructor=$d;$d.prototype.l=function(){return"Property"};
$d.prototype.$classData=t({Yc:0},!1,"tyrian.Property$",{Yc:1,b:1,wb:1,tc:1});var ae;class ce extends Dd{}ce.prototype.$classData=t({ha:0},!1,"java.lang.RuntimeException",{ha:1,na:1,oa:1,b:1,c:1});function yb(a){a.d="";return a}function zb(){this.d=null}zb.prototype=new p;zb.prototype.constructor=zb;zb.prototype.l=function(){return this.d};zb.prototype.g=function(){return this.d.length|0};zb.prototype.$classData=t({md:0},!1,"java.lang.StringBuilder",{md:1,b:1,ed:1,Gf:1,c:1});function de(){}
de.prototype=new p;de.prototype.constructor=de;function ee(){}d=ee.prototype=de.prototype;d.n=function(){return this};d.e=function(){return!this.q()};d.db=function(a){return this.Ab(a,-1)};d.Ab=function(a,b){a=0<a?a:0;b=0>b?-1:b<=a?0:b-a|0;return 0===b?J().la:new fe(this,a,b)};d.l=function(){return"\x3citerator\x3e"};d.ua=function(a,b,c,e){return Ab(this,a,b,c,e)};d.Xa=function(){F();return G(H(),this)};d.x=function(){return-1};function Nb(){ge||(ge=new he)}Nb.prototype=new Nd;
Nb.prototype.constructor=Nb;Nb.prototype.$classData=t({le:0},!1,"scala.collection.Iterable$",{le:1,me:1,b:1,qa:1,c:1});var Mb;function ie(){}ie.prototype=new p;ie.prototype.constructor=ie;function je(){}je.prototype=ie.prototype;function ke(a,b){var c=a.x();if(-1!==c){var e=b.x();c=-1!==e&&c!==e}else c=!1;if(c)return!1;a:{a=a.n();for(b=b.n();a.q()&&b.q();)if(!x(y(),a.h(),b.h())){b=!1;break a}b=a.q()===b.q()}return b}function he(){F()}he.prototype=new Nd;he.prototype.constructor=he;
he.prototype.$classData=t({Ke:0},!1,"scala.collection.immutable.Iterable$",{Ke:1,me:1,b:1,qa:1,c:1});var ge;function le(){this.Wb=null;me=this;this.Wb=ne(new oe(new Xd(()=>Wd())))}le.prototype=new p;le.prototype.constructor=le;function pe(a,b,c){return new oe(new Xd(((e,g)=>()=>{for(var f=e.ac,h=g.$b;0<h&&!f.e();)f=V(f).w(),e.ac=f,h=-1+h|0,g.$b=h;return V(f)})(new Ad(b),new zd(c))))}le.prototype.$classData=t({Me:0},!1,"scala.collection.immutable.LazyList$",{Me:1,b:1,Sa:1,qa:1,c:1});var me;
function Wb(){me||(me=new le);return me}function Vb(){}Vb.prototype=new p;Vb.prototype.constructor=Vb;Vb.prototype.$classData=t({$e:0},!1,"scala.collection.immutable.Stream$",{$e:1,b:1,Sa:1,qa:1,c:1});var Ub;class Bc extends ce{}Bc.prototype.$classData=t({lc:0},!1,"java.lang.IllegalArgumentException",{lc:1,ha:1,na:1,oa:1,b:1,c:1});function N(a,b){K(a,b);return a}class O extends ce{}O.prototype.$classData=t({mc:0},!1,"java.lang.IndexOutOfBoundsException",{mc:1,ha:1,na:1,oa:1,b:1,c:1});
class yc extends ce{constructor(){super();K(this,null)}}yc.prototype.$classData=t({jd:0},!1,"java.lang.NullPointerException",{jd:1,ha:1,na:1,oa:1,b:1,c:1});class Ud extends ce{constructor(a){super();K(this,a)}}Ud.prototype.$classData=t({sd:0},!1,"java.lang.UnsupportedOperationException",{sd:1,ha:1,na:1,oa:1,b:1,c:1});class Td extends ce{constructor(a){super();K(this,a)}}Td.prototype.$classData=t({xd:0},!1,"java.util.NoSuchElementException",{xd:1,ha:1,na:1,oa:1,b:1,c:1});function qe(){}
qe.prototype=new p;qe.prototype.constructor=qe;function re(){}re.prototype=qe.prototype;qe.prototype.ia=function(){return new W(this)};var Jd=t({cc:0},!1,"mdocjs$Msg",{cc:1,b:1,r:1,ja:1,c:1,Ld:1});qe.prototype.$classData=Jd;
class zc extends ce{constructor(a){super();this.qc=null;this.Rb=!1;this.vb=a;K(this,null)}pb(){if(!this.Rb&&!this.Rb){if(null===this.vb)var a="null";else try{a=oa(this.vb)+" (of class "+ha(this.vb)+")"}catch(b){if(Oc||(Oc=new Mc),null!==(b instanceof pd?b:new Pc(b)))a="an instance of class "+ha(this.vb);else throw b;}this.qc=a;this.Rb=!0}return this.qc}}zc.prototype.$classData=t({Ad:0},!1,"scala.MatchError",{Ad:1,ha:1,na:1,oa:1,b:1,c:1});function se(){}se.prototype=new p;
se.prototype.constructor=se;function te(){}te.prototype=se.prototype;se.prototype.e=function(){return this===ue()};se.prototype.x=function(){return this.e()?0:1};se.prototype.n=function(){if(this.e())var a=J().la;else throw J(),new Td("None.get");return a};function W(a){this.sc=this.fb=0;this.rc=null;if(null===a)throw Nc(null);this.rc=a;this.fb=0;this.sc=a.Y()}W.prototype=new ee;W.prototype.constructor=W;W.prototype.q=function(){return this.fb<this.sc};
W.prototype.h=function(){var a=this.rc.Z(this.fb);this.fb=1+this.fb|0;return a};W.prototype.$classData=t({Cd:0},!1,"scala.Product$$anon$1",{Cd:1,C:1,b:1,z:1,i:1,j:1});function ve(a,b){this.Za=a;this.$a=b}ve.prototype=new p;ve.prototype.constructor=ve;d=ve.prototype;d.Y=function(){return 2};d.Z=function(a){a:switch(a){case 0:a=this.Za;break a;case 1:a=this.$a;break a;default:throw N(new O,a+" is out of bounds (min 0, max 1)");}return a};d.l=function(){return"("+this.Za+","+this.$a+")"};d.$=function(){return"Tuple2"};
d.ia=function(){return new X(this)};d.p=function(){return Tc(this)};d.k=function(a){return this===a?!0:a instanceof ve?x(y(),this.Za,a.Za)&&x(y(),this.$a,a.$a):!1};var we=t({dd:0},!1,"scala.Tuple2",{dd:1,b:1,Jf:1,ja:1,r:1,c:1});ve.prototype.$classData=we;function xe(){}xe.prototype=new Ld;xe.prototype.constructor=xe;xe.prototype.$classData=t({he:0},!1,"scala.collection.ClassTagSeqFactory$AnySeqDelegate",{he:1,Xf:1,b:1,qa:1,c:1,Sa:1});function Qd(){}Qd.prototype=new ee;Qd.prototype.constructor=Qd;
d=Qd.prototype;d.q=function(){return!1};d.x=function(){return 0};d.Ab=function(){return this};d.h=function(){throw new Td("next on empty iterator");};d.$classData=t({oe:0},!1,"scala.collection.Iterator$$anon$19",{oe:1,C:1,b:1,z:1,i:1,j:1});function ye(a){for(;0<a.Aa;)a.Ra.q()?(a.Ra.h(),a.Aa=-1+a.Aa|0):a.Aa=0}function ze(a,b){if(0>a.ga)return-1;a=a.ga-b|0;return 0>a?0:a}function fe(a,b,c){this.Ra=a;this.ga=c;this.Aa=b}fe.prototype=new ee;fe.prototype.constructor=fe;d=fe.prototype;
d.x=function(){var a=this.Ra.x();if(0>a)return-1;a=a-this.Aa|0;a=0>a?0:a;if(0>this.ga)return a;var b=this.ga;return b<a?b:a};d.q=function(){ye(this);return 0!==this.ga&&this.Ra.q()};d.h=function(){ye(this);return 0<this.ga?(this.ga=-1+this.ga|0,this.Ra.h()):0>this.ga?this.Ra.h():J().la.h()};d.Ab=function(a,b){a=0<a?a:0;if(0>b)b=ze(this,a);else if(b<=a)b=0;else if(0>this.ga)b=b-a|0;else{var c=ze(this,a);b=b-a|0;b=c<b?c:b}if(0===b)return J().la;this.Aa=this.Aa+a|0;this.ga=b;return this};
d.$classData=t({pe:0},!1,"scala.collection.Iterator$SliceIterator",{pe:1,C:1,b:1,z:1,i:1,j:1});function Ae(a,b){if(0>b)throw N(new O,""+b);a=a.hc(b);if(a.e())throw N(new O,""+b);return a.s()}function Be(a,b){if(b&&b.$classData&&b.$classData.N.Tb)a:for(;;){if(a===b){a=!0;break a}if((a.e()?0:!b.e())&&x(y(),a.s(),b.s()))a=a.y(),b=b.y();else{a=a.e()&&b.e();break a}}else a=ke(a,b);return a}function Ce(a){this.yb=a}Ce.prototype=new ee;Ce.prototype.constructor=Ce;Ce.prototype.q=function(){return!this.yb.e()};
Ce.prototype.h=function(){var a=this.yb.s();this.yb=this.yb.y();return a};Ce.prototype.$classData=t({se:0},!1,"scala.collection.StrictOptimizedLinearSeqOps$$anon$1",{se:1,C:1,b:1,z:1,i:1,j:1});function Rb(){Xb()}Rb.prototype=new je;Rb.prototype.constructor=Rb;Rb.prototype.$classData=t({Je:0},!1,"scala.collection.immutable.IndexedSeq$",{Je:1,qe:1,b:1,Sa:1,qa:1,c:1});var Qb;function De(a){this.kb=a}De.prototype=new ee;De.prototype.constructor=De;De.prototype.q=function(){return!this.kb.e()};
De.prototype.h=function(){if(this.kb.e())return J().la.h();var a=V(this.kb).s();this.kb=V(this.kb).w();return a};De.prototype.$classData=t({Ne:0},!1,"scala.collection.immutable.LazyList$LazyIterator",{Ne:1,C:1,b:1,z:1,i:1,j:1});function Ee(){Fe=this;H();H()}Ee.prototype=new p;Ee.prototype.constructor=Ee;Ee.prototype.$classData=t({Ue:0},!1,"scala.collection.immutable.List$",{Ue:1,b:1,te:1,Sa:1,qa:1,c:1});var Fe;function F(){Fe||(Fe=new Ee)}
function Ge(a){a.V<=a.L&&J().la.h();a.mb=1+a.mb|0;for(var b=null;0===b.a.length;)a.mb=1+a.mb|0,b=null;a.zb=a.Va;var c=a.We/2|0,e=a.mb-c|0;a.Na=(1+c|0)-(0>e?-e|0:e)|0;c=a.Na;switch(c){case 1:a.sa=b;break;case 2:a.Ka=b;break;case 3:a.La=b;break;case 4:a.Ma=b;break;case 5:a.Ua=b;break;case 6:a.Zb=b;break;default:throw new zc(c);}a.Va=a.zb+Math.imul(b.a.length,1<<Math.imul(5,-1+a.Na|0))|0;a.Va>a.ta&&(a.Va=a.ta);1<a.Na&&(a.lb=-1+(1<<Math.imul(5,a.Na))|0)}
function He(a,b,c){this.Zb=this.Ua=this.Ma=this.La=this.Ka=null;this.ta=b;this.We=c;this.sa=a.Wa;this.Ja=this.sa.a.length;this.lb=this.L=0;this.V=this.ta;this.mb=0;this.Na=1;this.zb=0;this.Va=this.Ja}He.prototype=new p;He.prototype.constructor=He;d=He.prototype;d.n=function(){return this};d.e=function(){return this.V<=this.L};d.l=function(){return"\x3citerator\x3e"};d.ua=function(a,b,c,e){return Ab(this,a,b,c,e)};d.Xa=function(){F();return G(H(),this)};d.x=function(){return this.V-this.L|0};
d.q=function(){return this.V>this.L};
d.h=function(){if(this.L===this.Ja){var a=(this.L-this.V|0)+this.ta|0;a===this.Va&&Ge(this);if(1<this.Na){a=a-this.zb|0;var b=this.lb^a;1024>b?this.sa=this.Ka.a[31&(a>>>5|0)]:(32768>b?this.Ka=this.La.a[31&(a>>>10|0)]:(1048576>b?this.La=this.Ma.a[31&(a>>>15|0)]:(33554432>b?this.Ma=this.Ua.a[31&(a>>>20|0)]:(this.Ua=this.Zb.a[a>>>25|0],this.Ma=this.Ua.a[0]),this.La=this.Ma.a[0]),this.Ka=this.La.a[0]),this.sa=this.Ka.a[0]);this.lb=a}this.V=this.V-this.L|0;a=this.sa.a.length;b=this.V;this.Ja=a<b?a:b;this.L=
0}a=this.sa.a[this.L];this.L=1+this.L|0;return a};
d.db=function(a){if(0<a){a=((this.L-this.V|0)+this.ta|0)+a|0;var b=this.ta;a=a<b?a:b;if(a===this.ta)this.Ja=this.V=this.L=0;else{for(;a>=this.Va;)Ge(this);b=a-this.zb|0;if(1<this.Na){var c=this.lb^b;1024>c||(32768>c||(1048576>c||(33554432>c||(this.Ua=this.Zb.a[b>>>25|0]),this.Ma=this.Ua.a[31&(b>>>20|0)]),this.La=this.Ma.a[31&(b>>>15|0)]),this.Ka=this.La.a[31&(b>>>10|0)]);this.sa=this.Ka.a[31&(b>>>5|0)];this.lb=b}this.Ja=this.sa.a.length;this.L=31&b;this.V=this.L+(this.ta-a|0)|0;this.Ja>this.V&&(this.Ja=
this.V)}}return this};d.$classData=t({Ve:0},!1,"scala.collection.immutable.NewVectorIterator",{Ve:1,b:1,z:1,i:1,j:1,sb:1});function Pb(){F()}Pb.prototype=new je;Pb.prototype.constructor=Pb;Pb.prototype.$classData=t({Ze:0},!1,"scala.collection.immutable.Seq$",{Ze:1,qe:1,b:1,Sa:1,qa:1,c:1});var Ob;
function Ie(){this.Ec=0;this.Fc=null;Je=this;try{var a=Oa;Na||(Na=new Ma);var b=a(Na,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250");md||(md=new ld);var c=null===b?0:b.length|0;0===c&&jd(b);var e=65535&(b.charCodeAt(0)|0),g=(a=45===e)?2147483648:2147483647;e=a||43===e?1:0;e>=(b.length|0)&&jd(b);for(var f=0;e!==c;){id||(id=new hd);var h=id,l=65535&(b.charCodeAt(e)|0);if(256>l)var v=48<=l&&57>=l?-48+l|0:65<=l&&90>=l?-55+l|0:97<=l&&122>=l?-87+l|0:-1;else if(65313<=l&&65338>=
l)v=-65303+l|0;else if(65345<=l&&65370>=l)v=-65335+l|0;else{var Hd=gd(h);b:{z();for(var qa=Hd,tf=l,rd=0,be=qa.a.length;;){if(rd===be){var sd=-1-rd|0;break b}var td=(rd+be|0)>>>1|0,uf=qa.a[td];if(tf<uf)be=td;else{if(x(y(),tf,uf)){sd=td;break b}rd=1+td|0}}}qa=0>sd?-2-sd|0:sd;if(0>qa)v=-1;else{var vf=l-gd(h).a[qa]|0;v=9<vf?-1:vf}}var wf=10>v?v:-1;f=10*f+wf;(-1===wf||f>g)&&jd(b);e=1+e|0}}catch(gg){throw gg;}this.Ec=a?-f|0:f|0;this.Fc=new He(Ke(),0,0)}Ie.prototype=new p;Ie.prototype.constructor=Ie;
Ie.prototype.$classData=t({af:0},!1,"scala.collection.immutable.Vector$",{af:1,b:1,te:1,Sa:1,qa:1,c:1});var Je;function Xb(){Je||(Je=new Ie);return Je}function X(a){this.Hc=0;this.zf=a;this.Bb=0;this.Hc=a.Y()}X.prototype=new ee;X.prototype.constructor=X;X.prototype.q=function(){return this.Bb<this.Hc};X.prototype.h=function(){var a=this.zf.Z(this.Bb);this.Bb=1+this.Bb|0;return a};X.prototype.$classData=t({yf:0},!1,"scala.runtime.ScalaRunTime$$anon$1",{yf:1,C:1,b:1,z:1,i:1,j:1});
function ib(a,b){this.Db=a;this.Eb=b}ib.prototype=new p;ib.prototype.constructor=ib;d=ib.prototype;d.ia=function(){return new W(this)};d.p=function(){return Tc(this)};d.k=function(a){return this===a?!0:a instanceof ib?this.Db===a.Db&&this.Eb===a.Eb:!1};d.l=function(){return Cc(this)};d.Y=function(){return 2};d.$=function(){return"Attribute"};d.Z=function(a){if(0===a)return this.Db;if(1===a)return this.Eb;throw N(new O,""+a);};var Le=t({Mc:0},!1,"tyrian.Attribute",{Mc:1,b:1,Cb:1,r:1,ja:1,c:1});
ib.prototype.$classData=Le;function Vc(a,b){this.Hb=a;this.Gb=b}Vc.prototype=new p;Vc.prototype.constructor=Vc;d=Vc.prototype;d.ia=function(){return new W(this)};d.p=function(){return Tc(this)};d.k=function(a){if(this===a)return!0;if(a instanceof Vc&&this.Hb===a.Hb){var b=this.Gb;a=a.Gb;return null===b?null===a:b.k(a)}return!1};d.l=function(){return Cc(this)};d.Y=function(){return 2};d.$=function(){return"Event"};
d.Z=function(a){if(0===a)return this.Hb;if(1===a)return this.Gb;throw N(new O,""+a);};d.$classData=t({Oc:0},!1,"tyrian.Event",{Oc:1,b:1,Cb:1,r:1,ja:1,c:1});
function Me(){this.Ya=this.fc=null;Ne=this;new U(this,"accept");new U(this,"accesskey");new U(this,"action");new U(this,"alt");new U(this,"autocomplete");new U(this,"charset");new U(this,"cite");this.fc=new U(this,"class");new U(this,"class");new U(this,"class");new U(this,"class");new U(this,"class");new U(this,"cols");new T(this,"cols");new U(this,"colspan");new T(this,"colspan");new U(this,"colspan");new T(this,"colspan");new U(this,"content");new U(this,"contenteditable");new Xc(this,"contenteditable");
new U(this,"contenteditable");new Xc(this,"contenteditable");new U(this,"coords");new U(this,"data");new U(this,"datetime");new U(this,"datetime");new U(this,"dir");new U(this,"dirname");new U(this,"draggable");new Xc(this,"draggable");new U(this,"enctype");new U(this,"enctype");new U(this,"for");new U(this,"for");new U(this,"for");new U(this,"form");new U(this,"formaction");new U(this,"formaction");new U(this,"headers");new U(this,"height");new T(this,"height");new U(this,"high");new Yc(this,"high");
new U(this,"href");new U(this,"hreflang");new U(this,"hreflang");new U(this,"http");this.Ya=new U(this,"id");new U(this,"kind");new U(this,"label");new U(this,"lang");new U(this,"list");new U(this,"low");new Yc(this,"low");new U(this,"max");new T(this,"max");new U(this,"maxlength");new T(this,"maxlength");new U(this,"maxlength");new T(this,"maxlength");new U(this,"media");new U(this,"method");new U(this,"min");new T(this,"min");new U(this,"multiple");new U(this,"muted");new U(this,"name");new U(this,
"optimum");new Yc(this,"optimum");new U(this,"pattern");new U(this,"placeholder");new U(this,"poster");new U(this,"preload");new U(this,"rel");new U(this,"rows");new T(this,"rows");new U(this,"rowspan");new T(this,"rowspan");new U(this,"rowspan");new T(this,"rowspan");new U(this,"scope");new U(this,"shape");new U(this,"size");new T(this,"size");new U(this,"sizes");new U(this,"span");new T(this,"span");new U(this,"spellcheck");new Xc(this,"spellcheck");new U(this,"spellcheck");new Xc(this,"spellcheck");
new U(this,"src");new U(this,"srcdoc");new U(this,"srcdoc");new U(this,"srclang");new U(this,"srclang");new U(this,"srcset");new U(this,"srcset");new U(this,"start");new T(this,"start");new U(this,"step");new T(this,"step");new U(this,"style");new U(this,"tabindex");new T(this,"tabindex");new U(this,"tabindex");new T(this,"tabindex");new U(this,"target");new U(this,"title");new U(this,"translate");new U(this,"type");new U(this,"type");new U(this,"type");new U(this,"type");new U(this,"usemap");new U(this,
"usemap");new U(this,"width");new T(this,"width");new U(this,"wrap");new ad(this,"value");new $c(this,"value");new Zc(this,"value")}Me.prototype=new p;Me.prototype.constructor=Me;function Oe(){A();var a=C(B(),new (w(we).m)([new ve("width","100px"),new ve("height","50px")]));hb();fd(dd(),a.ub(new Wc(b=>gb(b.Za,b.$a))).Xa())}Me.prototype.$classData=t({Pc:0},!1,"tyrian.Html$",{Pc:1,b:1,Ef:1,Df:1,wb:1,Dd:1});var Ne;function A(){Ne||(Ne=new Me);return Ne}function D(a){this.Lb=a}D.prototype=new p;
D.prototype.constructor=D;d=D.prototype;d.ia=function(){return new W(this)};d.p=function(){return Tc(this)};d.k=function(a){return this===a?!0:a instanceof D?this.Lb===a.Lb:!1};d.l=function(){return Cc(this)};d.Y=function(){return 1};d.$=function(){return"Text"};d.Z=function(a){if(0===a)return this.Lb;throw N(new O,""+a);};var pb=t({ad:0},!1,"tyrian.Text",{ad:1,b:1,Fb:1,r:1,ja:1,c:1});D.prototype.$classData=pb;function na(a){a=+a;return Ka(La(),a)}
class kd extends Bc{constructor(a){super();K(this,a)}}kd.prototype.$classData=t({kd:0},!1,"java.lang.NumberFormatException",{kd:1,lc:1,ha:1,na:1,oa:1,b:1,c:1});function ma(a){for(var b=0,c=1,e=-1+(a.length|0)|0;0<=e;)b=b+Math.imul(65535&(a.charCodeAt(e)|0),c)|0,c=Math.imul(31,c),e=-1+e|0;return b}function ed(a){return";"===a.substring((a.length|0)-1|0)}class Pe extends O{constructor(){super();K(this,null)}}
Pe.prototype.$classData=t({nd:0},!1,"java.lang.StringIndexOutOfBoundsException",{nd:1,mc:1,ha:1,na:1,oa:1,b:1,c:1});function Qe(){}Qe.prototype=new te;Qe.prototype.constructor=Qe;d=Qe.prototype;d.$=function(){return"None"};d.Y=function(){return 0};d.Z=function(a){return Kc(P(),a)};d.ia=function(){return new X(this)};d.p=function(){return 2433880};d.l=function(){return"None"};d.$classData=t({Bd:0},!1,"scala.None$",{Bd:1,If:1,b:1,i:1,ja:1,r:1,c:1});var Re;function ue(){Re||(Re=new Qe);return Re}
function Se(){}Se.prototype=new p;Se.prototype.constructor=Se;function Te(){}Te.prototype=Se.prototype;Se.prototype.wa=function(){return this.Oa()};Se.prototype.ua=function(a,b,c,e){return Ab(this,a,b,c,e)};Se.prototype.Xa=function(){F();return G(H(),this)};Se.prototype.x=function(){return-1};function Ue(a,b){a.aa=b;a.f=0;a.M=Ac(B(),a.aa);return a}function Ve(){this.aa=null;this.M=this.f=0}Ve.prototype=new ee;Ve.prototype.constructor=Ve;function We(){}d=We.prototype=Ve.prototype;
d.x=function(){return this.M-this.f|0};d.q=function(){return this.f<this.M};d.h=function(){try{var a=xc(B(),this.aa,this.f);this.f=1+this.f|0;return a}catch(b){throw b;}};d.db=function(a){if(0<a){a=this.f+a|0;if(0>a)a=this.M;else{var b=this.M;a=b<a?b:a}this.f=a}return this};d.$classData=t({ka:0},!1,"scala.collection.ArrayOps$ArrayIterator",{ka:1,C:1,b:1,z:1,i:1,j:1,c:1});function Xe(a){this.Q=0;this.ke=a;this.za=0;this.Q=a.g()}Xe.prototype=new ee;Xe.prototype.constructor=Xe;d=Xe.prototype;d.x=function(){return this.Q};
d.q=function(){return 0<this.Q};d.h=function(){if(0<this.Q){var a=this.ke.o(this.za);this.za=1+this.za|0;this.Q=-1+this.Q|0;return a}return J().la.h()};d.db=function(a){0<a&&(this.za=this.za+a|0,a=this.Q-a|0,this.Q=0>a?0:a);return this};d.Ab=function(a,b){a=0>a?0:a>this.Q?this.Q:a;b=(0>b?0:b>this.Q?this.Q:b)-a|0;this.Q=0>b?0:b;this.za=this.za+a|0;return this};d.$classData=t({je:0},!1,"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{je:1,C:1,b:1,z:1,i:1,j:1,c:1});
function Ye(){this.zc=null;this.Ub=!1;Ze=this;new xe(this)}Ye.prototype=new p;Ye.prototype.constructor=Ye;
function $e(a,b){if(null===b)return null;if(b instanceof q)return new Gc(b);if(b instanceof ya)return new af(b);if(b instanceof Ba)return new bf(b);if(b instanceof za)return new cf(b);if(b instanceof Aa)return new df(b);if(b instanceof va)return new ef(b);if(b instanceof wa)return new ff(b);if(b instanceof xa)return new gf(b);if(b instanceof ua)return new hf(b);if(b&&b.$classData&&1===b.$classData.Qa&&b.$classData.Pa.N.Hf)return new jf(b);throw new zc(b);}
Ye.prototype.$classData=t({ye:0},!1,"scala.collection.immutable.ArraySeq$",{ye:1,b:1,cg:1,Yf:1,Wf:1,Zf:1,c:1});var Ze;function Dc(){Ze||(Ze=new Ye);return Ze}function I(a,b,c){this.Kb=a;this.Ib=b;this.Jb=c}I.prototype=new p;I.prototype.constructor=I;d=I.prototype;d.ia=function(){return new W(this)};d.p=function(){return Tc(this)};
d.k=function(a){if(this===a)return!0;if(a instanceof I){if(this.Kb===a.Kb){var b=this.Ib,c=a.Ib;b=null===b?null===c:b.k(c)}else b=!1;if(b)return b=this.Jb,a=a.Jb,null===b?null===a:b.k(a)}return!1};d.l=function(){return Cc(this)};d.Y=function(){return 3};d.$=function(){return"Tag"};d.Z=function(a){switch(a){case 0:return this.Kb;case 1:return this.Ib;case 2:return this.Jb;default:throw N(new O,""+a);}};d.$classData=t({$c:0},!1,"tyrian.Tag",{$c:1,b:1,Fb:1,Cf:1,r:1,ja:1,c:1});
function kf(a){this.aa=null;this.M=this.f=0;this.Sd=a;Ue(this,a)}kf.prototype=new We;kf.prototype.constructor=kf;kf.prototype.h=function(){try{var a=this.Sd.a[this.f];this.f=1+this.f|0}catch(b){throw b;}return a};kf.prototype.$classData=t({Rd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcB$sp",{Rd:1,ka:1,C:1,b:1,z:1,i:1,j:1,c:1});function lf(a){this.aa=null;this.M=this.f=0;this.Ud=a;Ue(this,a)}lf.prototype=new We;lf.prototype.constructor=lf;
lf.prototype.h=function(){try{var a=this.Ud.a[this.f];this.f=1+this.f|0}catch(b){throw b;}return n(a)};lf.prototype.$classData=t({Td:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcC$sp",{Td:1,ka:1,C:1,b:1,z:1,i:1,j:1,c:1});function mf(a){this.aa=null;this.M=this.f=0;this.Wd=a;Ue(this,a)}mf.prototype=new We;mf.prototype.constructor=mf;mf.prototype.h=function(){try{var a=this.Wd.a[this.f];this.f=1+this.f|0}catch(b){throw b;}return a};
mf.prototype.$classData=t({Vd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcD$sp",{Vd:1,ka:1,C:1,b:1,z:1,i:1,j:1,c:1});function nf(a){this.aa=null;this.M=this.f=0;this.Yd=a;Ue(this,a)}nf.prototype=new We;nf.prototype.constructor=nf;nf.prototype.h=function(){try{var a=this.Yd.a[this.f];this.f=1+this.f|0}catch(b){throw b;}return a};nf.prototype.$classData=t({Xd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcF$sp",{Xd:1,ka:1,C:1,b:1,z:1,i:1,j:1,c:1});
function of(a){this.aa=null;this.M=this.f=0;this.$d=a;Ue(this,a)}of.prototype=new We;of.prototype.constructor=of;of.prototype.h=function(){try{var a=this.$d.a[this.f];this.f=1+this.f|0}catch(b){throw b;}return a};of.prototype.$classData=t({Zd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcI$sp",{Zd:1,ka:1,C:1,b:1,z:1,i:1,j:1,c:1});function pf(a){this.aa=null;this.M=this.f=0;this.be=a;Ue(this,a)}pf.prototype=new We;pf.prototype.constructor=pf;
pf.prototype.h=function(){try{var a=this.be.a[this.f],b=a.u,c=a.t;this.f=1+this.f|0;var e=new k(b,c)}catch(g){throw g;}return e};pf.prototype.$classData=t({ae:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcJ$sp",{ae:1,ka:1,C:1,b:1,z:1,i:1,j:1,c:1});function qf(a){this.aa=null;this.M=this.f=0;this.de=a;Ue(this,a)}qf.prototype=new We;qf.prototype.constructor=qf;qf.prototype.h=function(){try{var a=this.de.a[this.f];this.f=1+this.f|0}catch(b){throw b;}return a};
qf.prototype.$classData=t({ce:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcS$sp",{ce:1,ka:1,C:1,b:1,z:1,i:1,j:1,c:1});function rf(a){this.aa=null;this.M=this.f=0;Ue(this,a)}rf.prototype=new We;rf.prototype.constructor=rf;rf.prototype.h=function(){try{this.f=1+this.f|0}catch(a){throw a;}};rf.prototype.$classData=t({ee:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcV$sp",{ee:1,ka:1,C:1,b:1,z:1,i:1,j:1,c:1});function sf(a){this.aa=null;this.M=this.f=0;this.ge=a;Ue(this,a)}sf.prototype=new We;
sf.prototype.constructor=sf;sf.prototype.h=function(){try{var a=this.ge.a[this.f];this.f=1+this.f|0}catch(b){throw b;}return a};sf.prototype.$classData=t({fe:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcZ$sp",{fe:1,ka:1,C:1,b:1,z:1,i:1,j:1,c:1});function xf(){}xf.prototype=new p;xf.prototype.constructor=xf;function yf(){}yf.prototype=xf.prototype;
class Pc extends ce{constructor(a){super();this.nb=a;K(this,null)}pb(){return oa(this.nb)}ic(){}$(){return"JavaScriptException"}Y(){return 1}Z(a){return 0===a?this.nb:Kc(P(),a)}ia(){return new X(this)}p(){return Tc(this)}k(a){if(this===a)return!0;if(a instanceof Pc){var b=this.nb;a=a.nb;return x(y(),b,a)}return!1}}Pc.prototype.$classData=t({of:0},!1,"scala.scalajs.js.JavaScriptException",{of:1,ha:1,na:1,oa:1,b:1,c:1,ja:1,r:1});function zf(){this.uc=null;this.Sb=0}zf.prototype=new yf;
zf.prototype.constructor=zf;function Af(){}Af.prototype=zf.prototype;zf.prototype.l=function(){return this.uc};zf.prototype.k=function(a){return this===a};zf.prototype.p=function(){return this.Sb};function Bf(){}Bf.prototype=new Te;Bf.prototype.constructor=Bf;function Cf(){}Cf.prototype=Bf.prototype;Bf.prototype.l=function(){return this.wa()+"(\x3cnot computed\x3e)"};function Fc(){this.Sb=0;this.uc="Object";ue();E();Fa(u);this.Sb=sa(this)}Fc.prototype=new Af;Fc.prototype.constructor=Fc;
Fc.prototype.$classData=t({Md:0},!1,"scala.reflect.ManifestFactory$ObjectManifest$",{Md:1,Rf:1,Qf:1,b:1,Pf:1,Of:1,Nf:1,Sf:1,c:1,r:1});var Ec;function Id(a,b){this.bc=b}Id.prototype=new re;Id.prototype.constructor=Id;d=Id.prototype;d.Y=function(){return 0};d.Z=function(a){throw N(new O,""+a);};d.$=function(){return this.bc};d.l=function(){return this.bc};d.$classData=t({Kc:0},!1,"mdocjs$$anon$1",{Kc:1,cc:1,b:1,r:1,ja:1,c:1,Ld:1,og:1,wb:1,tc:1,Kf:1});
function Y(a,b){return a===b?!0:b&&b.$classData&&b.$classData.N.G&&b.Ob(a)?a.hb(b):!1}function Df(){}Df.prototype=new Te;Df.prototype.constructor=Df;function Ef(){}d=Ef.prototype=Df.prototype;d.Ob=function(){return!0};d.k=function(a){return Y(this,a)};
d.p=function(){var a=S();if(this&&this.$classData&&this.$classData.N.O)a:{var b=a.J;a=this.g();switch(a){case 0:a=R(b^0);break a;case 1:a=b;b=this.o(0);a=R(Q(a,M(P(),b))^1);break a;default:var c=this.o(0),e=M(P(),c);c=b=Q(b,e);var g=this.o(1);g=M(P(),g);var f=g-e|0;for(e=2;e<a;){b=Q(b,g);var h=this.o(e);h=M(P(),h);if(f!==(h-g|0)){b=Q(b,h);for(e=1+e|0;e<a;)c=this.o(e),b=Q(b,M(P(),c)),e=1+e|0;a=R(b^a);break a}g=h;e=1+e|0}a=R(Q(Q(c,f),g))}}else if(this instanceof Ff){a=a.J;e=0;g=a;b=c=h=f=0;for(var l=
this;!l.e();){var v=l.s();l=l.y();v=M(P(),v);g=Q(g,v);switch(f){case 0:b=v;f=1;break;case 1:h=v-c|0;f=2;break;case 2:h!==(v-c|0)&&(f=3)}c=v;e=1+e|0}2===f?(e=h,a=R(Q(Q(Q(a,b),e),c))):a=R(g^e)}else a:if(b=a.J,a=this.n(),a.q())if(c=a.h(),a.q()){e=a.h();f=M(P(),c);c=b=Q(b,f);g=M(P(),e);f=g-f|0;for(e=2;a.q();){b=Q(b,g);h=a.h();h=M(P(),h);if(f!==(h-g|0)){b=Q(b,h);for(e=1+e|0;a.q();)c=a.h(),b=Q(b,M(P(),c)),e=1+e|0;a=R(b^e);break a}g=h;e=1+e|0}a=R(Q(Q(c,f),g))}else a=R(Q(b,M(P(),c))^1);else a=R(b^0);return a};
d.l=function(){return wb(this,this.wa()+"(",", ")};d.e=function(){return 0===this.ya(0)};d.hb=function(a){return ke(this,a)};function Gf(){}Gf.prototype=new Cf;Gf.prototype.constructor=Gf;function Hf(){}Hf.prototype=Gf.prototype;function If(){this.xb=null}If.prototype=new Hf;If.prototype.constructor=If;function Jf(){}Jf.prototype=If.prototype;If.prototype.o=function(a){return this.xb.o(a)};If.prototype.g=function(){return this.xb.g()};If.prototype.e=function(){return this.xb.e()};
function Kf(a){this.xb=a}Kf.prototype=new Jf;Kf.prototype.constructor=Kf;d=Kf.prototype;d.n=function(){return new Xe(this)};d.Oa=function(){return"IndexedSeqView"};d.ya=function(a){var b=this.g();return b===a?0:b<a?-1:1};d.x=function(){return this.g()};d.$classData=t({ie:0},!1,"scala.collection.IndexedSeqView$Id",{ie:1,bg:1,Uf:1,Vf:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,dg:1,c:1,ag:1,H:1,$f:1,P:1});function Lf(){}Lf.prototype=new Ef;Lf.prototype.constructor=Lf;function Mf(){}Mf.prototype=Lf.prototype;
function Nf(a,b){return b&&b.$classData&&b.$classData.N.ba?a.g()===b.g():!0}function Of(a,b){if(b&&b.$classData&&b.$classData.N.ba){if(a===b)return!0;var c=a.g(),e=c===b.g();if(e){var g=0,f=a.Nb(),h=b.Nb();f=f<h?f:h;h=c>>31;var l=f>>>31|0|f>>31<<1;for(f=(h===l?(-2147483648^c)>(-2147483648^f<<1):h>l)?f:c;g<f&&e;)e=x(y(),a.o(g),b.o(g)),g=1+g|0;if(g<c&&e)for(a=a.n().db(g),b=b.n().db(g);e&&a.q();)e=x(y(),a.h(),b.h())}return e}return ke(a,b)}function Pf(){}Pf.prototype=new Ef;
Pf.prototype.constructor=Pf;function Qf(){}Qf.prototype=Pf.prototype;var Sf=function Rf(a,b){Wb();return new oe(new Xd(((e,g)=>()=>{if(e.e())return Wd();Wb();var f=g.v(V(e).s()),h=Rf(V(e).w(),g);return new Rd(f,h)})(a,b)))};
function Tf(a,b,c,e,g){b.d=""+b.d+c;if(!a.ca)b.d+="\x3cnot computed\x3e";else if(!a.e()){c=V(a).s();b.d=""+b.d+c;c=a;var f=V(a).w();if(c!==f&&(!f.ca||V(c)!==V(f))&&(c=f,f.ca&&!f.e()))for(f=V(f).w();c!==f&&f.ca&&!f.e()&&V(c)!==V(f);){b.d=""+b.d+e;var h=V(c).s();b.d=""+b.d+h;c=V(c).w();f=V(f).w();f.ca&&!f.e()&&(f=V(f).w())}if(!f.ca||f.e()){for(;c!==f;)b.d=""+b.d+e,a=V(c).s(),b.d=""+b.d+a,c=V(c).w();c.ca||(b.d=""+b.d+e,b.d+="\x3cnot computed\x3e")}else{h=a;for(a=0;;){var l=h,v=f;if(l!==v&&V(l)!==V(v))h=
V(h).w(),f=V(f).w(),a=1+a|0;else break}h=c;l=f;(h===l||V(h)===V(l))&&0<a&&(b.d=""+b.d+e,a=V(c).s(),b.d=""+b.d+a,c=V(c).w());for(;;)if(a=c,h=f,a!==h&&V(a)!==V(h))b.d=""+b.d+e,a=V(c).s(),b.d=""+b.d+a,c=V(c).w();else break;b.d=""+b.d+e;b.d+="\x3ccycle\x3e"}}b.d=""+b.d+g;return b}function oe(a){this.Bc=null;this.Xb=!1;this.Ac=a;this.Yb=this.ca=!1}oe.prototype=new Mf;oe.prototype.constructor=oe;d=oe.prototype;d.Oa=function(){return"LinearSeq"};
d.g=function(){for(var a=this,b=0;!a.e();)b=1+b|0,a=a.y();return b};d.ya=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.e()?0:1;break a}if(b.e()){a=-1;break a}c=1+c|0;b=b.y()}return a};d.o=function(a){return Ae(this,a)};d.hb=function(a){return Be(this,a)};
function V(a){if(!a.Xb&&!a.Xb){if(a.Yb)throw a=new ce,K(a,"self-referential LazyList or a derivation thereof has no more elements"),Nc(a);a.Yb=!0;try{var b=(0,a.Ac.qf)()}finally{a.Yb=!1}a.ca=!0;a.Ac=null;a.Bc=b;a.Xb=!0}return a.Bc}d.e=function(){return V(this)===Wd()};d.x=function(){return this.ca&&this.e()?0:-1};d.s=function(){return V(this).s()};function ne(a){var b=a,c=a;for(b.e()||(b=V(b).w());c!==b&&!b.e();){b=V(b).w();if(b.e())break;b=V(b).w();if(b===c)break;c=V(c).w()}return a}
d.n=function(){return this.ca&&this.e()?J().la:new De(this)};d.wa=function(){return"LazyList"};d.ua=function(a,b,c,e){ne(this);Tf(this,a.fa,b,c,e);return a};d.l=function(){var a=new zb;yb(a);a.d="LazyList";return Tf(this,a,"(",", ",")").d};d.v=function(a){return Ae(this,a|0)};d.hc=function(a){return 0>=a?this:this.ca&&this.e()?Wb().Wb:pe(Wb(),this,a)};d.ub=function(a){return this.ca&&this.e()?Wb().Wb:Sf(this,a)};d.y=function(){return V(this).w()};
d.$classData=t({Le:0},!1,"scala.collection.immutable.LazyList",{Le:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,Cc:1,Tb:1,wc:1,Dc:1,c:1});function Uf(){}Uf.prototype=new Mf;Uf.prototype.constructor=Uf;function Z(){}d=Z.prototype=Uf.prototype;d.Ob=function(a){return Nf(this,a)};d.hb=function(a){return Of(this,a)};d.Oa=function(){return"IndexedSeq"};d.ya=function(a){var b=this.g();return b===a?0:b<a?-1:1};d.x=function(){return this.g()};d.wa=function(){return"ArraySeq"};
d.Nb=function(){return 2147483647};d.ub=function(a){for(var b=new q(this.g()),c=0;c<b.a.length;)b.a[c]=a.v(this.o(c)),c=1+c|0;return $e(Dc(),b)};function Vf(){this.Wa=null}Vf.prototype=new Mf;Vf.prototype.constructor=Vf;function Wf(){}d=Wf.prototype=Vf.prototype;d.Ob=function(a){return Nf(this,a)};d.hb=function(a){return Of(this,a)};d.Oa=function(){return"IndexedSeq"};d.ya=function(a){var b=this.g();return b===a?0:b<a?-1:1};d.x=function(){return this.g()};
d.g=function(){return this instanceof Xf?this.Vb:this.Wa.a.length};d.n=function(){return Ke()===this?Xb().Fc:new He(this,this.g(),0)};d.wa=function(){return"Vector"};d.Nb=function(){return Xb().Ec};function Yf(){}Yf.prototype=new Qf;Yf.prototype.constructor=Yf;function Zf(){}d=Zf.prototype=Yf.prototype;d.Oa=function(){return"IndexedSeq"};d.ya=function(a){var b=this.g();return b===a?0:b<a?-1:1};d.x=function(){return this.g()};d.wa=function(){return"ArraySeq"};
d.k=function(a){return a instanceof Yf&&Ac(B(),this.ea)!==Ac(B(),a.ea)?!1:Y(this,a)};function hf(a){this.Ba=a}hf.prototype=new Z;hf.prototype.constructor=hf;d=hf.prototype;d.g=function(){return this.Ba.a.length};
d.p=function(){var a=S();a:{var b=this.Ba;a=a.J;var c=b.a.length;switch(c){case 0:b=R(a^0);break a;case 1:b=R(Q(a,b.a[0]?1231:1237)^1);break a;default:var e=b.a[0]?1231:1237,g=a=Q(a,e),f=b.a[1]?1231:1237;e=f-e|0;for(var h=2;h<c;){a=Q(a,f);var l=b.a[h]?1231:1237;if(e!==(l-f|0)){a=Q(a,l);for(h=1+h|0;h<c;)a=Q(a,b.a[h]?1231:1237),h=1+h|0;b=R(a^c);break a}f=l;h=1+h|0}b=R(Q(Q(g,e),f))}}return b};d.k=function(a){if(a instanceof hf){var b=this.Ba;a=a.Ba;return ab(z(),b,a)}return Y(this,a)};d.n=function(){return new sf(this.Ba)};
d.v=function(a){return this.Ba.a[a|0]};d.o=function(a){return this.Ba.a[a]};d.$classData=t({ze:0},!1,"scala.collection.immutable.ArraySeq$ofBoolean",{ze:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function ff(a){this.Ca=a}ff.prototype=new Z;ff.prototype.constructor=ff;d=ff.prototype;d.g=function(){return this.Ca.a.length};
d.p=function(){var a=S();a:{var b=this.Ca;a=a.J;var c=b.a.length;switch(c){case 0:b=R(a^0);break a;case 1:b=R(Q(a,b.a[0])^1);break a;default:var e=b.a[0],g=a=Q(a,e),f=b.a[1];e=f-e|0;for(var h=2;h<c;){a=Q(a,f);var l=b.a[h];if(e!==(l-f|0)){a=Q(a,l);for(h=1+h|0;h<c;)a=Q(a,b.a[h]),h=1+h|0;b=R(a^c);break a}f=l;h=1+h|0}b=R(Q(Q(g,e),f))}}return b};d.k=function(a){if(a instanceof ff){var b=this.Ca;a=a.Ca;return $a(z(),b,a)}return Y(this,a)};d.n=function(){return new kf(this.Ca)};
d.v=function(a){return this.Ca.a[a|0]};d.o=function(a){return this.Ca.a[a]};d.$classData=t({Ae:0},!1,"scala.collection.immutable.ArraySeq$ofByte",{Ae:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function ef(a){this.Da=a}ef.prototype=new Z;ef.prototype.constructor=ef;d=ef.prototype;d.g=function(){return this.Da.a.length};d.bb=function(a){return this.Da.a[a]};d.p=function(){var a=S();return Uc(this.Da,a.J)};
d.k=function(a){if(a instanceof ef){var b=this.Da;a=a.Da;return Za(z(),b,a)}return Y(this,a)};d.n=function(){return new lf(this.Da)};d.ua=function(a,b,c,e){return(new $f(this.Da)).ua(a,b,c,e)};d.v=function(a){return n(this.bb(a|0))};d.o=function(a){return n(this.bb(a))};d.$classData=t({Be:0},!1,"scala.collection.immutable.ArraySeq$ofChar",{Be:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function bf(a){this.Ea=a}bf.prototype=new Z;
bf.prototype.constructor=bf;d=bf.prototype;d.g=function(){return this.Ea.a.length};d.p=function(){var a=S();a:{var b=this.Ea;a=a.J;var c=b.a.length;switch(c){case 0:b=R(a^0);break a;case 1:b=b.a[0];b=R(Q(a,L(P(),b))^1);break a;default:var e=b.a[0],g=L(P(),e);e=a=Q(a,g);var f=b.a[1];f=L(P(),f);var h=f-g|0;for(g=2;g<c;){a=Q(a,f);var l=b.a[g];l=L(P(),l);if(h!==(l-f|0)){a=Q(a,l);for(g=1+g|0;g<c;)e=b.a[g],a=Q(a,L(P(),e)),g=1+g|0;b=R(a^c);break a}f=l;g=1+g|0}b=R(Q(Q(e,h),f))}}return b};
d.k=function(a){if(a instanceof bf){var b=this.Ea;a=a.Ea;return bb(z(),b,a)}return Y(this,a)};d.n=function(){return new mf(this.Ea)};d.v=function(a){return this.Ea.a[a|0]};d.o=function(a){return this.Ea.a[a]};d.$classData=t({Ce:0},!1,"scala.collection.immutable.ArraySeq$ofDouble",{Ce:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function df(a){this.Fa=a}df.prototype=new Z;df.prototype.constructor=df;d=df.prototype;d.g=function(){return this.Fa.a.length};
d.p=function(){var a=S();a:{var b=this.Fa;var c=a.J;a=b.a.length;switch(a){case 0:b=R(c^0);break a;case 1:a=c;b=b.a[0];P();b=R(Q(a,L(0,b))^1);break a;default:var e=b.a[0],g=L(P(),e);e=c=Q(c,g);var f=b.a[1];f=L(P(),f);var h=f-g|0;for(g=2;g<a;){c=Q(c,f);var l=b.a[g];l=L(P(),l);if(h!==(l-f|0)){c=Q(c,l);for(g=1+g|0;g<a;)e=b.a[g],P(),c=Q(c,L(0,e)),g=1+g|0;b=R(c^a);break a}f=l;g=1+g|0}b=R(Q(Q(e,h),f))}}return b};d.k=function(a){if(a instanceof df){var b=this.Fa;a=a.Fa;return cb(z(),b,a)}return Y(this,a)};
d.n=function(){return new nf(this.Fa)};d.v=function(a){return this.Fa.a[a|0]};d.o=function(a){return this.Fa.a[a]};d.$classData=t({De:0},!1,"scala.collection.immutable.ArraySeq$ofFloat",{De:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function af(a){this.Ga=a}af.prototype=new Z;af.prototype.constructor=af;d=af.prototype;d.g=function(){return this.Ga.a.length};
d.p=function(){var a=S();a:{var b=this.Ga;a=a.J;var c=b.a.length;switch(c){case 0:b=R(a^0);break a;case 1:b=R(Q(a,b.a[0])^1);break a;default:var e=b.a[0],g=a=Q(a,e),f=b.a[1];e=f-e|0;for(var h=2;h<c;){a=Q(a,f);var l=b.a[h];if(e!==(l-f|0)){a=Q(a,l);for(h=1+h|0;h<c;)a=Q(a,b.a[h]),h=1+h|0;b=R(a^c);break a}f=l;h=1+h|0}b=R(Q(Q(g,e),f))}}return b};d.k=function(a){if(a instanceof af){var b=this.Ga;a=a.Ga;return Xa(z(),b,a)}return Y(this,a)};d.n=function(){return new of(this.Ga)};
d.v=function(a){return this.Ga.a[a|0]};d.o=function(a){return this.Ga.a[a]};d.$classData=t({Ee:0},!1,"scala.collection.immutable.ArraySeq$ofInt",{Ee:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function cf(a){this.Ha=a}cf.prototype=new Z;cf.prototype.constructor=cf;d=cf.prototype;d.g=function(){return this.Ha.a.length};
d.p=function(){var a=S();a:{var b=this.Ha;a=a.J;var c=b.a.length;switch(c){case 0:a=R(a^0);break a;case 1:c=b.a[0];b=c.u;c=c.t;a=R(Q(a,Jc(P(),new k(b,c)))^1);break a;default:var e=b.a[0],g=e.u;e=e.t;e=Jc(P(),new k(g,e));g=a=Q(a,e);var f=b.a[1],h=f.u;f=f.t;h=Jc(P(),new k(h,f));f=h-e|0;for(e=2;e<c;){a=Q(a,h);var l=b.a[e],v=l.u;l=l.t;v=Jc(P(),new k(v,l));if(f!==(v-h|0)){a=Q(a,v);for(e=1+e|0;e<c;)h=b.a[e],g=h.u,h=h.t,a=Q(a,Jc(P(),new k(g,h))),e=1+e|0;a=R(a^c);break a}h=v;e=1+e|0}a=R(Q(Q(g,f),h))}}return a};
d.k=function(a){if(a instanceof cf){var b=this.Ha;a=a.Ha;return Wa(z(),b,a)}return Y(this,a)};d.n=function(){return new pf(this.Ha)};d.v=function(a){return this.Ha.a[a|0]};d.o=function(a){return this.Ha.a[a]};d.$classData=t({Fe:0},!1,"scala.collection.immutable.ArraySeq$ofLong",{Fe:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function Gc(a){this.Ta=a}Gc.prototype=new Z;Gc.prototype.constructor=Gc;d=Gc.prototype;d.g=function(){return this.Ta.a.length};
d.o=function(a){return this.Ta.a[a]};d.p=function(){var a=S();a:{var b=this.Ta;var c=a.J;a=Ac(B(),b);switch(a){case 0:b=R(c^0);break a;case 1:a=c;b=xc(B(),b,0);b=R(Q(a,M(P(),b))^1);break a;default:var e=xc(B(),b,0),g=M(P(),e);e=c=Q(c,g);var f=xc(B(),b,1);f=M(P(),f);var h=f-g|0;for(g=2;g<a;){c=Q(c,f);var l=xc(B(),b,g);l=M(P(),l);if(h!==(l-f|0)){c=Q(c,l);for(g=1+g|0;g<a;)e=xc(B(),b,g),c=Q(c,M(P(),e)),g=1+g|0;b=R(c^a);break a}f=l;g=1+g|0}b=R(Q(Q(e,h),f))}}return b};
d.k=function(a){if(a instanceof Gc){ud||(ud=new qd);a:{var b=this.Ta;a=a.Ta;if(b===a)b=!0;else if(b.a.length!==a.a.length)b=!1;else{for(var c=b.a.length,e=0;e<c;){if(!x(y(),b.a[e],a.a[e])){b=!1;break a}e=1+e|0}b=!0}}}else b=Y(this,a);return b};d.n=function(){return Ue(new Ve,this.Ta)};d.v=function(a){return this.o(a|0)};
d.$classData=t({Ge:0},!1,"scala.collection.immutable.ArraySeq$ofRef",{Ge:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function gf(a){this.Ia=a}gf.prototype=new Z;gf.prototype.constructor=gf;d=gf.prototype;d.g=function(){return this.Ia.a.length};
d.p=function(){var a=S();a:{var b=this.Ia;a=a.J;var c=b.a.length;switch(c){case 0:b=R(a^0);break a;case 1:b=R(Q(a,b.a[0])^1);break a;default:var e=b.a[0],g=a=Q(a,e),f=b.a[1];e=f-e|0;for(var h=2;h<c;){a=Q(a,f);var l=b.a[h];if(e!==(l-f|0)){a=Q(a,l);for(h=1+h|0;h<c;)a=Q(a,b.a[h]),h=1+h|0;b=R(a^c);break a}f=l;h=1+h|0}b=R(Q(Q(g,e),f))}}return b};d.k=function(a){if(a instanceof gf){var b=this.Ia;a=a.Ia;return Ya(z(),b,a)}return Y(this,a)};d.n=function(){return new qf(this.Ia)};
d.v=function(a){return this.Ia.a[a|0]};d.o=function(a){return this.Ia.a[a]};d.$classData=t({He:0},!1,"scala.collection.immutable.ArraySeq$ofShort",{He:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function jf(a){this.jb=a}jf.prototype=new Z;jf.prototype.constructor=jf;d=jf.prototype;d.g=function(){return this.jb.a.length};
d.p=function(){a:{var a=S().J;var b=this.jb.a.length;switch(b){case 0:a=R(a^0);break a;case 1:a=R(Q(a,0)^1);break a;default:for(var c=a=Q(a,0),e=0,g=e,f=2;f<b;){a=Q(a,e);if(g!==(-e|0)){a=Q(a,0);for(f=1+f|0;f<b;)a=Q(a,0),f=1+f|0;a=R(a^b);break a}e=0;f=1+f|0}a=R(Q(Q(c,g),e))}}return a};d.k=function(a){return a instanceof jf?this.jb.a.length===a.jb.a.length:Y(this,a)};d.n=function(){return new rf(this.jb)};d.v=function(){};d.o=function(){};
d.$classData=t({Ie:0},!1,"scala.collection.immutable.ArraySeq$ofUnit",{Ie:1,ra:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,pa:1,c:1});function Ff(){}Ff.prototype=new Mf;Ff.prototype.constructor=Ff;function ag(){}d=ag.prototype=Ff.prototype;d.n=function(){return new Ce(this)};d.Oa=function(){return"LinearSeq"};d.o=function(a){return Ae(this,a)};d.hb=function(a){return Be(this,a)};d.e=function(){return this===H()};
function G(a,b){if(b instanceof Ff){if(a.e())a=b;else if(!b.e()){var c=new bg(b.s(),a),e=c;for(b=b.y();!b.e();){var g=new bg(b.s(),a);e=e.ib=g;b=b.y()}a=c}return a}if(0===b.x())return a;c=b.n();if(c.q()){for(b=e=new bg(c.h(),a);c.q();)g=new bg(c.h(),a),b=b.ib=g;return e}return a}d.g=function(){for(var a=this,b=0;!a.e();)b=1+b|0,a=a.y();return b};d.ya=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.e()?0:1;break a}if(b.e()){a=-1;break a}c=1+c|0;b=b.y()}return a};d.wa=function(){return"List"};
d.Xa=function(){return this};d.k=function(a){var b;if(a instanceof Ff)a:for(b=this;;){if(b===a){b=!0;break a}var c=b.e(),e=a.e();if(c||e||!x(y(),b.s(),a.s())){b=c&&e;break a}b=b.y();a=a.y()}else b=Y(this,a);return b};d.v=function(a){return Ae(this,a|0)};d.hc=function(a){a:for(var b=this;;){if(0>=a||b.e())break a;a=-1+a|0;b=b.y()}return b};d.ub=function(a){if(this===H())a=H();else{for(var b=new bg(a.v(this.s()),H()),c=b,e=this.y();e!==H();){var g=new bg(a.v(e.s()),H());c=c.ib=g;e=e.y()}a=b}return a};
function cg(){this.Wa=null}cg.prototype=new Wf;cg.prototype.constructor=cg;function dg(){}dg.prototype=cg.prototype;function $f(a){this.ea=a}$f.prototype=new Zf;$f.prototype.constructor=$f;d=$f.prototype;d.g=function(){return this.ea.a.length};d.bb=function(a){return this.ea.a[a]};d.p=function(){var a=S();return Uc(this.ea,a.J)};d.k=function(a){if(a instanceof $f){var b=this.ea;a=a.ea;return Za(z(),b,a)}return Yf.prototype.k.call(this,a)};d.n=function(){return new lf(this.ea)};
d.ua=function(a,b,c,e){var g=a.fa;0!==(b.length|0)&&(g.d=""+g.d+b);b=this.ea.a.length;if(0!==b)if(""===c){c=this.ea;od||(od=new nd);b=0+c.a.length|0;if(0>b||b>c.a.length)throw new Pe;for(var f="",h=0;h!==b;)f=""+f+String.fromCharCode(c.a[h]),h=1+h|0;g.d=""+g.d+f}else for(g.g(),e.length|0,c.length|0,f=String.fromCharCode(this.ea.a[0]),g.d=""+g.d+f,f=1;f<b;)g.d=""+g.d+c,h=String.fromCharCode(this.ea.a[f]),g.d=""+g.d+h,f=1+f|0;0!==(e.length|0)&&(g.d=""+g.d+e);return a};
d.v=function(a){return n(this.bb(a|0))};d.o=function(a){return n(this.bb(a))};d.$classData=t({ef:0},!1,"scala.collection.mutable.ArraySeq$ofChar",{ef:1,hg:1,df:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,kf:1,jf:1,lf:1,ff:1,sb:1,gf:1,O:1,P:1,hf:1,S:1,R:1,c:1});function Xf(){this.Wa=null;this.Vb=0}Xf.prototype=new dg;Xf.prototype.constructor=Xf;function eg(){}eg.prototype=Xf.prototype;function bg(a,b){this.yc=a;this.ib=b}bg.prototype=new ag;bg.prototype.constructor=bg;d=bg.prototype;
d.s=function(){return this.yc};d.$=function(){return"::"};d.Y=function(){return 2};d.Z=function(a){switch(a){case 0:return this.yc;case 1:return this.ib;default:return Kc(P(),a)}};d.ia=function(){return new X(this)};d.y=function(){return this.ib};d.$classData=t({we:0},!1,"scala.collection.immutable.$colon$colon",{we:1,Te:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,Cc:1,Tb:1,wc:1,Dc:1,re:1,S:1,R:1,da:1,xc:1,c:1,ja:1});function fg(){hg=this;H();H()}fg.prototype=new ag;
fg.prototype.constructor=fg;d=fg.prototype;d.Pb=function(){throw new Td("head of empty list");};d.x=function(){return 0};d.n=function(){return J().la};d.$=function(){return"Nil"};d.Y=function(){return 0};d.Z=function(a){return Kc(P(),a)};d.ia=function(){return new X(this)};d.y=function(){throw new Ud("tail of empty list");};d.s=function(){this.Pb()};
d.$classData=t({Xe:0},!1,"scala.collection.immutable.Nil$",{Xe:1,Te:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,Cc:1,Tb:1,wc:1,Dc:1,re:1,S:1,R:1,da:1,xc:1,c:1,ja:1});var hg;function H(){hg||(hg=new fg);return hg}function ig(){this.Wa=null;this.Vb=0;var a=Db().Gc;Db();this.Vb=0;this.Wa=a}ig.prototype=new eg;ig.prototype.constructor=ig;d=ig.prototype;d.k=function(a){return this===a||!(a instanceof Vf)&&Y(this,a)};
function jg(a){return N(new O,a+" is out of bounds (empty vector)")}d.ub=function(){return this};d.v=function(a){throw jg(a|0);};d.o=function(a){throw jg(a);};d.$classData=t({bf:0},!1,"scala.collection.immutable.Vector0$",{bf:1,eg:1,gg:1,fg:1,T:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,W:1,U:1,X:1,ba:1,O:1,P:1,ma:1,da:1,S:1,R:1,xc:1,c:1});var kg;function Ke(){kg||(kg=new ig);return kg}function xb(){this.fa=null}xb.prototype=new Qf;xb.prototype.constructor=xb;d=xb.prototype;d.Oa=function(){return"IndexedSeq"};
d.n=function(){var a=new Kf(this);return new Xe(a)};d.ya=function(a){var b=this.fa.g();return b===a?0:b<a?-1:1};d.g=function(){return this.fa.g()};d.x=function(){return this.fa.g()};d.l=function(){return this.fa.d};d.e=function(){return 0===this.fa.g()};d.v=function(a){return n(65535&(this.fa.d.charCodeAt(a|0)|0))};d.o=function(a){return n(65535&(this.fa.d.charCodeAt(a)|0))};
d.$classData=t({mf:0},!1,"scala.collection.mutable.StringBuilder",{mf:1,df:1,K:1,B:1,b:1,D:1,i:1,F:1,j:1,E:1,G:1,I:1,A:1,H:1,r:1,kf:1,jf:1,lf:1,ff:1,sb:1,lg:1,ig:1,kg:1,jg:1,gf:1,O:1,P:1,hf:1,ed:1,c:1});ba=new k(0,0);Ha.Ic=ba;var Gd=null;mdoc_js_run2=function(){qb();A();B();A();var a=C(0,new (w(jb).m)([mb("This is some text.")]));E();F();G(H(),a)};mdoc_js_run4=function(){qb();lb(A().Ya,"my-container")};
mdoc_js_run8=function(){qb();A();var a=C(B(),new (w(kb).m)([lb(A().Ya,"an-id")]));E();F();G(H(),a);E();a=C(B(),new (w(Le).m)([lb(A().Ya,"an-id")]));G(H(),a);E();A();hb();A();ae||(ae=new $d);A();hb();gb("width","100px");Oe();A()};mdoc_js_run6=function(){qb()};mdoc_js_run3=function(){qb();A();mb("some text");A();var a=C(B(),new (w(jb).m)([(A(),new D("some text"))]));E();F();G(H(),a)};
mdoc_js_run1=function(){qb();A();var a=C(B(),new (w(kb).m)([lb(A().fc,"green-box")]));B();A();var b=C(0,new (w(jb).m)([mb("This is some text.")]));F();G(H(),a);F();G(H(),b)};mdoc_js_run5=function(){qb();A();B();A();var a=gb("font-weight","bold");hb();C(0,new (w(kb).m)([new ib("style",a)])).Xa();E();a=C(B(),new (w(pb).m)([(A(),new D("Hello"))]));G(H(),a)};mdoc_js_run7=function(){qb()};
}).call(this);
