let mdoc_js_run2,mdoc_js_run4,mdoc_js_run8,mdoc_js_run6,mdoc_js_run3,mdoc_js_run1,mdoc_js_run5,mdoc_js_run7;
(function(){
'use strict';var d,aa=Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.11.0",fileLevelThis:this}),ba;function ca(a){for(var b in a)return b}function k(a){this.Kb=a}k.prototype.toString=function(){return String.fromCharCode(this.Kb)};
function da(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"number"!==typeof a||a===a&&Math.fround(a)!==a?"java.lang.Double":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.Pe():a instanceof l?"java.lang.Long":a instanceof k?"java.lang.Character":a&&a.$classData?a.$classData.name:
null.Qe()}}function ea(a){switch(typeof a){case "string":return fa(a);case "number":return ha(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.m():a instanceof l?a.W^a.V:a instanceof k?null===a?0:a.Kb:m.prototype.m.call(a)}}var ia=0,ja=new WeakMap;
function ka(a){switch(typeof a){case "string":return fa(a);case "number":return ha(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:fa(a);default:if(null===a)return 0;b=ja.get(a);void 0===b&&(ia=b=ia+1|0,ja.set(a,b));return b}}function m(){}m.prototype.constructor=m;function p(){}p.prototype=m.prototype;m.prototype.m=function(){return ka(this)};
m.prototype.n=function(){var a=this.m();return da(this)+"@"+(+(a>>>0)).toString(16)};m.prototype.toString=function(){return this.n()};function q(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=null}else this.a=a}q.prototype=new p;q.prototype.constructor=q;function la(){}la.prototype=q.prototype;function ma(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=!1}else this.a=a}ma.prototype=new p;ma.prototype.constructor=ma;
function na(a){this.a="number"===typeof a?new Uint16Array(a):a}na.prototype=new p;na.prototype.constructor=na;function oa(a){this.a="number"===typeof a?new Int8Array(a):a}oa.prototype=new p;oa.prototype.constructor=oa;function pa(a){this.a="number"===typeof a?new Int16Array(a):a}pa.prototype=new p;pa.prototype.constructor=pa;function qa(a){this.a="number"===typeof a?new Int32Array(a):a}qa.prototype=new p;qa.prototype.constructor=qa;
function ra(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=ba}else this.a=a}ra.prototype=new p;ra.prototype.constructor=ra;function sa(a){this.a="number"===typeof a?new Float32Array(a):a}sa.prototype=new p;sa.prototype.constructor=sa;function ta(a){this.a="number"===typeof a?new Float64Array(a):a}ta.prototype=new p;ta.prototype.constructor=ta;
function ua(){this.k=void 0;this.ta=this.da=null;this.ua=0;this.lc=null;this.pa="";this.va=this.Da=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function r(a,b,c,e){var h=new ua;h.da={};h.lc=a;h.pa=b;h.va=f=>f===h;h.name=c;h.isPrimitive=!0;h.isInstance=()=>!1;void 0!==e&&(h.Da=va(h,e));return h}
function t(a,b,c,e){var h=new ua,f=ca(a);h.da=e;h.pa="L"+c+";";h.va=g=>!!g.da[f];h.name=c;h.isInterface=b;h.isInstance=g=>!!(g&&g.$classData&&g.$classData.da[f]);return h}function va(a,b,c){var e=new ua;b.prototype.$classData=e;var h="["+a.pa;e.k=b;e.da={b:1,$a:1,c:1};e.ta=a;e.ua=1;e.pa=h;e.name=h;e.isArrayClass=!0;e.va=c||(f=>e===f);e.isInstance=f=>f instanceof b;return e}
function wa(a){function b(g){if("number"===typeof g){this.a=Array(g);for(var n=0;n<g;n++)this.a[n]=null}else this.a=g}var c=new ua;b.prototype=new la;b.prototype.constructor=b;var e=a.ta||a,h=a.ua+1;b.prototype.$classData=c;a="["+a.pa;c.k=b;c.da={b:1,$a:1,c:1};c.ta=e;c.ua=h;c.pa=a;c.name=a;c.isArrayClass=!0;var f=g=>{var n=g.ua;return n===h?e.va(g.ta):n>h&&e===u};c.va=f;c.isInstance=g=>{g=g&&g.$classData;return!!g&&(g===c||f(g))};return c}function v(a){a.Da||(a.Da=wa(a));return a.Da}var u=new ua;
u.da={b:1};u.pa="Ljava.lang.Object;";u.va=a=>!a.isPrimitive;u.name="java.lang.Object";u.isInstance=a=>null!==a;u.Da=va(u,q,a=>{var b=a.ua;return 1===b?!a.ta.isPrimitive:1<b});m.prototype.$classData=u;r(void 0,"V","void",void 0);r(!1,"Z","boolean",ma);r(0,"C","char",na);r(0,"B","byte",oa);r(0,"S","short",pa);r(0,"I","int",qa);var xa=r(null,"J","long",ra);r(0,"F","float",sa);r(0,"D","double",ta);
function ya(){this.Nb=this.ab=this.Fa=null;za=this;this.Fa=new ArrayBuffer(8);this.ab=new Int32Array(this.Fa,0,2);new Float32Array(this.Fa,0,2);this.Nb=new Float64Array(this.Fa,0,1);this.ab[0]=16909060;new Int8Array(this.Fa,0,8)}ya.prototype=new p;ya.prototype.constructor=ya;function Aa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.Nb[0]=b;return(a.ab[0]|0)^(a.ab[1]|0)}ya.prototype.$classData=t({Sc:0},!1,"java.lang.FloatingPointBits$",{Sc:1,b:1});var za;
function Ba(){za||(za=new ya);return za}
function Ca(){this.Qb=this.qb=null;Da=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.qb=a;this.Qb=null}Ca.prototype=new p;Ca.prototype.constructor=Ca;function Ea(a,b,c){return null!==a.qb?(a=a.qb,Fa||(Fa=new Ga),Fa.Sb.call(a,b)?a[b]:c):Ea(a.Qb,b,c)}Ca.prototype.$classData=t({Zc:0},!1,"java.lang.System$SystemProperties$",{Zc:1,b:1});var Da;function Ga(){this.Sb=null;Fa=this;this.Sb=Object.prototype.hasOwnProperty}Ga.prototype=new p;Ga.prototype.constructor=Ga;Ga.prototype.$classData=t({ad:0},!1,"java.lang.Utils$Cache$",{ad:1,b:1});var Fa;function Ha(){}Ha.prototype=new p;
Ha.prototype.constructor=Ha;function Ia(a,b){if(b instanceof q||b instanceof ma||b instanceof na||b instanceof oa||b instanceof pa||b instanceof qa||b instanceof ra||b instanceof sa||b instanceof ta)return b.a.length;a=new Ja;w(a,"argument type mismatch");throw a;}Ha.prototype.$classData=t({bd:0},!1,"java.lang.reflect.Array$",{bd:1,b:1});var Ka;function La(){Ka||(Ka=new Ha);return Ka}function Ma(){}Ma.prototype=new p;Ma.prototype.constructor=Ma;
Ma.prototype.$classData=t({cd:0},!1,"java.util.Arrays$",{cd:1,b:1});var Oa;
function Pa(){this.Ib=this.Hb=null;Qa=this;x();var a=Ra("font-family","Arial, Helvetica, sans-serif");Sa();this.Hb=new Ta("style",a);x();z();x();var b=A(z(),new (v(Ua).k)([(x(),new B("This is some HTML in bold."))]));a=C().Ha;D();b=E(F(),b);b=A(0,new (v(Ua).k)([new G("b",a,b)]));a=C().Ha;D();b=E(F(),b);this.Ib=new G("p",a,b);x();a=A(z(),new (v(Va).k)([Wa(x().Ca,"my-container")]));z();x();b=A(z(),new (v(Va).k)([this.Hb]));z();var c=this.Ib;x();var e=Xa("Hello, world!");x();z();x();var h=Ya(),f=A(0,
new (v(Va).k)([Za(h)]));h=v(Ua).k;f=f.Ba();C();var g=A(z(),new (v($a).k)([(x(),new B("Say hello!"))]));g=E(F(),g);c=A(0,new h([c,e,new G("button",f,g)]));D();b=E(F(),b);D();c=E(F(),c);b=A(0,new (v(Ua).k)([new G("div",b,c)]));D();E(F(),a);D();E(F(),b)}Pa.prototype=new p;Pa.prototype.constructor=Pa;Pa.prototype.$classData=t({mc:0},!1,"mdocjs$",{mc:1,b:1});var Qa;function ab(){Qa||(Qa=new Pa)}function l(a,b){this.W=a;this.V=b}l.prototype=new p;l.prototype.constructor=l;
l.prototype.m=function(){return this.W^this.V};l.prototype.n=function(){bb();var a=this.W,b=this.V;return b===a>>31?""+a:0>b?"-"+cb(-a|0,0!==a?~b:-b|0):cb(a,b)};l.prototype.$classData=t({Nc:0},!1,"org.scalajs.linker.runtime.RuntimeLong",{Nc:1,b:1});
function cb(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+Math.clz32(1E9)|0)-(0!==b?Math.clz32(b):32+Math.clz32(a)|0)|0,e=c,h=0===(32&e)?1E9<<e:0;e=0===(32&e)?5E8>>>(31-e|0)|0|0<<e:1E9<<e;var f=a,g=b;for(a=b=0;0<=c&&0!==(-2097152&g);){var n=f,y=g,X=h,Na=e;if(y===Na?(-2147483648^n)>=(-2147483648^X):(-2147483648^y)>=(-2147483648^Na))n=g,y=e,g=f-h|0,n=(-2147483648^g)>(-2147483648^f)?-1+(n-y|0)|0:n-y|0,f=g,g=n,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;n=e>>>1|0;h=h>>>1|0|e<<31;e=n}c=g;if(0===
c?-1147483648<=(-2147483648^f):-2147483648<=(-2147483648^c))c=4294967296*g+ +(f>>>0),f=c/1E9,h=f/4294967296|0,e=b,b=f=e+(f|0)|0,a=(-2147483648^f)<(-2147483648^e)?1+(a+h|0)|0:a+h|0,f=c%1E9|0;c=""+f;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length)+c}return b}function db(){this.Ya=0}db.prototype=new p;db.prototype.constructor=db;db.prototype.$classData=t({Oc:0},!1,"org.scalajs.linker.runtime.RuntimeLong$",{Oc:1,b:1});var eb;function bb(){eb||(eb=new db);return eb}
function fb(a,b,c){if(a.f())a=""+b+")";else{var e=a.oa,h=new gb;h.U=hb(new ib);a=e.call(a,h,b,c,")").U.d}return a}function jb(a,b,c,e,h){var f=b.U;0!==c.length&&(f.d=""+f.d+c);a=a.p();if(a.t())for(c=a.j(),f.d=""+f.d+c;a.t();)f.d=""+f.d+e,c=a.j(),f.d=""+f.d+c;0!==h.length&&(f.d=""+f.d+h);return b}function kb(){this.jc=null;lb=this;this.jc=new q(0);new (v(v(u)).k)(0);new (v(v(v(u))).k)(0);new (v(v(v(v(u)))).k)(0);new (v(v(v(v(v(u))))).k)(0);new (v(v(v(v(v(v(u)))))).k)(0)}kb.prototype=new p;
kb.prototype.constructor=kb;kb.prototype.$classData=t({re:0},!1,"scala.collection.immutable.VectorStatics$",{re:1,b:1});var lb;function mb(){lb||(lb=new kb);return lb}function nb(){this.Ha=null;ob=this;pb||(pb=new qb);pb||(pb=new qb);rb||(rb=new sb);tb||(tb=new ub);vb();D();this.Ha=F();wb();xb()}nb.prototype=new p;nb.prototype.constructor=nb;nb.prototype.$classData=t({hd:0},!1,"scala.package$",{hd:1,b:1});var ob;function C(){ob||(ob=new nb);return ob}function yb(){}yb.prototype=new p;
yb.prototype.constructor=yb;function zb(a,b,c){if(b instanceof q||b instanceof qa||b instanceof ta||b instanceof ra||b instanceof sa)return b.a[c];if(b instanceof na)return new k(b.a[c]);if(b instanceof oa||b instanceof pa||b instanceof ma)return b.a[c];if(null===b)throw new H;throw new Ab(b);}function Bb(a){z();var b=a.ja();return fb(b,a.$()+"(",",")}function A(a,b){return null===b?null:0===b.a.length?(a=Cb(),Db||(Db=new Eb),a.ub||a.ub||(a.cc=new Fb(new q(0)),a.ub=!0),a.cc):new Fb(b)}
yb.prototype.$classData=t({He:0},!1,"scala.runtime.ScalaRunTime$",{He:1,b:1});var Gb;function z(){Gb||(Gb=new yb);return Gb}function Hb(){}Hb.prototype=new p;Hb.prototype.constructor=Hb;function Ib(a,b){a=b.W;b=b.V;return b===a>>31?a:a^b}
function I(a,b){a=2147483647<b?2147483647:-2147483648>b?-2147483648:b|0;if(a===b)return a;a=bb();if(-0x7fffffffffffffff>b){a.Ya=-2147483648;var c=0}else if(0x7fffffffffffffff<=b)a.Ya=2147483647,c=-1;else{c=b|0;var e=b/4294967296|0;a.Ya=0>b&&0!==c?-1+e|0:e}a=a.Ya;bb();return(0>a?-(4294967296*+((0!==c?~a:-a|0)>>>0)+ +((-c|0)>>>0)):4294967296*a+ +(c>>>0))===b?c^a:Aa(Ba(),b)}function J(a,b){return null===b?0:"number"===typeof b?I(0,+b):b instanceof l?(a=null===b?ba:b,Ib(0,new l(a.W,a.V))):ea(b)}
Hb.prototype.$classData=t({Ke:0},!1,"scala.runtime.Statics$",{Ke:1,b:1});var Jb;function K(){Jb||(Jb=new Hb);return Jb}function Kb(){}Kb.prototype=new p;Kb.prototype.constructor=Kb;function Lb(){}Lb.prototype=Kb.prototype;function L(a,b){a=Mb(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function Mb(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}function M(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}
function Nb(a){N();var b=a.Y();if(0===b)return fa(a.$());var c=L(-889275714,fa(a.$()));for(var e=0;e<b;){var h=a.Z(e);c=L(c,J(K(),h));e=1+e|0}return M(c^b)}function Ob(a,b){var c=a.a.length;switch(c){case 0:return M(b^0);case 1:return M(L(b,a.a[0])^1);default:var e=a.a[0],h=b=L(b,e),f=a.a[1];e=f-e|0;for(var g=2;g<c;){b=L(b,f);var n=a.a[g];if(e!==(n-f|0)){b=L(b,n);for(g=1+g|0;g<c;)b=L(b,a.a[g]),g=1+g|0;return M(b^c)}f=n;g=1+g|0}return M(L(L(h,e),f))}}
var Va=t({kb:0},!0,"tyrian.Attr",{kb:1,b:1}),Ua=t({lb:0},!0,"tyrian.Elem",{lb:1,b:1});function Za(a){return new Pb("click",new Qb(()=>a))}function O(a){if(null===a)throw new H;}O.prototype=new p;O.prototype.constructor=O;O.prototype.$classData=t({xc:0},!1,"tyrian.HtmlAttributes$AttributeNameBoolean",{xc:1,b:1});function Rb(a){if(null===a)throw new H;}Rb.prototype=new p;Rb.prototype.constructor=Rb;Rb.prototype.$classData=t({yc:0},!1,"tyrian.HtmlAttributes$AttributeNameDouble",{yc:1,b:1});
function P(a){if(null===a)throw new H;}P.prototype=new p;P.prototype.constructor=P;P.prototype.$classData=t({zc:0},!1,"tyrian.HtmlAttributes$AttributeNameInt",{zc:1,b:1});function Q(a,b){this.Bc=b;if(null===a)throw new H;}Q.prototype=new p;Q.prototype.constructor=Q;function Wa(a,b){Sa();return new Ta(a.Bc,b)}Q.prototype.$classData=t({Ac:0},!1,"tyrian.HtmlAttributes$AttributeNameString",{Ac:1,b:1});function Sb(a){if(null===a)throw new H;}Sb.prototype=new p;Sb.prototype.constructor=Sb;
Sb.prototype.$classData=t({Cc:0},!1,"tyrian.HtmlAttributes$PropertyNameBoolean",{Cc:1,b:1});function Tb(a){if(null===a)throw new H;}Tb.prototype=new p;Tb.prototype.constructor=Tb;Tb.prototype.$classData=t({Dc:0},!1,"tyrian.HtmlAttributes$PropertyNameDouble",{Dc:1,b:1});function Ub(a){if(null===a)throw new H;}Ub.prototype=new p;Ub.prototype.constructor=Ub;Ub.prototype.$classData=t({Ec:0},!1,"tyrian.HtmlAttributes$PropertyNameString",{Ec:1,b:1});
function Xa(a){var b=C().Ha;C();a=A(z(),new (v($a).k)([(x(),new B(a))]));a=E(F(),a);return new G("p",b,a)}function Vb(){Wb=this;Ra("","")}Vb.prototype=new p;Vb.prototype.constructor=Vb;function Ra(a,b){Xb();return""===a?""===b?"":Yb(b)?b:b+";":""===b?Yb(a)?a:a+";":a+":"+b+";"}function Zb(a,b){Xb();for(a=b;!a.f();)a.q(),a=a.G()}Vb.prototype.$classData=t({Gc:0},!1,"tyrian.Style$package$Style$",{Gc:1,b:1});var Wb;function Xb(){Wb||(Wb=new Vb);return Wb}
function $b(a){0===(32&a.Za)<<24>>24&&0===(32&a.Za)<<24>>24&&(a.Mb=new qa(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.Za=(32|a.Za)<<24>>24);return a.Mb}function ac(){this.Mb=null;this.Za=0}ac.prototype=new p;ac.prototype.constructor=ac;
ac.prototype.$classData=t({Rc:0},!1,"java.lang.Character$",{Rc:1,b:1,c:1});var bc;function cc(a){throw new dc('For input string: "'+a+'"');}function ec(){}ec.prototype=new p;ec.prototype.constructor=ec;ec.prototype.$classData=t({Tc:0},!1,"java.lang.Integer$",{Tc:1,b:1,c:1});var fc;function gc(){}gc.prototype=new p;gc.prototype.constructor=gc;gc.prototype.$classData=t({Wc:0},!1,"java.lang.String$",{Wc:1,b:1,c:1});var hc;
function w(a,b){a.Rb=b;"[object Error]"!==Object.prototype.toString.call(a)&&(void 0===Error.captureStackTrace?Error():Error.captureStackTrace(a))}class ic extends Error{constructor(){super();this.Rb=null}ob(){return this.Rb}n(){var a=da(this),b=this.ob();return null===b?a:a+": "+b}m(){return m.prototype.m.call(this)}get message(){var a=this.ob();return null===a?"":a}get name(){return da(this)}toString(){return this.n()}}function jc(){}jc.prototype=new p;jc.prototype.constructor=jc;
function kc(){}kc.prototype=jc.prototype;jc.prototype.n=function(){return"\x3cfunction0\x3e"};function lc(){}lc.prototype=new p;lc.prototype.constructor=lc;function mc(){}mc.prototype=lc.prototype;lc.prototype.n=function(){return"\x3cfunction1\x3e"};function nc(a){this.Db=a}nc.prototype=new p;nc.prototype.constructor=nc;nc.prototype.n=function(){return""+this.Db};nc.prototype.$classData=t({Fe:0},!1,"scala.runtime.IntRef",{Fe:1,b:1,c:1});function oc(a){this.Eb=a}oc.prototype=new p;
oc.prototype.constructor=oc;oc.prototype.n=function(){return""+this.Eb};oc.prototype.$classData=t({Ge:0},!1,"scala.runtime.ObjectRef",{Ge:1,b:1,c:1});function pc(){this.Yb=this.C=0;qc=this;this.C=fa("Seq");this.Yb=fa("Map");fa("Set");var a=C().Ha,b=this.Yb,c=0,e=0,h=0,f=1;for(a=a.p();a.t();){var g=a.j();g=J(K(),g);c=c+g|0;e^=g;f=Math.imul(f,1|g);h=1+h|0}b=L(b,c);b=L(b,e);b=Mb(b,f);M(b^h)}pc.prototype=new Lb;pc.prototype.constructor=pc;
pc.prototype.$classData=t({kd:0},!1,"scala.util.hashing.MurmurHash3$",{kd:1,af:1,b:1});var qc;function N(){qc||(qc=new pc);return qc}class rc extends ic{}function Ya(){sc||(sc=new tc);return uc}function tc(){sc=this;uc=new vc(0,"Greet");new (v(wc).k)([Ya()])}tc.prototype=new p;tc.prototype.constructor=tc;tc.prototype.$classData=t({nc:0},!1,"mdocjs$Msg$",{nc:1,b:1,db:1,gd:1});var sc;function xc(){}xc.prototype=new p;xc.prototype.constructor=xc;function yc(){}yc.prototype=xc.prototype;
function zc(){}zc.prototype=new p;zc.prototype.constructor=zc;function Ac(){}Ac.prototype=zc.prototype;function Bc(){this.xa=null;Cc=this;this.xa=new Dc}Bc.prototype=new p;Bc.prototype.constructor=Bc;Bc.prototype.$classData=t({Id:0},!1,"scala.collection.Iterator$",{Id:1,b:1,la:1,c:1});var Cc;function vb(){Cc||(Cc=new Bc);return Cc}function Ec(a,b){this.ge=a;this.he=b}Ec.prototype=new p;Ec.prototype.constructor=Ec;Ec.prototype.q=function(){return this.ge};Ec.prototype.s=function(){return this.he};
Ec.prototype.$classData=t({fe:0},!1,"scala.collection.immutable.LazyList$State$Cons",{fe:1,b:1,ee:1,c:1});function Fc(){}Fc.prototype=new p;Fc.prototype.constructor=Fc;Fc.prototype.pb=function(){throw new Gc("head of empty lazy list");};Fc.prototype.s=function(){throw new Hc("tail of empty lazy list");};Fc.prototype.q=function(){this.pb()};Fc.prototype.$classData=t({ie:0},!1,"scala.collection.immutable.LazyList$State$Empty$",{ie:1,b:1,ee:1,c:1});var Kc;function Lc(){Kc||(Kc=new Fc);return Kc}
function Mc(a){this.Ce=a}Mc.prototype=new kc;Mc.prototype.constructor=Mc;Mc.prototype.$classData=t({Be:0},!1,"scala.scalajs.runtime.AnonFunction0",{Be:1,vf:1,b:1,Le:1});function Qb(a){this.Ee=a}Qb.prototype=new mc;Qb.prototype.constructor=Qb;Qb.prototype.r=function(a){return(0,this.Ee)(a)};Qb.prototype.$classData=t({De:0},!1,"scala.scalajs.runtime.AnonFunction1",{De:1,wf:1,b:1,u:1});function Nc(){Oc=this;Sa()}Nc.prototype=new p;Nc.prototype.constructor=Nc;Nc.prototype.n=function(){return"Attribute"};
Nc.prototype.$classData=t({qc:0},!1,"tyrian.Attribute$",{qc:1,b:1,db:1,Wb:1});var Oc;function Sa(){Oc||(Oc=new Nc)}function Pc(){(Qc=this)||(Qc=new Pc)}Pc.prototype=new p;Pc.prototype.constructor=Pc;Pc.prototype.n=function(){return"Property"};Pc.prototype.$classData=t({Fc:0},!1,"tyrian.Property$",{Fc:1,b:1,db:1,Wb:1});var Qc;class Rc extends rc{}Rc.prototype.$classData=t({ea:0},!1,"java.lang.RuntimeException",{ea:1,ha:1,ia:1,b:1,c:1});function hb(a){a.d="";return a}function ib(){this.d=null}
ib.prototype=new p;ib.prototype.constructor=ib;ib.prototype.n=function(){return this.d};ib.prototype.g=function(){return this.d.length};ib.prototype.$classData=t({Xc:0},!1,"java.lang.StringBuilder",{Xc:1,b:1,Qc:1,Re:1,c:1});function Sc(){}Sc.prototype=new p;Sc.prototype.constructor=Sc;function Tc(){}d=Tc.prototype=Sc.prototype;d.p=function(){return this};d.f=function(){return!this.t()};d.n=function(){return"\x3citerator\x3e"};d.oa=function(a,b,c,e){return jb(this,a,b,c,e)};
d.Ba=function(){D();return E(F(),this)};d.H=function(){return-1};function qb(){Uc||(Uc=new Vc)}qb.prototype=new Ac;qb.prototype.constructor=qb;qb.prototype.$classData=t({Gd:0},!1,"scala.collection.Iterable$",{Gd:1,Hd:1,b:1,la:1,c:1});var pb;function Wc(){}Wc.prototype=new p;Wc.prototype.constructor=Wc;function Xc(){}Xc.prototype=Wc.prototype;function Vc(){D()}Vc.prototype=new Ac;Vc.prototype.constructor=Vc;
Vc.prototype.$classData=t({ae:0},!1,"scala.collection.immutable.Iterable$",{ae:1,Hd:1,b:1,la:1,c:1});var Uc;function Yc(){this.xb=null;Zc=this;this.xb=$c(new ad(new Mc(()=>Lc())))}Yc.prototype=new p;Yc.prototype.constructor=Yc;function bd(a,b,c){var e=new oc(b),h=new nc(c);return new ad(new Mc(()=>{for(var f=e.Eb,g=h.Db;0<g&&!f.f();)f=R(f).s(),e.Eb=f,g=-1+g|0,h.Db=g;return R(f)}))}Yc.prototype.$classData=t({ce:0},!1,"scala.collection.immutable.LazyList$",{ce:1,b:1,Ia:1,la:1,c:1});var Zc;
function wb(){Zc||(Zc=new Yc);return Zc}class Ja extends Rc{}Ja.prototype.$classData=t({Ob:0},!1,"java.lang.IllegalArgumentException",{Ob:1,ea:1,ha:1,ia:1,b:1,c:1});function S(a,b){w(a,b);return a}class T extends Rc{}T.prototype.$classData=t({Pb:0},!1,"java.lang.IndexOutOfBoundsException",{Pb:1,ea:1,ha:1,ia:1,b:1,c:1});class H extends Rc{constructor(){super();w(this,null)}}H.prototype.$classData=t({Uc:0},!1,"java.lang.NullPointerException",{Uc:1,ea:1,ha:1,ia:1,b:1,c:1});
class Hc extends Rc{constructor(a){super();w(this,a)}}Hc.prototype.$classData=t({$c:0},!1,"java.lang.UnsupportedOperationException",{$c:1,ea:1,ha:1,ia:1,b:1,c:1});class Gc extends Rc{constructor(a){super();w(this,a)}}Gc.prototype.$classData=t({dd:0},!1,"java.util.NoSuchElementException",{dd:1,ea:1,ha:1,ia:1,b:1,c:1});function cd(){}cd.prototype=new p;cd.prototype.constructor=cd;function dd(){}dd.prototype=cd.prototype;cd.prototype.ja=function(){return new U(this)};
var wc=t({Fb:0},!1,"mdocjs$Msg",{Fb:1,b:1,o:1,ka:1,c:1,id:1});cd.prototype.$classData=wc;class Ab extends Rc{constructor(a){super();this.Tb=null;this.rb=!1;this.cb=a;w(this,null)}ob(){if(!this.rb&&!this.rb){if(null===this.cb)var a="null";else try{var b=this.cb;a=(void 0===b?"undefined":b.toString())+" (of class "+da(this.cb)+")"}catch(c){a="an instance of class "+da(this.cb)}this.Tb=a;this.rb=!0}return this.Tb}}Ab.prototype.$classData=t({ed:0},!1,"scala.MatchError",{ed:1,ea:1,ha:1,ia:1,b:1,c:1});
function U(a){this.Vb=this.Ga=0;this.Ub=null;if(null===a)throw null;this.Ub=a;this.Ga=0;this.Vb=a.Y()}U.prototype=new Tc;U.prototype.constructor=U;U.prototype.t=function(){return this.Ga<this.Vb};U.prototype.j=function(){var a=this.Ub.Z(this.Ga);this.Ga=1+this.Ga|0;return a};U.prototype.$classData=t({fd:0},!1,"scala.Product$$anon$1",{fd:1,D:1,b:1,z:1,h:1,i:1});function ed(a,b){this.mb=a;this.nb=b}ed.prototype=new p;ed.prototype.constructor=ed;d=ed.prototype;d.Y=function(){return 2};
d.Z=function(a){a:switch(a){case 0:a=this.mb;break a;case 1:a=this.nb;break a;default:throw S(new T,a+" is out of bounds (min 0, max 1)");}return a};d.n=function(){return"("+this.mb+","+this.nb+")"};d.$=function(){return"Tuple2"};d.ja=function(){return new fd(this)};d.m=function(){return Nb(this)};var gd=t({Pc:0},!1,"scala.Tuple2",{Pc:1,b:1,Te:1,ka:1,o:1,c:1});ed.prototype.$classData=gd;function hd(){}hd.prototype=new yc;hd.prototype.constructor=hd;
hd.prototype.$classData=t({Cd:0},!1,"scala.collection.ClassTagSeqFactory$AnySeqDelegate",{Cd:1,ef:1,b:1,la:1,c:1,Ia:1});function Dc(){}Dc.prototype=new Tc;Dc.prototype.constructor=Dc;Dc.prototype.t=function(){return!1};Dc.prototype.H=function(){return 0};Dc.prototype.j=function(){throw new Gc("next on empty iterator");};Dc.prototype.$classData=t({Jd:0},!1,"scala.collection.Iterator$$anon$19",{Jd:1,D:1,b:1,z:1,h:1,i:1});
function id(a,b){if(0>b)throw S(new T,""+b);a=a.Lb(b);if(a.f())throw S(new T,""+b);return a.q()}function jd(a){this.fb=a}jd.prototype=new Tc;jd.prototype.constructor=jd;jd.prototype.t=function(){return!this.fb.f()};jd.prototype.j=function(){var a=this.fb.q();this.fb=this.fb.G();return a};jd.prototype.$classData=t({Md:0},!1,"scala.collection.StrictOptimizedLinearSeqOps$$anon$1",{Md:1,D:1,b:1,z:1,h:1,i:1});function ub(){xb()}ub.prototype=new Xc;ub.prototype.constructor=ub;
ub.prototype.$classData=t({$d:0},!1,"scala.collection.immutable.IndexedSeq$",{$d:1,Kd:1,b:1,Ia:1,la:1,c:1});var tb;function kd(a){this.Sa=a}kd.prototype=new Tc;kd.prototype.constructor=kd;kd.prototype.t=function(){return!this.Sa.f()};kd.prototype.j=function(){if(this.Sa.f())return vb().xa.j();var a=R(this.Sa).q();this.Sa=R(this.Sa).s();return a};kd.prototype.$classData=t({de:0},!1,"scala.collection.immutable.LazyList$LazyIterator",{de:1,D:1,b:1,z:1,h:1,i:1});function ld(){md=this;F();F()}
ld.prototype=new p;ld.prototype.constructor=ld;ld.prototype.$classData=t({ke:0},!1,"scala.collection.immutable.List$",{ke:1,b:1,Nd:1,Ia:1,la:1,c:1});var md;function D(){md||(md=new ld)}function nd(a,b,c){this.hc=this.hb=this.Va=this.Ua=this.Ta=null;this.ib=b;this.me=c;this.ya=a.Aa;this.Ab=this.ya.a.length;this.Bb=this.X=0;this.ma=this.ib;this.Xa=0;this.za=1;this.Cb=0;this.Wa=this.Ab}nd.prototype=new p;nd.prototype.constructor=nd;d=nd.prototype;d.p=function(){return this};
d.f=function(){return this.ma<=this.X};d.n=function(){return"\x3citerator\x3e"};d.oa=function(a,b,c,e){return jb(this,a,b,c,e)};d.Ba=function(){D();return E(F(),this)};d.H=function(){return this.ma-this.X|0};d.t=function(){return this.ma>this.X};
d.j=function(){if(this.X===this.Ab){var a=(this.X-this.ma|0)+this.ib|0;if(a===this.Wa){this.ma<=this.X&&vb().xa.j();this.Xa=1+this.Xa|0;for(var b=null;0===b.a.length;)this.Xa=1+this.Xa|0,b=null;this.Cb=this.Wa;var c=this.me/2|0,e=this.Xa-c|0;c=this.za=(1+c|0)-(0>e?-e|0:e)|0;switch(c){case 1:this.ya=b;break;case 2:this.Ta=b;break;case 3:this.Ua=b;break;case 4:this.Va=b;break;case 5:this.hb=b;break;case 6:this.hc=b;break;default:throw new Ab(c);}this.Wa=this.Cb+Math.imul(b.a.length,1<<Math.imul(5,-1+
this.za|0))|0;this.Wa>this.ib&&(this.Wa=this.ib);1<this.za&&(this.Bb=-1+(1<<Math.imul(5,this.za))|0)}1<this.za&&(a=a-this.Cb|0,b=this.Bb^a,1024>b?this.ya=this.Ta.a[31&(a>>>5|0)]:(32768>b?this.Ta=this.Ua.a[31&(a>>>10|0)]:(1048576>b?this.Ua=this.Va.a[31&(a>>>15|0)]:(33554432>b?this.Va=this.hb.a[31&(a>>>20|0)]:(this.hb=this.hc.a[a>>>25|0],this.Va=this.hb.a[0]),this.Ua=this.Va.a[0]),this.Ta=this.Ua.a[0]),this.ya=this.Ta.a[0]),this.Bb=a);this.ma=this.ma-this.X|0;a=this.ya.a.length;b=this.ma;this.Ab=a<
b?a:b;this.X=0}a=this.ya.a[this.X];this.X=1+this.X|0;return a};d.$classData=t({le:0},!1,"scala.collection.immutable.NewVectorIterator",{le:1,b:1,z:1,h:1,i:1,$a:1});function sb(){D()}sb.prototype=new Xc;sb.prototype.constructor=sb;sb.prototype.$classData=t({oe:0},!1,"scala.collection.immutable.Seq$",{oe:1,Kd:1,b:1,Ia:1,la:1,c:1});var rb;
function od(){this.ic=null;pd=this;try{var a=Ea;Da||(Da=new Ca);var b=a(Da,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250");fc||(fc=new ec);var c=null===b?0:b.length;0===c&&cc(b);var e=b.charCodeAt(0),h=45===e;a=h?2147483648:2147483647;e=h||43===e?1:0;e>=b.length&&cc(b);for(h=0;e!==c;){bc||(bc=new ac);var f=bc,g=b.charCodeAt(e);if(256>g)var n=48<=g&&57>=g?-48+g|0:65<=g&&90>=g?-55+g|0:97<=g&&122>=g?-87+g|0:-1;else if(65313<=g&&65338>=g)n=-65303+g|0;else if(65345<=g&&65370>=
g)n=-65335+g|0;else{Oa||(Oa=new Ma);b:for(var y=$b(f),X=0,Na=y.a.length;;){if(X===Na){var Ic=-1-X|0;break b}var Jc=(X+Na|0)>>>1|0,de=y.a[Jc],ee=g===de?0:g<de?-1:1;if(0>ee)Na=Jc;else{if(0===ee){Ic=Jc;break b}X=1+Jc|0}}X=0>Ic?-2-Ic|0:Ic;if(0>X)n=-1;else{var fe=g-$b(f).a[X]|0;n=9<fe?-1:fe}}var ge=10>n?n:-1;h=10*h+ge;(-1===ge||h>a)&&cc(b);e=1+e|0}}catch(Fe){throw Fe;}this.ic=new nd(qd(),0,0)}od.prototype=new p;od.prototype.constructor=od;
od.prototype.$classData=t({pe:0},!1,"scala.collection.immutable.Vector$",{pe:1,b:1,Nd:1,Ia:1,la:1,c:1});var pd;function xb(){pd||(pd=new od);return pd}function fd(a){this.kc=0;this.Je=a;this.jb=0;this.kc=a.Y()}fd.prototype=new Tc;fd.prototype.constructor=fd;fd.prototype.t=function(){return this.jb<this.kc};fd.prototype.j=function(){var a=this.Je.Z(this.jb);this.jb=1+this.jb|0;return a};fd.prototype.$classData=t({Ie:0},!1,"scala.runtime.ScalaRunTime$$anon$1",{Ie:1,D:1,b:1,z:1,h:1,i:1});
function Ta(a,b){this.rc=a;this.sc=b}Ta.prototype=new p;Ta.prototype.constructor=Ta;d=Ta.prototype;d.ja=function(){return new U(this)};d.m=function(){return Nb(this)};d.n=function(){return Bb(this)};d.Y=function(){return 2};d.$=function(){return"Attribute"};d.Z=function(a){if(0===a)return this.rc;if(1===a)return this.sc;throw S(new T,""+a);};var rd=t({pc:0},!1,"tyrian.Attribute",{pc:1,b:1,kb:1,o:1,ka:1,c:1});Ta.prototype.$classData=rd;function Pb(a,b){this.vc=a;this.uc=b}Pb.prototype=new p;
Pb.prototype.constructor=Pb;d=Pb.prototype;d.ja=function(){return new U(this)};d.m=function(){return Nb(this)};d.n=function(){return Bb(this)};d.Y=function(){return 2};d.$=function(){return"Event"};d.Z=function(a){if(0===a)return this.vc;if(1===a)return this.uc;throw S(new T,""+a);};d.$classData=t({tc:0},!1,"tyrian.Event",{tc:1,b:1,kb:1,o:1,ka:1,c:1});
function sd(){this.Ca=this.Jb=null;td=this;new Q(this,"accept");new Q(this,"accesskey");new Q(this,"action");new Q(this,"alt");new Q(this,"autocomplete");new Q(this,"charset");new Q(this,"cite");this.Jb=new Q(this,"class");new Q(this,"class");new Q(this,"class");new Q(this,"class");new Q(this,"class");new Q(this,"cols");new P(this,"cols");new Q(this,"colspan");new P(this,"colspan");new Q(this,"colspan");new P(this,"colspan");new Q(this,"content");new Q(this,"contenteditable");new O(this,"contenteditable");
new Q(this,"contenteditable");new O(this,"contenteditable");new Q(this,"coords");new Q(this,"data");new Q(this,"datetime");new Q(this,"datetime");new Q(this,"dir");new Q(this,"dirname");new Q(this,"draggable");new O(this,"draggable");new Q(this,"enctype");new Q(this,"enctype");new Q(this,"for");new Q(this,"for");new Q(this,"for");new Q(this,"form");new Q(this,"formaction");new Q(this,"formaction");new Q(this,"headers");new Q(this,"height");new P(this,"height");new Q(this,"high");new Rb(this,"high");
new Q(this,"href");new Q(this,"hreflang");new Q(this,"hreflang");new Q(this,"http");this.Ca=new Q(this,"id");new Q(this,"kind");new Q(this,"label");new Q(this,"lang");new Q(this,"list");new Q(this,"low");new Rb(this,"low");new Q(this,"max");new P(this,"max");new Q(this,"maxlength");new P(this,"maxlength");new Q(this,"maxlength");new P(this,"maxlength");new Q(this,"media");new Q(this,"method");new Q(this,"min");new P(this,"min");new Q(this,"multiple");new Q(this,"muted");new Q(this,"name");new Q(this,
"optimum");new Rb(this,"optimum");new Q(this,"pattern");new Q(this,"placeholder");new Q(this,"poster");new Q(this,"preload");new Q(this,"rel");new Q(this,"rows");new P(this,"rows");new Q(this,"rowspan");new P(this,"rowspan");new Q(this,"rowspan");new P(this,"rowspan");new Q(this,"scope");new Q(this,"shape");new Q(this,"size");new P(this,"size");new Q(this,"sizes");new Q(this,"span");new P(this,"span");new Q(this,"spellcheck");new O(this,"spellcheck");new Q(this,"spellcheck");new O(this,"spellcheck");
new Q(this,"src");new Q(this,"srcdoc");new Q(this,"srcdoc");new Q(this,"srclang");new Q(this,"srclang");new Q(this,"srcset");new Q(this,"srcset");new Q(this,"start");new P(this,"start");new Q(this,"step");new P(this,"step");new Q(this,"style");new Q(this,"tabindex");new P(this,"tabindex");new Q(this,"tabindex");new P(this,"tabindex");new Q(this,"target");new Q(this,"title");new Q(this,"translate");new Q(this,"type");new Q(this,"type");new Q(this,"type");new Q(this,"type");new Q(this,"usemap");new Q(this,
"usemap");new Q(this,"width");new P(this,"width");new Q(this,"wrap");new Ub(this,"value");new Tb(this,"value");new Sb(this,"value")}sd.prototype=new p;sd.prototype.constructor=sd;function ud(){x();var a=A(z(),new (v(gd).k)([new ed("width","100px"),new ed("height","50px")]));Sa();Zb(Xb(),a.bb(new Qb(b=>Ra(b.mb,b.nb))).Ba())}sd.prototype.$classData=t({wc:0},!1,"tyrian.Html$",{wc:1,b:1,Oe:1,Ne:1,db:1,gd:1});var td;function x(){td||(td=new sd);return td}function B(a){this.Mc=a}B.prototype=new p;
B.prototype.constructor=B;d=B.prototype;d.ja=function(){return new U(this)};d.m=function(){return Nb(this)};d.n=function(){return Bb(this)};d.Y=function(){return 1};d.$=function(){return"Text"};d.Z=function(a){if(0===a)return this.Mc;throw S(new T,""+a);};var $a=t({Lc:0},!1,"tyrian.Text",{Lc:1,b:1,lb:1,o:1,ka:1,c:1});B.prototype.$classData=$a;function ha(a){return Aa(Ba(),a)}class dc extends Ja{constructor(a){super();w(this,a)}}
dc.prototype.$classData=t({Vc:0},!1,"java.lang.NumberFormatException",{Vc:1,Ob:1,ea:1,ha:1,ia:1,b:1,c:1});function fa(a){for(var b=0,c=1,e=-1+a.length|0;0<=e;)b=b+Math.imul(a.charCodeAt(e),c)|0,c=Math.imul(31,c),e=-1+e|0;return b}function Yb(a){return";"===a.substring(a.length-1|0)}class vd extends T{constructor(){super();w(this,null)}}vd.prototype.$classData=t({Yc:0},!1,"java.lang.StringIndexOutOfBoundsException",{Yc:1,Pb:1,ea:1,ha:1,ia:1,b:1,c:1});function wd(){}wd.prototype=new p;
wd.prototype.constructor=wd;function xd(){}xd.prototype=wd.prototype;wd.prototype.qa=function(){return this.sa()};wd.prototype.oa=function(a,b,c,e){return jb(this,a,b,c,e)};wd.prototype.Ba=function(){D();return E(F(),this)};wd.prototype.H=function(){return-1};function V(a,b){a.R=b;a.e=0;z();b=a.R;b=Ia(La(),b);a.Q=b;return a}function yd(){this.R=null;this.Q=this.e=0}yd.prototype=new Tc;yd.prototype.constructor=yd;function W(){}W.prototype=yd.prototype;
yd.prototype.H=function(){return this.Q-this.e|0};yd.prototype.t=function(){return this.e<this.Q};yd.prototype.j=function(){try{var a=zb(z(),this.R,this.e);this.e=1+this.e|0;return a}catch(b){throw b;}};yd.prototype.$classData=t({aa:0},!1,"scala.collection.ArrayOps$ArrayIterator",{aa:1,D:1,b:1,z:1,h:1,i:1,c:1});function zd(a){this.wa=0;this.Fd=a;this.tb=0;this.wa=a.g()}zd.prototype=new Tc;zd.prototype.constructor=zd;zd.prototype.H=function(){return this.wa};zd.prototype.t=function(){return 0<this.wa};
zd.prototype.j=function(){if(0<this.wa){var a=this.Fd.l(this.tb);this.tb=1+this.tb|0;this.wa=-1+this.wa|0;return a}return vb().xa.j()};zd.prototype.$classData=t({Ed:0},!1,"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{Ed:1,D:1,b:1,z:1,h:1,i:1,c:1});function Ad(){this.cc=null;this.ub=!1;Bd=this;new hd(this)}Ad.prototype=new p;Ad.prototype.constructor=Ad;
function Cd(a,b){if(null===b)return null;if(b instanceof q)return new Fb(b);if(b instanceof qa)return new Dd(b);if(b instanceof ta)return new Ed(b);if(b instanceof ra)return new Fd(b);if(b instanceof sa)return new Gd(b);if(b instanceof na)return new Hd(b);if(b instanceof oa)return new Id(b);if(b instanceof pa)return new Jd(b);if(b instanceof ma)return new Kd(b);if(b&&b.$classData&&1===b.$classData.ua&&b.$classData.ta.da.Se)return new Ld(b);throw new Ab(b);}
Ad.prototype.$classData=t({Pd:0},!1,"scala.collection.immutable.ArraySeq$",{Pd:1,b:1,lf:1,ff:1,df:1,gf:1,c:1});var Bd;function Cb(){Bd||(Bd=new Ad);return Bd}function G(a,b,c){this.Kc=a;this.Ic=b;this.Jc=c}G.prototype=new p;G.prototype.constructor=G;d=G.prototype;d.ja=function(){return new U(this)};d.m=function(){return Nb(this)};d.n=function(){return Bb(this)};d.Y=function(){return 3};d.$=function(){return"Tag"};
d.Z=function(a){switch(a){case 0:return this.Kc;case 1:return this.Ic;case 2:return this.Jc;default:throw S(new T,""+a);}};d.$classData=t({Hc:0},!1,"tyrian.Tag",{Hc:1,b:1,lb:1,Me:1,o:1,ka:1,c:1});function Md(a){this.R=null;this.Q=this.e=0;this.md=a;V(this,a)}Md.prototype=new W;Md.prototype.constructor=Md;Md.prototype.j=function(){try{var a=this.md.a[this.e];this.e=1+this.e|0}catch(b){throw b;}return a};
Md.prototype.$classData=t({ld:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcB$sp",{ld:1,aa:1,D:1,b:1,z:1,h:1,i:1,c:1});function Nd(a){this.R=null;this.Q=this.e=0;this.od=a;V(this,a)}Nd.prototype=new W;Nd.prototype.constructor=Nd;Nd.prototype.j=function(){try{var a=this.od.a[this.e];this.e=1+this.e|0}catch(b){throw b;}return new k(a)};Nd.prototype.$classData=t({nd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcC$sp",{nd:1,aa:1,D:1,b:1,z:1,h:1,i:1,c:1});
function Od(a){this.R=null;this.Q=this.e=0;this.qd=a;V(this,a)}Od.prototype=new W;Od.prototype.constructor=Od;Od.prototype.j=function(){try{var a=this.qd.a[this.e];this.e=1+this.e|0}catch(b){throw b;}return a};Od.prototype.$classData=t({pd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcD$sp",{pd:1,aa:1,D:1,b:1,z:1,h:1,i:1,c:1});function Pd(a){this.R=null;this.Q=this.e=0;this.sd=a;V(this,a)}Pd.prototype=new W;Pd.prototype.constructor=Pd;
Pd.prototype.j=function(){try{var a=this.sd.a[this.e];this.e=1+this.e|0}catch(b){throw b;}return a};Pd.prototype.$classData=t({rd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcF$sp",{rd:1,aa:1,D:1,b:1,z:1,h:1,i:1,c:1});function Qd(a){this.R=null;this.Q=this.e=0;this.ud=a;V(this,a)}Qd.prototype=new W;Qd.prototype.constructor=Qd;Qd.prototype.j=function(){try{var a=this.ud.a[this.e];this.e=1+this.e|0}catch(b){throw b;}return a};
Qd.prototype.$classData=t({td:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcI$sp",{td:1,aa:1,D:1,b:1,z:1,h:1,i:1,c:1});function Rd(a){this.R=null;this.Q=this.e=0;this.wd=a;V(this,a)}Rd.prototype=new W;Rd.prototype.constructor=Rd;Rd.prototype.j=function(){try{var a=this.wd.a[this.e],b=a.W,c=a.V;this.e=1+this.e|0;var e=new l(b,c)}catch(h){throw h;}return e};Rd.prototype.$classData=t({vd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcJ$sp",{vd:1,aa:1,D:1,b:1,z:1,h:1,i:1,c:1});
function Sd(a){this.R=null;this.Q=this.e=0;this.yd=a;V(this,a)}Sd.prototype=new W;Sd.prototype.constructor=Sd;Sd.prototype.j=function(){try{var a=this.yd.a[this.e];this.e=1+this.e|0}catch(b){throw b;}return a};Sd.prototype.$classData=t({xd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcS$sp",{xd:1,aa:1,D:1,b:1,z:1,h:1,i:1,c:1});function Td(a){this.R=null;this.Q=this.e=0;V(this,a)}Td.prototype=new W;Td.prototype.constructor=Td;Td.prototype.j=function(){try{this.e=1+this.e|0}catch(a){throw a;}};
Td.prototype.$classData=t({zd:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcV$sp",{zd:1,aa:1,D:1,b:1,z:1,h:1,i:1,c:1});function Ud(a){this.R=null;this.Q=this.e=0;this.Bd=a;V(this,a)}Ud.prototype=new W;Ud.prototype.constructor=Ud;Ud.prototype.j=function(){try{var a=this.Bd.a[this.e];this.e=1+this.e|0}catch(b){throw b;}return a};Ud.prototype.$classData=t({Ad:0},!1,"scala.collection.ArrayOps$ArrayIterator$mcZ$sp",{Ad:1,aa:1,D:1,b:1,z:1,h:1,i:1,c:1});function Vd(){}Vd.prototype=new p;
Vd.prototype.constructor=Vd;function Wd(){}Wd.prototype=Vd.prototype;function Xd(){this.Xb=null;this.sb=0}Xd.prototype=new Wd;Xd.prototype.constructor=Xd;function Yd(){}Yd.prototype=Xd.prototype;Xd.prototype.n=function(){return this.Xb};Xd.prototype.m=function(){return this.sb};function Zd(){}Zd.prototype=new xd;Zd.prototype.constructor=Zd;function $d(){}$d.prototype=Zd.prototype;Zd.prototype.n=function(){return this.qa()+"(\x3cnot computed\x3e)"};
function Eb(){this.sb=0;this.Xb="Object";C();this.sb=ka(this)}Eb.prototype=new Yd;Eb.prototype.constructor=Eb;Eb.prototype.$classData=t({jd:0},!1,"scala.reflect.ManifestFactory$ObjectManifest$",{jd:1,Ze:1,Ye:1,b:1,Xe:1,We:1,Ve:1,$e:1,c:1,o:1});var Db;function vc(a,b){this.Gb=b}vc.prototype=new dd;vc.prototype.constructor=vc;d=vc.prototype;d.Y=function(){return 0};d.Z=function(a){throw S(new T,""+a);};d.$=function(){return this.Gb};d.n=function(){return this.Gb};
d.$classData=t({oc:0},!1,"mdocjs$Msg$$anon$1",{oc:1,Fb:1,b:1,o:1,ka:1,c:1,id:1,xf:1,db:1,Wb:1,Ue:1});function ae(){}ae.prototype=new xd;ae.prototype.constructor=ae;function be(){}be.prototype=ae.prototype;
ae.prototype.m=function(){var a=N();if(this&&this.$classData&&this.$classData.da.I)a:{var b=a.C;a=this.g();switch(a){case 0:a=M(b^0);break a;case 1:a=b;b=this.l(0);a=M(L(a,J(K(),b))^1);break a;default:var c=this.l(0),e=J(K(),c);c=b=L(b,e);var h=this.l(1);h=J(K(),h);var f=h-e|0;for(e=2;e<a;){b=L(b,h);var g=this.l(e);g=J(K(),g);if(f!==(g-h|0)){b=L(b,g);for(e=1+e|0;e<a;)c=this.l(e),b=L(b,J(K(),c)),e=1+e|0;a=M(b^a);break a}h=g;e=1+e|0}a=M(L(L(c,f),h))}}else if(this instanceof ce){a=a.C;e=0;h=a;b=c=g=
f=0;for(var n=this;!n.f();){var y=n.q();n=n.G();y=J(K(),y);h=L(h,y);switch(f){case 0:b=y;f=1;break;case 1:g=y-c|0;f=2;break;case 2:g!==(y-c|0)&&(f=3)}c=y;e=1+e|0}2===f?(e=g,a=M(L(L(L(a,b),e),c))):a=M(h^e)}else a:if(b=a.C,a=this.p(),a.t())if(c=a.j(),a.t()){e=a.j();f=J(K(),c);c=b=L(b,f);h=J(K(),e);f=h-f|0;for(e=2;a.t();){b=L(b,h);g=a.j();g=J(K(),g);if(f!==(g-h|0)){b=L(b,g);for(e=1+e|0;a.t();)c=a.j(),b=L(b,J(K(),c)),e=1+e|0;a=M(b^e);break a}h=g;e=1+e|0}a=M(L(L(c,f),h))}else a=M(L(b,J(K(),c))^1);else a=
M(b^0);return a};ae.prototype.n=function(){return fb(this,this.qa()+"(",", ")};ae.prototype.f=function(){return 0===this.ra(0)};function he(){}he.prototype=new $d;he.prototype.constructor=he;function ie(){}ie.prototype=he.prototype;function je(){this.eb=null}je.prototype=new ie;je.prototype.constructor=je;function ke(){}ke.prototype=je.prototype;je.prototype.l=function(a){return this.eb.l(a)};je.prototype.g=function(){return this.eb.g()};je.prototype.f=function(){return this.eb.f()};
function le(a){this.eb=a}le.prototype=new ke;le.prototype.constructor=le;d=le.prototype;d.p=function(){return new zd(this)};d.sa=function(){return"IndexedSeqView"};d.ra=function(a){var b=this.g();return b===a?0:b<a?-1:1};d.H=function(){return this.g()};d.$classData=t({Dd:0},!1,"scala.collection.IndexedSeqView$Id",{Dd:1,kf:1,bf:1,cf:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,mf:1,c:1,jf:1,A:1,hf:1,J:1});function me(){}me.prototype=new be;me.prototype.constructor=me;function ne(){}ne.prototype=me.prototype;
function oe(){}oe.prototype=new be;oe.prototype.constructor=oe;function pe(){}pe.prototype=oe.prototype;var re=function qe(a,b){wb();return new ad(new Mc(()=>{if(a.f())return Lc();wb();var e=b.r(R(a).q()),h=qe(R(a).s(),b);return new Ec(e,h)}))};
function se(a,b,c,e,h){b.d=""+b.d+c;if(!a.S)b.d+="\x3cnot computed\x3e";else if(!a.f()){c=R(a).q();b.d=""+b.d+c;c=a;var f=R(a).s();if(c!==f&&(!f.S||R(c)!==R(f))&&(c=f,f.S&&!f.f()))for(f=R(f).s();c!==f&&f.S&&!f.f()&&R(c)!==R(f);){b.d=""+b.d+e;var g=R(c).q();b.d=""+b.d+g;c=R(c).s();f=R(f).s();f.S&&!f.f()&&(f=R(f).s())}if(!f.S||f.f()){for(;c!==f;)b.d=""+b.d+e,a=R(c).q(),b.d=""+b.d+a,c=R(c).s();c.S||(b.d=""+b.d+e,b.d+="\x3cnot computed\x3e")}else{g=a;for(a=0;;){var n=g,y=f;if(n!==y&&R(n)!==R(y))g=R(g).s(),
f=R(f).s(),a=1+a|0;else break}g=c;n=f;(g===n||R(g)===R(n))&&0<a&&(b.d=""+b.d+e,a=R(c).q(),b.d=""+b.d+a,c=R(c).s());for(;;)if(a=c,g=f,a!==g&&R(a)!==R(g))b.d=""+b.d+e,a=R(c).q(),b.d=""+b.d+a,c=R(c).s();else break;b.d=""+b.d+e;b.d+="\x3ccycle\x3e"}}b.d=""+b.d+h;return b}function ad(a){this.ec=null;this.yb=!1;this.dc=a;this.zb=this.S=!1}ad.prototype=new ne;ad.prototype.constructor=ad;d=ad.prototype;d.sa=function(){return"LinearSeq"};d.g=function(){for(var a=this,b=0;!a.f();)b=1+b|0,a=a.G();return b};
d.ra=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.f()?0:1;break a}if(b.f()){a=-1;break a}c=1+c|0;b=b.G()}return a};d.l=function(a){return id(this,a)};function R(a){if(!a.yb&&!a.yb){if(a.zb)throw a=new Rc,w(a,"self-referential LazyList or a derivation thereof has no more elements"),a;a.zb=!0;try{var b=(0,a.dc.Ce)()}finally{a.zb=!1}a.S=!0;a.dc=null;a.ec=b;a.yb=!0}return a.ec}d.f=function(){return R(this)===Lc()};d.H=function(){return this.S&&this.f()?0:-1};d.q=function(){return R(this).q()};
function $c(a){var b=a,c=a;for(b.f()||(b=R(b).s());c!==b&&!b.f();){b=R(b).s();if(b.f())break;b=R(b).s();if(b===c)break;c=R(c).s()}return a}d.p=function(){return this.S&&this.f()?vb().xa:new kd(this)};d.qa=function(){return"LazyList"};d.oa=function(a,b,c,e){$c(this);se(this,a.U,b,c,e);return a};d.n=function(){var a=new ib;hb(a);a.d="LazyList";return se(this,a,"(",", ",")").d};d.r=function(a){return id(this,a|0)};d.Lb=function(a){return 0>=a?this:this.S&&this.f()?wb().xb:bd(wb(),this,a)};
d.bb=function(a){return this.S&&this.f()?wb().xb:re(this,a)};d.G=function(){return R(this).s()};d.$classData=t({be:0},!1,"scala.collection.immutable.LazyList",{be:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,fc:1,Zb:1,$b:1,gc:1,c:1});function te(){}te.prototype=new ne;te.prototype.constructor=te;function Y(){}d=Y.prototype=te.prototype;d.sa=function(){return"IndexedSeq"};d.ra=function(a){var b=this.g();return b===a?0:b<a?-1:1};d.H=function(){return this.g()};d.qa=function(){return"ArraySeq"};
d.bb=function(a){for(var b=new q(this.g()),c=0;c<b.a.length;)b.a[c]=a.r(this.l(c)),c=1+c|0;return Cd(Cb(),b)};function ue(){this.Aa=null}ue.prototype=new ne;ue.prototype.constructor=ue;function ve(){}d=ve.prototype=ue.prototype;d.sa=function(){return"IndexedSeq"};d.ra=function(a){var b=this.g();return b===a?0:b<a?-1:1};d.H=function(){return this.g()};d.g=function(){return this instanceof we?this.wb:this.Aa.a.length};d.p=function(){return qd()===this?xb().ic:new nd(this,this.g(),0)};d.qa=function(){return"Vector"};
function xe(){}xe.prototype=new pe;xe.prototype.constructor=xe;function ye(){}ye.prototype=xe.prototype;xe.prototype.sa=function(){return"IndexedSeq"};xe.prototype.ra=function(a){var b=this.g();return b===a?0:b<a?-1:1};xe.prototype.H=function(){return this.g()};xe.prototype.qa=function(){return"ArraySeq"};function Kd(a){this.Ka=a}Kd.prototype=new Y;Kd.prototype.constructor=Kd;d=Kd.prototype;d.g=function(){return this.Ka.a.length};
d.m=function(){var a=N();a:{var b=this.Ka;a=a.C;var c=b.a.length;switch(c){case 0:b=M(a^0);break a;case 1:b=M(L(a,b.a[0]?1231:1237)^1);break a;default:var e=b.a[0]?1231:1237,h=a=L(a,e),f=b.a[1]?1231:1237;e=f-e|0;for(var g=2;g<c;){a=L(a,f);var n=b.a[g]?1231:1237;if(e!==(n-f|0)){a=L(a,n);for(g=1+g|0;g<c;)a=L(a,b.a[g]?1231:1237),g=1+g|0;b=M(a^c);break a}f=n;g=1+g|0}b=M(L(L(h,e),f))}}return b};d.p=function(){return new Ud(this.Ka)};d.r=function(a){return this.Ka.a[a|0]};d.l=function(a){return this.Ka.a[a]};
d.$classData=t({Qd:0},!1,"scala.collection.immutable.ArraySeq$ofBoolean",{Qd:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function Id(a){this.La=a}Id.prototype=new Y;Id.prototype.constructor=Id;d=Id.prototype;d.g=function(){return this.La.a.length};
d.m=function(){var a=N();a:{var b=this.La;a=a.C;var c=b.a.length;switch(c){case 0:b=M(a^0);break a;case 1:b=M(L(a,b.a[0])^1);break a;default:var e=b.a[0],h=a=L(a,e),f=b.a[1];e=f-e|0;for(var g=2;g<c;){a=L(a,f);var n=b.a[g];if(e!==(n-f|0)){a=L(a,n);for(g=1+g|0;g<c;)a=L(a,b.a[g]),g=1+g|0;b=M(a^c);break a}f=n;g=1+g|0}b=M(L(L(h,e),f))}}return b};d.p=function(){return new Md(this.La)};d.r=function(a){return this.La.a[a|0]};d.l=function(a){return this.La.a[a]};
d.$classData=t({Rd:0},!1,"scala.collection.immutable.ArraySeq$ofByte",{Rd:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function Hd(a){this.Ma=a}Hd.prototype=new Y;Hd.prototype.constructor=Hd;d=Hd.prototype;d.g=function(){return this.Ma.a.length};d.Ea=function(a){return this.Ma.a[a]};d.m=function(){var a=N();return Ob(this.Ma,a.C)};d.p=function(){return new Nd(this.Ma)};d.oa=function(a,b,c,e){return(new ze(this.Ma)).oa(a,b,c,e)};
d.r=function(a){return new k(this.Ea(a|0))};d.l=function(a){return new k(this.Ea(a))};d.$classData=t({Sd:0},!1,"scala.collection.immutable.ArraySeq$ofChar",{Sd:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function Ed(a){this.Na=a}Ed.prototype=new Y;Ed.prototype.constructor=Ed;d=Ed.prototype;d.g=function(){return this.Na.a.length};
d.m=function(){var a=N();a:{var b=this.Na;a=a.C;var c=b.a.length;switch(c){case 0:b=M(a^0);break a;case 1:b=b.a[0];b=M(L(a,I(K(),b))^1);break a;default:var e=b.a[0],h=I(K(),e);e=a=L(a,h);var f=b.a[1];f=I(K(),f);var g=f-h|0;for(h=2;h<c;){a=L(a,f);var n=b.a[h];n=I(K(),n);if(g!==(n-f|0)){a=L(a,n);for(h=1+h|0;h<c;)e=b.a[h],a=L(a,I(K(),e)),h=1+h|0;b=M(a^c);break a}f=n;h=1+h|0}b=M(L(L(e,g),f))}}return b};d.p=function(){return new Od(this.Na)};d.r=function(a){return this.Na.a[a|0]};d.l=function(a){return this.Na.a[a]};
d.$classData=t({Td:0},!1,"scala.collection.immutable.ArraySeq$ofDouble",{Td:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function Gd(a){this.Oa=a}Gd.prototype=new Y;Gd.prototype.constructor=Gd;d=Gd.prototype;d.g=function(){return this.Oa.a.length};
d.m=function(){var a=N();a:{var b=this.Oa;var c=a.C;a=b.a.length;switch(a){case 0:b=M(c^0);break a;case 1:a=c;b=b.a[0];K();b=M(L(a,I(0,b))^1);break a;default:var e=b.a[0],h=I(K(),e);e=c=L(c,h);var f=b.a[1];f=I(K(),f);var g=f-h|0;for(h=2;h<a;){c=L(c,f);var n=b.a[h];n=I(K(),n);if(g!==(n-f|0)){c=L(c,n);for(h=1+h|0;h<a;)e=b.a[h],K(),c=L(c,I(0,e)),h=1+h|0;b=M(c^a);break a}f=n;h=1+h|0}b=M(L(L(e,g),f))}}return b};d.p=function(){return new Pd(this.Oa)};d.r=function(a){return this.Oa.a[a|0]};d.l=function(a){return this.Oa.a[a]};
d.$classData=t({Ud:0},!1,"scala.collection.immutable.ArraySeq$ofFloat",{Ud:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function Dd(a){this.Pa=a}Dd.prototype=new Y;Dd.prototype.constructor=Dd;d=Dd.prototype;d.g=function(){return this.Pa.a.length};
d.m=function(){var a=N();a:{var b=this.Pa;a=a.C;var c=b.a.length;switch(c){case 0:b=M(a^0);break a;case 1:b=M(L(a,b.a[0])^1);break a;default:var e=b.a[0],h=a=L(a,e),f=b.a[1];e=f-e|0;for(var g=2;g<c;){a=L(a,f);var n=b.a[g];if(e!==(n-f|0)){a=L(a,n);for(g=1+g|0;g<c;)a=L(a,b.a[g]),g=1+g|0;b=M(a^c);break a}f=n;g=1+g|0}b=M(L(L(h,e),f))}}return b};d.p=function(){return new Qd(this.Pa)};d.r=function(a){return this.Pa.a[a|0]};d.l=function(a){return this.Pa.a[a]};
d.$classData=t({Vd:0},!1,"scala.collection.immutable.ArraySeq$ofInt",{Vd:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function Fd(a){this.Qa=a}Fd.prototype=new Y;Fd.prototype.constructor=Fd;d=Fd.prototype;d.g=function(){return this.Qa.a.length};
d.m=function(){var a=N();a:{var b=this.Qa;a=a.C;var c=b.a.length;switch(c){case 0:a=M(a^0);break a;case 1:c=b.a[0];b=c.W;c=c.V;a=M(L(a,Ib(K(),new l(b,c)))^1);break a;default:var e=b.a[0],h=e.W;e=e.V;e=Ib(K(),new l(h,e));h=a=L(a,e);var f=b.a[1],g=f.W;f=f.V;g=Ib(K(),new l(g,f));f=g-e|0;for(e=2;e<c;){a=L(a,g);var n=b.a[e],y=n.W;n=n.V;y=Ib(K(),new l(y,n));if(f!==(y-g|0)){a=L(a,y);for(e=1+e|0;e<c;)g=b.a[e],h=g.W,g=g.V,a=L(a,Ib(K(),new l(h,g))),e=1+e|0;a=M(a^c);break a}g=y;e=1+e|0}a=M(L(L(h,f),g))}}return a};
d.p=function(){return new Rd(this.Qa)};d.r=function(a){return this.Qa.a[a|0]};d.l=function(a){return this.Qa.a[a]};d.$classData=t({Wd:0},!1,"scala.collection.immutable.ArraySeq$ofLong",{Wd:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function Fb(a){this.gb=a}Fb.prototype=new Y;Fb.prototype.constructor=Fb;d=Fb.prototype;d.g=function(){return this.gb.a.length};d.l=function(a){return this.gb.a[a]};
d.m=function(){var a=N();a:{var b=this.gb;var c=a.C;z();a=Ia(La(),b);switch(a){case 0:b=M(c^0);break a;case 1:a=c;b=zb(z(),b,0);b=M(L(a,J(K(),b))^1);break a;default:var e=zb(z(),b,0),h=J(K(),e);e=c=L(c,h);var f=zb(z(),b,1);f=J(K(),f);var g=f-h|0;for(h=2;h<a;){c=L(c,f);var n=zb(z(),b,h);n=J(K(),n);if(g!==(n-f|0)){c=L(c,n);for(h=1+h|0;h<a;)e=zb(z(),b,h),c=L(c,J(K(),e)),h=1+h|0;b=M(c^a);break a}f=n;h=1+h|0}b=M(L(L(e,g),f))}}return b};d.p=function(){return V(new yd,this.gb)};
d.r=function(a){return this.l(a|0)};d.$classData=t({Xd:0},!1,"scala.collection.immutable.ArraySeq$ofRef",{Xd:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function Jd(a){this.Ra=a}Jd.prototype=new Y;Jd.prototype.constructor=Jd;d=Jd.prototype;d.g=function(){return this.Ra.a.length};
d.m=function(){var a=N();a:{var b=this.Ra;a=a.C;var c=b.a.length;switch(c){case 0:b=M(a^0);break a;case 1:b=M(L(a,b.a[0])^1);break a;default:var e=b.a[0],h=a=L(a,e),f=b.a[1];e=f-e|0;for(var g=2;g<c;){a=L(a,f);var n=b.a[g];if(e!==(n-f|0)){a=L(a,n);for(g=1+g|0;g<c;)a=L(a,b.a[g]),g=1+g|0;b=M(a^c);break a}f=n;g=1+g|0}b=M(L(L(h,e),f))}}return b};d.p=function(){return new Sd(this.Ra)};d.r=function(a){return this.Ra.a[a|0]};d.l=function(a){return this.Ra.a[a]};
d.$classData=t({Yd:0},!1,"scala.collection.immutable.ArraySeq$ofShort",{Yd:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function Ld(a){this.vb=a}Ld.prototype=new Y;Ld.prototype.constructor=Ld;d=Ld.prototype;d.g=function(){return this.vb.a.length};
d.m=function(){a:{var a=N().C;var b=this.vb.a.length;switch(b){case 0:a=M(a^0);break a;case 1:a=M(L(a,0)^1);break a;default:for(var c=a=L(a,0),e=0,h=e,f=2;f<b;){a=L(a,e);if(h!==(-e|0)){a=L(a,0);for(f=1+f|0;f<b;)a=L(a,0),f=1+f|0;a=M(a^b);break a}e=0;f=1+f|0}a=M(L(L(c,h),e))}}return a};d.p=function(){return new Td(this.vb)};d.r=function(){};d.l=function(){};
d.$classData=t({Zd:0},!1,"scala.collection.immutable.ArraySeq$ofUnit",{Zd:1,ga:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,fa:1,c:1});function ce(){}ce.prototype=new ne;ce.prototype.constructor=ce;function Ae(){}d=Ae.prototype=ce.prototype;d.p=function(){return new jd(this)};d.sa=function(){return"LinearSeq"};d.l=function(a){return id(this,a)};d.f=function(){return this===F()};
function E(a,b){if(b instanceof ce){if(a.f())a=b;else if(!b.f()){var c=new Z(b.q(),a),e=c;for(b=b.G();!b.f();){var h=new Z(b.q(),a);e=e.Ja=h;b=b.G()}a=c}return a}if(0===b.H())return a;c=b.p();if(c.t()){for(b=e=new Z(c.j(),a);c.t();)h=new Z(c.j(),a),b=b.Ja=h;return e}return a}d.g=function(){for(var a=this,b=0;!a.f();)b=1+b|0,a=a.G();return b};d.ra=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.f()?0:1;break a}if(b.f()){a=-1;break a}c=1+c|0;b=b.G()}return a};d.qa=function(){return"List"};
d.Ba=function(){return this};d.r=function(a){return id(this,a|0)};d.Lb=function(a){a:for(var b=this;;){if(0>=a||b.f())break a;a=-1+a|0;b=b.G()}return b};d.bb=function(a){if(this===F())a=F();else{for(var b=new Z(a.r(this.q()),F()),c=b,e=this.G();e!==F();){var h=new Z(a.r(e.q()),F());c=c.Ja=h;e=e.G()}a=b}return a};function Be(){this.Aa=null}Be.prototype=new ve;Be.prototype.constructor=Be;function Ce(){}Ce.prototype=Be.prototype;function ze(a){this.na=a}ze.prototype=new ye;ze.prototype.constructor=ze;
d=ze.prototype;d.g=function(){return this.na.a.length};d.Ea=function(a){return this.na.a[a]};d.m=function(){var a=N();return Ob(this.na,a.C)};d.p=function(){return new Nd(this.na)};
d.oa=function(a,b,c,e){var h=a.U;0!==b.length&&(h.d=""+h.d+b);b=this.na.a.length;if(0!==b)if(""===c){c=this.na;hc||(hc=new gc);b=0+c.a.length|0;if(0>b||b>c.a.length)throw new vd;for(var f="",g=0;g!==b;)f=""+f+String.fromCharCode(c.a[g]),g=1+g|0;h.d=""+h.d+f}else for(h.g(),f=String.fromCharCode(this.na.a[0]),h.d=""+h.d+f,f=1;f<b;)h.d=""+h.d+c,g=String.fromCharCode(this.na.a[f]),h.d=""+h.d+g,f=1+f|0;0!==e.length&&(h.d=""+h.d+e);return a};d.r=function(a){return new k(this.Ea(a|0))};d.l=function(a){return new k(this.Ea(a))};
d.$classData=t({te:0},!1,"scala.collection.mutable.ArraySeq$ofChar",{te:1,qf:1,se:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,ye:1,xe:1,ze:1,ue:1,$a:1,ve:1,I:1,J:1,we:1,L:1,K:1,c:1});function we(){this.Aa=null;this.wb=0}we.prototype=new Ce;we.prototype.constructor=we;function De(){}De.prototype=we.prototype;function Z(a,b){this.bc=a;this.Ja=b}Z.prototype=new Ae;Z.prototype.constructor=Z;d=Z.prototype;d.q=function(){return this.bc};d.$=function(){return"::"};d.Y=function(){return 2};
d.Z=function(a){switch(a){case 0:return this.bc;case 1:return this.Ja;default:throw K(),S(new T,""+a);}};d.ja=function(){return new fd(this)};d.G=function(){return this.Ja};d.$classData=t({Od:0},!1,"scala.collection.immutable.$colon$colon",{Od:1,je:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,fc:1,Zb:1,$b:1,gc:1,Ld:1,L:1,K:1,T:1,ac:1,c:1,ka:1});function Ee(){Ge=this;F();F()}Ee.prototype=new Ae;Ee.prototype.constructor=Ee;d=Ee.prototype;
d.pb=function(){throw new Gc("head of empty list");};d.H=function(){return 0};d.p=function(){return vb().xa};d.$=function(){return"Nil"};d.Y=function(){return 0};d.Z=function(a){K();throw S(new T,""+a);};d.ja=function(){return new fd(this)};d.G=function(){throw new Hc("tail of empty list");};d.q=function(){this.pb()};
d.$classData=t({ne:0},!1,"scala.collection.immutable.Nil$",{ne:1,je:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,fc:1,Zb:1,$b:1,gc:1,Ld:1,L:1,K:1,T:1,ac:1,c:1,ka:1});var Ge;function F(){Ge||(Ge=new Ee);return Ge}function He(){this.Aa=null;this.wb=0;var a=mb().jc;mb();this.wb=0;this.Aa=a}He.prototype=new De;He.prototype.constructor=He;function Ie(a){return S(new T,a+" is out of bounds (empty vector)")}He.prototype.bb=function(){return this};
He.prototype.r=function(a){throw Ie(a|0);};He.prototype.l=function(a){throw Ie(a);};He.prototype.$classData=t({qe:0},!1,"scala.collection.immutable.Vector0$",{qe:1,nf:1,pf:1,of:1,M:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,O:1,N:1,P:1,ba:1,I:1,J:1,ca:1,T:1,L:1,K:1,ac:1,c:1});var Je;function qd(){Je||(Je=new He);return Je}function gb(){this.U=null}gb.prototype=new pe;gb.prototype.constructor=gb;d=gb.prototype;d.sa=function(){return"IndexedSeq"};d.p=function(){var a=new le(this);return new zd(a)};
d.ra=function(a){var b=this.U.g();return b===a?0:b<a?-1:1};d.g=function(){return this.U.g()};d.H=function(){return this.U.g()};d.n=function(){return this.U.d};d.f=function(){return 0===this.U.g()};d.r=function(a){return new k(this.U.d.charCodeAt(a|0))};d.l=function(a){return new k(this.U.d.charCodeAt(a))};
d.$classData=t({Ae:0},!1,"scala.collection.mutable.StringBuilder",{Ae:1,se:1,E:1,v:1,b:1,w:1,h:1,y:1,i:1,x:1,F:1,B:1,u:1,A:1,o:1,ye:1,xe:1,ze:1,ue:1,$a:1,uf:1,rf:1,tf:1,sf:1,ve:1,I:1,J:1,we:1,Qc:1,c:1});ba=new l(0,0);xa.lc=ba;var uc=null;mdoc_js_run2=function(){ab();x();z();x();var a=A(0,new (v(Ua).k)([Xa("This is some text.")]));C();D();E(F(),a)};mdoc_js_run4=function(){ab();Wa(x().Ca,"my-container")};
mdoc_js_run8=function(){ab();x();var a=A(z(),new (v(Va).k)([Wa(x().Ca,"an-id")]));C();D();E(F(),a);C();a=A(z(),new (v(rd).k)([Wa(x().Ca,"an-id")]));E(F(),a);C();x();Sa();x();Qc||(Qc=new Pc);x();Sa();Ra("width","100px");ud();x()};mdoc_js_run6=function(){ab()};mdoc_js_run3=function(){ab();x();Xa("some text");x();var a=A(z(),new (v(Ua).k)([(x(),new B("some text"))]));C();D();E(F(),a)};
mdoc_js_run1=function(){ab();x();var a=A(z(),new (v(Va).k)([Wa(x().Jb,"green-box")]));z();x();var b=A(0,new (v(Ua).k)([Xa("This is some text.")]));D();E(F(),a);D();E(F(),b)};mdoc_js_run5=function(){ab();x();z();x();var a=Ra("font-weight","bold");Sa();A(0,new (v(Va).k)([new Ta("style",a)])).Ba();C();a=A(z(),new (v($a).k)([(x(),new B("Hello"))]));E(F(),a)};mdoc_js_run7=function(){ab()};
}).call(this);
