let mdoc_js_run0;
(function(){
'use strict';var f,aa=Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.11.0",fileLevelThis:this}),ba;function ca(a){for(var b in a)return b}function da(a){this.nb=a}da.prototype.toString=function(){return String.fromCharCode(this.nb)};
function ea(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"number"!==typeof a||a===a&&Math.fround(a)!==a?"java.lang.Double":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.zd():a instanceof k?"java.lang.Long":a instanceof da?"java.lang.Character":a&&a.$classData?a.$classData.name:
null.Ad()}}function fa(a){switch(typeof a){case "string":return l(a);case "number":return ha(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.o():a instanceof k?a.aa^a.$:a instanceof da?null===a?0:a.nb:m.prototype.o.call(a)}}var ia=0,ja=new WeakMap;
function ka(a){switch(typeof a){case "string":return l(a);case "number":return ha(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:l(a);default:if(null===a)return 0;b=ja.get(a);void 0===b&&(ia=b=ia+1|0,ja.set(a,b));return b}}function m(){}m.prototype.constructor=m;function p(){}p.prototype=m.prototype;m.prototype.o=function(){return ka(this)};
m.prototype.h=function(){var a=this.o();return ea(this)+"@"+(+(a>>>0)).toString(16)};m.prototype.toString=function(){return this.h()};function q(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=null}else this.c=a}q.prototype=new p;q.prototype.constructor=q;function la(){}la.prototype=q.prototype;function ma(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=!1}else this.c=a}ma.prototype=new p;ma.prototype.constructor=ma;
function na(a){this.c="number"===typeof a?new Uint16Array(a):a}na.prototype=new p;na.prototype.constructor=na;function oa(a){this.c="number"===typeof a?new Int8Array(a):a}oa.prototype=new p;oa.prototype.constructor=oa;function pa(a){this.c="number"===typeof a?new Int16Array(a):a}pa.prototype=new p;pa.prototype.constructor=pa;function t(a){this.c="number"===typeof a?new Int32Array(a):a}t.prototype=new p;t.prototype.constructor=t;
function qa(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=ba}else this.c=a}qa.prototype=new p;qa.prototype.constructor=qa;function ra(a){this.c="number"===typeof a?new Float32Array(a):a}ra.prototype=new p;ra.prototype.constructor=ra;function sa(a){this.c="number"===typeof a?new Float64Array(a):a}sa.prototype=new p;sa.prototype.constructor=sa;
function ua(){this.p=void 0;this.ca=this.w=null;this.da=0;this.Qb=null;this.E="";this.L=this.ba=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function u(a,b,c,d){var g=new ua;g.w={};g.Qb=a;g.E=b;g.L=e=>e===g;g.name=c;g.isPrimitive=!0;g.isInstance=()=>!1;void 0!==d&&(g.ba=va(g,d));return g}
function v(a,b,c,d){var g=new ua,e=ca(a);g.w=d;g.E="L"+c+";";g.L=h=>!!h.w[e];g.name=c;g.isInterface=b;g.isInstance=h=>!!(h&&h.$classData&&h.$classData.w[e]);return g}function va(a,b,c){var d=new ua;b.prototype.$classData=d;var g="["+a.E;d.p=b;d.w={a:1,Oa:1,d:1};d.ca=a;d.da=1;d.E=g;d.name=g;d.isArrayClass=!0;d.L=c||(e=>d===e);d.isInstance=e=>e instanceof b;return d}
function wa(a){function b(h){if("number"===typeof h){this.c=Array(h);for(var n=0;n<h;n++)this.c[n]=null}else this.c=h}var c=new ua;b.prototype=new la;b.prototype.constructor=b;var d=a.ca||a,g=a.da+1;b.prototype.$classData=c;a="["+a.E;c.p=b;c.w={a:1,Oa:1,d:1};c.ca=d;c.da=g;c.E=a;c.name=a;c.isArrayClass=!0;var e=h=>{var n=h.da;return n===g?d.L(h.ca):n>g&&d===w};c.L=e;c.isInstance=h=>{h=h&&h.$classData;return!!h&&(h===c||e(h))};return c}function x(a){a.ba||(a.ba=wa(a));return a.ba}var w=new ua;w.w={a:1};
w.E="Ljava.lang.Object;";w.L=a=>!a.isPrimitive;w.name="java.lang.Object";w.isInstance=a=>null!==a;w.ba=va(w,q,a=>{var b=a.da;return 1===b?!a.ca.isPrimitive:1<b});m.prototype.$classData=w;u(void 0,"V","void",void 0);u(!1,"Z","boolean",ma);u(0,"C","char",na);u(0,"B","byte",oa);u(0,"S","short",pa);u(0,"I","int",t);var xa=u(null,"J","long",qa);u(0,"F","float",ra);u(0,"D","double",sa);
function ya(){this.qb=this.xa=this.ea=null;za=this;this.ea=new ArrayBuffer(8);this.xa=new Int32Array(this.ea,0,2);new Float32Array(this.ea,0,2);this.qb=new Float64Array(this.ea,0,1);this.xa[0]=16909060;new Int8Array(this.ea,0,8)}ya.prototype=new p;ya.prototype.constructor=ya;function Aa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.qb[0]=b;return(a.xa[0]|0)^(a.xa[1]|0)}ya.prototype.$classData=v({nc:0},!1,"java.lang.FloatingPointBits$",{nc:1,a:1});var za;
function Ba(){za||(za=new ya);return za}
function Ca(){this.sb=this.Pa=null;Da=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.Pa=a;this.sb=null}Ca.prototype=new p;Ca.prototype.constructor=Ca;function Ea(a,b,c){return null!==a.Pa?(a=a.Pa,Fa||(Fa=new Ga),Fa.ub.call(a,b)?a[b]:c):Ea(a.sb,b,c)}Ca.prototype.$classData=v({tc:0},!1,"java.lang.System$SystemProperties$",{tc:1,a:1});var Da;function Ga(){this.ub=null;Fa=this;this.ub=Object.prototype.hasOwnProperty}Ga.prototype=new p;Ga.prototype.constructor=Ga;Ga.prototype.$classData=v({vc:0},!1,"java.lang.Utils$Cache$",{vc:1,a:1});var Fa;function Ha(){}Ha.prototype=new p;
Ha.prototype.constructor=Ha;function Ia(a,b){if(b instanceof q||b instanceof ma||b instanceof na||b instanceof oa||b instanceof pa||b instanceof t||b instanceof qa||b instanceof ra||b instanceof sa)return b.c.length;a=new Ja;y(a,"argument type mismatch");throw a;}Ha.prototype.$classData=v({wc:0},!1,"java.lang.reflect.Array$",{wc:1,a:1});var Ka;function La(){Ka||(Ka=new Ha);return Ka}function Ma(){}Ma.prototype=new p;Ma.prototype.constructor=Ma;
Ma.prototype.$classData=v({xc:0},!1,"java.util.Arrays$",{xc:1,a:1});var Na;function Oa(){}Oa.prototype=new p;Oa.prototype.constructor=Oa;Oa.prototype.$classData=v({Rb:0},!1,"mdocjs$",{Rb:1,a:1});var Pa;function k(a,b){this.aa=a;this.$=b}k.prototype=new p;k.prototype.constructor=k;k.prototype.o=function(){return this.aa^this.$};k.prototype.h=function(){Qa();var a=this.aa,b=this.$;return b===a>>31?""+a:0>b?"-"+Ra(-a|0,0!==a?~b:-b|0):Ra(a,b)};
k.prototype.$classData=v({jc:0},!1,"org.scalajs.linker.runtime.RuntimeLong",{jc:1,a:1});
function Ra(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+Math.clz32(1E9)|0)-(0!==b?Math.clz32(b):32+Math.clz32(a)|0)|0,d=c,g=0===(32&d)?1E9<<d:0;d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d;var e=a,h=b;for(a=b=0;0<=c&&0!==(-2097152&h);){var n=e,r=h,K=g,ta=d;if(r===ta?(-2147483648^n)>=(-2147483648^K):(-2147483648^r)>=(-2147483648^ta))n=h,r=d,h=e-g|0,n=(-2147483648^h)>(-2147483648^e)?-1+(n-r|0)|0:n-r|0,e=h,h=n,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;n=d>>>1|0;g=g>>>1|0|d<<31;d=n}c=h;if(0===
c?-1147483648<=(-2147483648^e):-2147483648<=(-2147483648^c))c=4294967296*h+ +(e>>>0),e=c/1E9,g=e/4294967296|0,d=b,b=e=d+(e|0)|0,a=(-2147483648^e)<(-2147483648^d)?1+(a+g|0)|0:a+g|0,e=c%1E9|0;c=""+e;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length)+c}return b}function Sa(){this.ua=0}Sa.prototype=new p;Sa.prototype.constructor=Sa;Sa.prototype.$classData=v({kc:0},!1,"org.scalajs.linker.runtime.RuntimeLong$",{kc:1,a:1});var Ta;function Qa(){Ta||(Ta=new Sa);return Ta}
function Ua(a,b,c,d){if(a.e())a=""+b+d;else{var g=a.va,e=new Va;e.u=Wa(new z);a=g.call(a,e,b,c,d).u.b}return a}function Xa(a,b,c,d,g){var e=b.u;0!==c.length&&(e.b=""+e.b+c);a=a.q();if(a.k())for(c=a.j(),e.b=""+e.b+c;a.k();)e.b=""+e.b+d,c=a.j(),e.b=""+e.b+c;0!==g.length&&(e.b=""+e.b+g);return b}function Ya(){this.Ob=null;Za=this;this.Ob=new q(0);new (x(x(w)).p)(0);new (x(x(x(w))).p)(0);new (x(x(x(x(w)))).p)(0);new (x(x(x(x(x(w))))).p)(0);new (x(x(x(x(x(x(w)))))).p)(0)}Ya.prototype=new p;
Ya.prototype.constructor=Ya;Ya.prototype.$classData=v({kd:0},!1,"scala.collection.immutable.VectorStatics$",{kd:1,a:1});var Za;function $a(){Za||(Za=new Ya);return Za}function ab(){this.ia=null;bb=this;cb||(cb=new db);cb||(cb=new db);eb||(eb=new fb);gb||(gb=new hb);ib();A();this.ia=B();jb();kb()}ab.prototype=new p;ab.prototype.constructor=ab;ab.prototype.$classData=v({Cc:0},!1,"scala.package$",{Cc:1,a:1});var bb;function lb(){bb||(bb=new ab);return bb}function mb(){}mb.prototype=new p;
mb.prototype.constructor=mb;function nb(a,b,c){if(b instanceof q||b instanceof t||b instanceof sa||b instanceof qa||b instanceof ra)return b.c[c];if(b instanceof na)return new da(b.c[c]);if(b instanceof oa||b instanceof pa||b instanceof ma)return b.c[c];if(null===b)throw new C;throw new ob(b);}function pb(a){D();var b=a.N();return Ua(b,a.B()+"(",",",")")}
function qb(a,b){return null===b?null:0===b.c.length?(rb||(rb=new sb),a=rb,tb||(tb=new ub),a.Ya||a.Ya||(a.Gb=new vb(new q(0)),a.Ya=!0),a.Gb):new vb(b)}mb.prototype.$classData=v({sd:0},!1,"scala.runtime.ScalaRunTime$",{sd:1,a:1});var wb;function D(){wb||(wb=new mb);return wb}function xb(){}xb.prototype=new p;xb.prototype.constructor=xb;
function E(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=Qa();if(-0x7fffffffffffffff>a){b.ua=-2147483648;var c=0}else if(0x7fffffffffffffff<=a)b.ua=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.ua=0>a&&0!==c?-1+d|0:d}b=b.ua;Qa();a=(0>b?-(4294967296*+((0!==c?~b:-b|0)>>>0)+ +((-c|0)>>>0)):4294967296*b+ +(c>>>0))===a?c^b:Aa(Ba(),a)}return a}return b instanceof k?(a=null===b?ba:b,b=new k(a.aa,a.$),a=b.aa,b=b.$,b===
a>>31?a:a^b):fa(b)}xb.prototype.$classData=v({vd:0},!1,"scala.runtime.Statics$",{vd:1,a:1});var yb;function F(){yb||(yb=new xb);return yb}function zb(){}zb.prototype=new p;zb.prototype.constructor=zb;function Ab(){}Ab.prototype=zb.prototype;function G(a,b){a=Bb(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function Bb(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}
function H(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function Cb(a){Db();var b=a.z();if(0===b)return l(a.B());var c=G(-889275714,l(a.B()));for(var d=0;d<b;){var g=a.A(d);c=G(c,E(F(),g));d=1+d|0}return H(c^b)}var Eb=v({Ja:0},!0,"tyrian.Attr",{Ja:1,a:1}),Fb=v({Ka:0},!0,"tyrian.Elem",{Ka:1,a:1});function I(a){if(null===a)throw new C;}I.prototype=new p;I.prototype.constructor=I;
I.prototype.$classData=v({Xb:0},!1,"tyrian.HtmlAttributes$AttributeNameBoolean",{Xb:1,a:1});function Gb(a){if(null===a)throw new C;}Gb.prototype=new p;Gb.prototype.constructor=Gb;Gb.prototype.$classData=v({Yb:0},!1,"tyrian.HtmlAttributes$AttributeNameDouble",{Yb:1,a:1});function J(a){if(null===a)throw new C;}J.prototype=new p;J.prototype.constructor=J;J.prototype.$classData=v({Zb:0},!1,"tyrian.HtmlAttributes$AttributeNameInt",{Zb:1,a:1});function L(a){if(null===a)throw new C;}L.prototype=new p;
L.prototype.constructor=L;L.prototype.$classData=v({$b:0},!1,"tyrian.HtmlAttributes$AttributeNameString",{$b:1,a:1});function Hb(a){if(null===a)throw new C;}Hb.prototype=new p;Hb.prototype.constructor=Hb;Hb.prototype.$classData=v({ac:0},!1,"tyrian.HtmlAttributes$AttributeNameStyle",{ac:1,a:1});function Ib(a){if(null===a)throw new C;}Ib.prototype=new p;Ib.prototype.constructor=Ib;Ib.prototype.$classData=v({bc:0},!1,"tyrian.HtmlAttributes$PropertyNameBoolean",{bc:1,a:1});
function Jb(a){if(null===a)throw new C;}Jb.prototype=new p;Jb.prototype.constructor=Jb;Jb.prototype.$classData=v({cc:0},!1,"tyrian.HtmlAttributes$PropertyNameDouble",{cc:1,a:1});function Kb(a){if(null===a)throw new C;}Kb.prototype=new p;Kb.prototype.constructor=Kb;Kb.prototype.$classData=v({dc:0},!1,"tyrian.HtmlAttributes$PropertyNameString",{dc:1,a:1});function Lb(){Mb=this;Nb("","")}Lb.prototype=new p;Lb.prototype.constructor=Lb;
function Nb(a,b){Mb||(Mb=new Lb);return""===a?""===b?"":Ob(b)?b:b+";":""===b?Ob(a)?a:a+";":a+":"+b+";"}Lb.prototype.$classData=v({ec:0},!1,"tyrian.Style$package$Style$",{ec:1,a:1});var Mb;function Pb(){this.mb=null;Qb=this;this.mb=new Rb(a=>""===a?a:" "+a)}Pb.prototype=new p;Pb.prototype.constructor=Pb;
function Sb(a,b){if(b instanceof M){var c=a.mb,d=b.jb;if(d===B())var g=B();else{g=d.f();var e=g=new N(Tb(g),B());for(d=d.g();d!==B();){var h=d.f();h=new N(Tb(h),B());e=e.x=h;d=d.g()}}e=g;a:for(;;)if(e.e()){g=B();break}else if(d=e.f(),g=e.g(),""===d===!0)e=g;else for(;;){if(g.e())g=e;else{if(""===g.f()!==!0){g=g.g();continue}d=g;g=new N(e.f(),B());h=e.g();for(e=g;h!==d;){var n=new N(h.f(),B());e=e.x=n;h=h.g()}for(h=d=d.g();!d.e();){if(""===d.f()===!0){for(;h!==d;)n=new N(h.f(),B()),e=e.x=n,h=h.g();
h=d.g()}d=d.g()}h.e()||(e.x=h)}break a}c=c.J(Ua(g,""," ",""));h=b.kb;g=r=>{if(r instanceof O)return r.lb;if(r&&r.$classData&&r.$classData.w.Vb)return Sb(a,r);throw new ob(r);};if(h===B())g=B();else{e=h.f();d=e=new N(g(e),B());for(h=h.g();h!==B();)n=h.f(),n=new N(g(n),B()),d=d.x=n,h=h.g();g=e}g=Ua(g,"","","");return"\x3c"+b.La+c+"\x3e"+g+"\x3c/"+b.La+"\x3e"}throw new ob(b);}function Tb(a){if(a instanceof Ub)return a.hb+'\x3d"'+a.ib+'"';Vb||(Vb=new Wb);if(a===Vb)return"";throw new ob(a);}
Pb.prototype.$classData=v({hc:0},!1,"tyrian.runtime.Render$",{hc:1,a:1});var Qb;function Zb(){}Zb.prototype=new p;Zb.prototype.constructor=Zb;Zb.prototype.$classData=v({ic:0},!1,"tyrian.runtime.TyrianSSR$",{ic:1,a:1});var $b;
function ac(a){0===(32&a.wa)<<24>>24&&0===(32&a.wa)<<24>>24&&(a.pb=new t(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.wa=(32|a.wa)<<24>>24);return a.pb}function bc(){this.pb=null;this.wa=0}bc.prototype=new p;bc.prototype.constructor=bc;
bc.prototype.$classData=v({mc:0},!1,"java.lang.Character$",{mc:1,a:1,d:1});var cc;function dc(a){throw new ec('For input string: "'+a+'"');}function fc(){}fc.prototype=new p;fc.prototype.constructor=fc;fc.prototype.$classData=v({pc:0},!1,"java.lang.Integer$",{pc:1,a:1,d:1});var gc;function y(a,b){a.tb=b;"[object Error]"!==Object.prototype.toString.call(a)&&(void 0===Error.captureStackTrace?Error():Error.captureStackTrace(a))}
class hc extends Error{constructor(){super();this.tb=null}Ma(){return this.tb}h(){var a=ea(this),b=this.Ma();return null===b?a:a+": "+b}o(){return m.prototype.o.call(this)}get message(){var a=this.Ma();return null===a?"":a}get name(){return ea(this)}toString(){return this.h()}}function ic(){}ic.prototype=new p;ic.prototype.constructor=ic;function jc(){}jc.prototype=ic.prototype;ic.prototype.h=function(){return"\x3cfunction0\x3e"};function kc(){}kc.prototype=new p;kc.prototype.constructor=kc;
function lc(){}lc.prototype=kc.prototype;kc.prototype.h=function(){return"\x3cfunction1\x3e"};function mc(a){this.fb=a}mc.prototype=new p;mc.prototype.constructor=mc;mc.prototype.h=function(){return""+this.fb};mc.prototype.$classData=v({qd:0},!1,"scala.runtime.IntRef",{qd:1,a:1,d:1});function nc(a){this.gb=a}nc.prototype=new p;nc.prototype.constructor=nc;nc.prototype.h=function(){return""+this.gb};nc.prototype.$classData=v({rd:0},!1,"scala.runtime.ObjectRef",{rd:1,a:1,d:1});
function oc(){this.Ab=this.ja=0;pc=this;this.ja=l("Seq");this.Ab=l("Map");l("Set");var a=lb().ia,b=this.Ab,c=0,d=0,g=0,e=1;for(a=a.q();a.k();){var h=a.j();h=E(F(),h);c=c+h|0;d^=h;e=Math.imul(e,1|h);g=1+g|0}b=G(b,c);b=G(b,d);b=Bb(b,e);H(b^g)}oc.prototype=new Ab;oc.prototype.constructor=oc;oc.prototype.$classData=v({Ec:0},!1,"scala.util.hashing.MurmurHash3$",{Ec:1,Kd:1,a:1});var pc;function Db(){pc||(pc=new oc);return pc}class qc extends hc{}function rc(){}rc.prototype=new p;
rc.prototype.constructor=rc;function sc(){}sc.prototype=rc.prototype;function tc(){}tc.prototype=new p;tc.prototype.constructor=tc;function uc(){}uc.prototype=tc.prototype;function vc(){this.U=null;wc=this;this.U=new P}vc.prototype=new p;vc.prototype.constructor=vc;vc.prototype.$classData=v({Mc:0},!1,"scala.collection.Iterator$",{Mc:1,a:1,C:1,d:1});var wc;function ib(){wc||(wc=new vc);return wc}function xc(){}xc.prototype=new p;xc.prototype.constructor=xc;
xc.prototype.Na=function(){throw new yc("head of empty lazy list");};function Q(){throw new zc("tail of empty lazy list");}xc.prototype.f=function(){this.Na()};xc.prototype.$classData=v({bd:0},!1,"scala.collection.immutable.LazyList$State$Empty$",{bd:1,a:1,Zd:1,d:1});var Ac;function Bc(){Ac||(Ac=new xc);return Ac}function Cc(a){this.nd=a}Cc.prototype=new jc;Cc.prototype.constructor=Cc;Cc.prototype.$classData=v({md:0},!1,"scala.scalajs.runtime.AnonFunction0",{md:1,me:1,a:1,wd:1});
function Rb(a){this.pd=a}Rb.prototype=new lc;Rb.prototype.constructor=Rb;Rb.prototype.J=function(a){return(0,this.pd)(a)};Rb.prototype.$classData=v({od:0},!1,"scala.scalajs.runtime.AnonFunction1",{od:1,ne:1,a:1,I:1});function Dc(){(Ec=this)||(Ec=new Dc)}Dc.prototype=new p;Dc.prototype.constructor=Dc;Dc.prototype.h=function(){return"Attribute"};Dc.prototype.$classData=v({Tb:0},!1,"tyrian.Attribute$",{Tb:1,a:1,yb:1,Bc:1});var Ec;class R extends qc{}
R.prototype.$classData=v({y:0},!1,"java.lang.RuntimeException",{y:1,F:1,G:1,a:1,d:1});function Wa(a){a.b="";return a}function z(){this.b=null}z.prototype=new p;z.prototype.constructor=z;z.prototype.h=function(){return this.b};z.prototype.i=function(){return this.b.length};z.prototype.$classData=v({sc:0},!1,"java.lang.StringBuilder",{sc:1,a:1,lc:1,Bd:1,d:1});function Fc(){}Fc.prototype=new p;Fc.prototype.constructor=Fc;function S(){}f=S.prototype=Fc.prototype;f.q=function(){return this};f.e=function(){return!this.k()};
f.h=function(){return"\x3citerator\x3e"};f.va=function(a,b,c,d){return Xa(this,a,b,c,d)};f.r=function(){return-1};function db(){Gc||(Gc=new Hc)}db.prototype=new uc;db.prototype.constructor=db;db.prototype.$classData=v({Kc:0},!1,"scala.collection.Iterable$",{Kc:1,Lc:1,a:1,C:1,d:1});var cb;function Ic(){}Ic.prototype=new p;Ic.prototype.constructor=Ic;function Jc(){}Jc.prototype=Ic.prototype;function Hc(){A()}Hc.prototype=new uc;Hc.prototype.constructor=Hc;
Hc.prototype.$classData=v({Yc:0},!1,"scala.collection.immutable.Iterable$",{Yc:1,Lc:1,a:1,C:1,d:1});var Gc;function Kc(){this.Hb=null;Lc=this;this.Hb=Mc(new Nc(new Cc(()=>Bc())))}Kc.prototype=new p;Kc.prototype.constructor=Kc;function Oc(a,b,c){var d=new nc(b),g=new mc(c);return new Nc(new Cc(()=>{for(var e=d.gb,h=g.fb;0<h&&!e.e();)e=Q(T(e)),d.gb=e,h=-1+h|0,g.fb=h;return T(e)}))}Kc.prototype.$classData=v({$c:0},!1,"scala.collection.immutable.LazyList$",{$c:1,a:1,na:1,C:1,d:1});var Lc;
function jb(){Lc||(Lc=new Kc);return Lc}class Ja extends R{}Ja.prototype.$classData=v({rb:0},!1,"java.lang.IllegalArgumentException",{rb:1,y:1,F:1,G:1,a:1,d:1});class U extends R{constructor(a){super();y(this,a)}}U.prototype.$classData=v({oc:0},!1,"java.lang.IndexOutOfBoundsException",{oc:1,y:1,F:1,G:1,a:1,d:1});class C extends R{constructor(){super();y(this,null)}}C.prototype.$classData=v({qc:0},!1,"java.lang.NullPointerException",{qc:1,y:1,F:1,G:1,a:1,d:1});
class zc extends R{constructor(a){super();y(this,a)}}zc.prototype.$classData=v({uc:0},!1,"java.lang.UnsupportedOperationException",{uc:1,y:1,F:1,G:1,a:1,d:1});class yc extends R{constructor(a){super();y(this,a)}}yc.prototype.$classData=v({yc:0},!1,"java.util.NoSuchElementException",{yc:1,y:1,F:1,G:1,a:1,d:1});
class ob extends R{constructor(a){super();this.vb=null;this.Qa=!1;this.ya=a;y(this,null)}Ma(){if(!this.Qa&&!this.Qa){if(null===this.ya)var a="null";else try{var b=this.ya;a=(void 0===b?"undefined":b.toString())+" (of class "+ea(this.ya)+")"}catch(c){a="an instance of class "+ea(this.ya)}this.vb=a;this.Qa=!0}return this.vb}}ob.prototype.$classData=v({zc:0},!1,"scala.MatchError",{zc:1,y:1,F:1,G:1,a:1,d:1});
function V(a){this.xb=this.ha=0;this.wb=null;if(null===a)throw null;this.wb=a;this.ha=0;this.xb=a.z()}V.prototype=new S;V.prototype.constructor=V;V.prototype.k=function(){return this.ha<this.xb};V.prototype.j=function(){var a=this.wb.A(this.ha);this.ha=1+this.ha|0;return a};V.prototype.$classData=v({Ac:0},!1,"scala.Product$$anon$1",{Ac:1,P:1,a:1,H:1,l:1,m:1});function Pc(){}Pc.prototype=new sc;Pc.prototype.constructor=Pc;
Pc.prototype.$classData=v({Gc:0},!1,"scala.collection.ClassTagSeqFactory$AnySeqDelegate",{Gc:1,Od:1,a:1,C:1,d:1,na:1});function P(){}P.prototype=new S;P.prototype.constructor=P;P.prototype.k=function(){return!1};P.prototype.r=function(){return 0};P.prototype.j=function(){throw new yc("next on empty iterator");};P.prototype.$classData=v({Nc:0},!1,"scala.collection.Iterator$$anon$19",{Nc:1,P:1,a:1,H:1,l:1,m:1});
function Qc(a,b){if(0>b)throw new U(""+b);a=a.ob(b);if(a.e())throw new U(""+b);return a.f()}function Rc(a){this.Aa=a}Rc.prototype=new S;Rc.prototype.constructor=Rc;Rc.prototype.k=function(){return!this.Aa.e()};Rc.prototype.j=function(){var a=this.Aa.f();this.Aa=this.Aa.g();return a};Rc.prototype.$classData=v({Qc:0},!1,"scala.collection.StrictOptimizedLinearSeqOps$$anon$1",{Qc:1,P:1,a:1,H:1,l:1,m:1});function hb(){kb()}hb.prototype=new Jc;hb.prototype.constructor=hb;
hb.prototype.$classData=v({Wc:0},!1,"scala.collection.immutable.IndexedSeq$",{Wc:1,Oc:1,a:1,na:1,C:1,d:1});var gb;function Sc(a){this.oa=a}Sc.prototype=new S;Sc.prototype.constructor=Sc;Sc.prototype.k=function(){return!this.oa.e()};Sc.prototype.j=function(){if(this.oa.e())return ib().U.j();var a=T(this.oa).f();this.oa=Q(T(this.oa));return a};Sc.prototype.$classData=v({ad:0},!1,"scala.collection.immutable.LazyList$LazyIterator",{ad:1,P:1,a:1,H:1,l:1,m:1});function Tc(){Uc=this;B();B()}
Tc.prototype=new p;Tc.prototype.constructor=Tc;Tc.prototype.$classData=v({dd:0},!1,"scala.collection.immutable.List$",{dd:1,a:1,Rc:1,na:1,C:1,d:1});var Uc;function A(){Uc||(Uc=new Tc)}function Vc(a,b,c){this.Mb=this.Ea=this.ra=this.qa=this.pa=null;this.Fa=b;this.fd=c;this.W=a.Y;this.bb=this.W.c.length;this.cb=this.t=0;this.D=this.Fa;this.ta=0;this.X=1;this.db=0;this.sa=this.bb}Vc.prototype=new p;Vc.prototype.constructor=Vc;f=Vc.prototype;f.q=function(){return this};f.e=function(){return this.D<=this.t};
f.h=function(){return"\x3citerator\x3e"};f.va=function(a,b,c,d){return Xa(this,a,b,c,d)};f.r=function(){return this.D-this.t|0};f.k=function(){return this.D>this.t};
f.j=function(){if(this.t===this.bb){var a=(this.t-this.D|0)+this.Fa|0;if(a===this.sa){this.D<=this.t&&ib().U.j();this.ta=1+this.ta|0;for(var b=null;0===b.c.length;)this.ta=1+this.ta|0,b=null;this.db=this.sa;var c=this.fd/2|0,d=this.ta-c|0;c=this.X=(1+c|0)-(0>d?-d|0:d)|0;switch(c){case 1:this.W=b;break;case 2:this.pa=b;break;case 3:this.qa=b;break;case 4:this.ra=b;break;case 5:this.Ea=b;break;case 6:this.Mb=b;break;default:throw new ob(c);}this.sa=this.db+Math.imul(b.c.length,1<<Math.imul(5,-1+this.X|
0))|0;this.sa>this.Fa&&(this.sa=this.Fa);1<this.X&&(this.cb=-1+(1<<Math.imul(5,this.X))|0)}1<this.X&&(a=a-this.db|0,b=this.cb^a,1024>b?this.W=this.pa.c[31&(a>>>5|0)]:(32768>b?this.pa=this.qa.c[31&(a>>>10|0)]:(1048576>b?this.qa=this.ra.c[31&(a>>>15|0)]:(33554432>b?this.ra=this.Ea.c[31&(a>>>20|0)]:(this.Ea=this.Mb.c[a>>>25|0],this.ra=this.Ea.c[0]),this.qa=this.ra.c[0]),this.pa=this.qa.c[0]),this.W=this.pa.c[0]),this.cb=a);this.D=this.D-this.t|0;a=this.W.c.length;b=this.D;this.bb=a<b?a:b;this.t=0}a=
this.W.c[this.t];this.t=1+this.t|0;return a};f.$classData=v({ed:0},!1,"scala.collection.immutable.NewVectorIterator",{ed:1,a:1,H:1,l:1,m:1,Oa:1});function fb(){A()}fb.prototype=new Jc;fb.prototype.constructor=fb;fb.prototype.$classData=v({hd:0},!1,"scala.collection.immutable.Seq$",{hd:1,Oc:1,a:1,na:1,C:1,d:1});var eb;
function Wc(){this.Nb=null;Xc=this;try{var a=Ea;Da||(Da=new Ca);var b=a(Da,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250");gc||(gc=new fc);var c=null===b?0:b.length;0===c&&dc(b);var d=b.charCodeAt(0),g=45===d;a=g?2147483648:2147483647;d=g||43===d?1:0;d>=b.length&&dc(b);for(g=0;d!==c;){cc||(cc=new bc);var e=cc,h=b.charCodeAt(d);if(256>h)var n=48<=h&&57>=h?-48+h|0:65<=h&&90>=h?-55+h|0:97<=h&&122>=h?-87+h|0:-1;else if(65313<=h&&65338>=h)n=-65303+h|0;else if(65345<=h&&65370>=
h)n=-65335+h|0;else{Na||(Na=new Ma);b:for(var r=ac(e),K=0,ta=r.c.length;;){if(K===ta){var Xb=-1-K|0;break b}var Yb=(K+ta|0)>>>1|0,od=r.c[Yb],pd=h===od?0:h<od?-1:1;if(0>pd)ta=Yb;else{if(0===pd){Xb=Yb;break b}K=1+Yb|0}}K=0>Xb?-2-Xb|0:Xb;if(0>K)n=-1;else{var qd=h-ac(e).c[K]|0;n=9<qd?-1:qd}}var rd=10>n?n:-1;g=10*g+rd;(-1===rd||g>a)&&dc(b);d=1+d|0}}catch(Pd){throw Pd;}this.Nb=new Vc(Yc(),0,0)}Wc.prototype=new p;Wc.prototype.constructor=Wc;
Wc.prototype.$classData=v({id:0},!1,"scala.collection.immutable.Vector$",{id:1,a:1,Rc:1,na:1,C:1,d:1});var Xc;function kb(){Xc||(Xc=new Wc);return Xc}function W(a){this.Pb=0;this.ud=a;this.Ia=0;this.Pb=a.z()}W.prototype=new S;W.prototype.constructor=W;W.prototype.k=function(){return this.Ia<this.Pb};W.prototype.j=function(){var a=this.ud.A(this.Ia);this.Ia=1+this.Ia|0;return a};W.prototype.$classData=v({td:0},!1,"scala.runtime.ScalaRunTime$$anon$1",{td:1,P:1,a:1,H:1,l:1,m:1});
function Ub(a,b){this.hb=a;this.ib=b}Ub.prototype=new p;Ub.prototype.constructor=Ub;f=Ub.prototype;f.N=function(){return new V(this)};f.o=function(){return Cb(this)};f.h=function(){return pb(this)};f.z=function(){return 2};f.B=function(){return"Attribute"};f.A=function(a){if(0===a)return this.hb;if(1===a)return this.ib;throw new U(""+a);};f.$classData=v({Sb:0},!1,"tyrian.Attribute",{Sb:1,a:1,Ja:1,v:1,ga:1,d:1});
function Zc(){$c=this;new L(this,"accept");new L(this,"accesskey");new L(this,"action");new L(this,"alt");new L(this,"autocomplete");new L(this,"charset");new L(this,"cite");new L(this,"class");new L(this,"class");new L(this,"class");new L(this,"class");new L(this,"class");new L(this,"cols");new J(this,"cols");new L(this,"colspan");new J(this,"colspan");new L(this,"colspan");new J(this,"colspan");new L(this,"content");new L(this,"contenteditable");new I(this,"contenteditable");new L(this,"contenteditable");
new I(this,"contenteditable");new L(this,"coords");new L(this,"data");new L(this,"datetime");new L(this,"datetime");new L(this,"dir");new L(this,"dirname");new L(this,"draggable");new I(this,"draggable");new L(this,"enctype");new L(this,"enctype");new L(this,"for");new L(this,"for");new L(this,"for");new L(this,"for");new L(this,"form");new L(this,"formaction");new L(this,"formaction");new L(this,"headers");new L(this,"height");new J(this,"height");new L(this,"high");new Gb(this,"high");new L(this,
"href");new L(this,"hreflang");new L(this,"hreflang");new L(this,"http");new L(this,"id");new L(this,"kind");new L(this,"label");new L(this,"lang");new L(this,"list");new L(this,"low");new Gb(this,"low");new L(this,"max");new J(this,"max");new L(this,"maxlength");new J(this,"maxlength");new L(this,"maxlength");new J(this,"maxlength");new L(this,"media");new L(this,"method");new L(this,"min");new J(this,"min");new L(this,"multiple");new L(this,"muted");new L(this,"name");new L(this,"optimum");new Gb(this,
"optimum");new L(this,"pattern");new L(this,"placeholder");new L(this,"poster");new L(this,"preload");new L(this,"rel");new L(this,"rows");new J(this,"rows");new L(this,"rowspan");new J(this,"rowspan");new L(this,"rowspan");new J(this,"rowspan");new L(this,"scope");new L(this,"shape");new L(this,"size");new J(this,"size");new L(this,"sizes");new L(this,"span");new J(this,"span");new L(this,"spellcheck");new I(this,"spellcheck");new L(this,"spellcheck");new I(this,"spellcheck");new L(this,"src");new L(this,
"srcdoc");new L(this,"srcdoc");new L(this,"srclang");new L(this,"srclang");new L(this,"srcset");new L(this,"srcset");new L(this,"start");new J(this,"start");new L(this,"step");new J(this,"step");new L(this,"style");new Hb(this,"style");new L(this,"tabindex");new J(this,"tabindex");new L(this,"tabindex");new J(this,"tabindex");new L(this,"target");new L(this,"title");new L(this,"translate");new L(this,"type");new L(this,"type");new L(this,"type");new L(this,"type");new L(this,"usemap");new L(this,
"usemap");new L(this,"width");new J(this,"width");new L(this,"wrap");new Kb(this,"value");new Jb(this,"value");new Ib(this,"value")}Zc.prototype=new p;Zc.prototype.constructor=Zc;Zc.prototype.$classData=v({Wb:0},!1,"tyrian.Html$",{Wb:1,a:1,yd:1,xd:1,yb:1,Dd:1});var $c;function ad(){$c||($c=new Zc)}function O(a){this.lb=a}O.prototype=new p;O.prototype.constructor=O;f=O.prototype;f.N=function(){return new V(this)};f.o=function(){return Cb(this)};f.h=function(){return pb(this)};f.z=function(){return 1};
f.B=function(){return"Text"};f.A=function(a){if(0===a)return this.lb;throw new U(""+a);};var bd=v({gc:0},!1,"tyrian.Text",{gc:1,a:1,Ka:1,v:1,ga:1,d:1});O.prototype.$classData=bd;function ha(a){return Aa(Ba(),a)}class ec extends Ja{constructor(a){super();y(this,a)}}ec.prototype.$classData=v({rc:0},!1,"java.lang.NumberFormatException",{rc:1,rb:1,y:1,F:1,G:1,a:1,d:1});function l(a){for(var b=0,c=1,d=-1+a.length|0;0<=d;)b=b+Math.imul(a.charCodeAt(d),c)|0,c=Math.imul(31,c),d=-1+d|0;return b}
function Ob(a){return";"===a.substring(a.length-1|0)}function cd(){}cd.prototype=new p;cd.prototype.constructor=cd;function dd(){}dd.prototype=cd.prototype;cd.prototype.K=function(){return this.Z()};cd.prototype.va=function(a,b,c,d){return Xa(this,a,b,c,d)};cd.prototype.r=function(){return-1};function X(a){this.Sa=0;this.Bb=a;this.la=0;D();a=this.Bb;this.Sa=Ia(La(),a)}X.prototype=new S;X.prototype.constructor=X;X.prototype.r=function(){return this.Sa-this.la|0};
X.prototype.k=function(){return this.la<this.Sa};X.prototype.j=function(){try{var a=nb(D(),this.Bb,this.la);this.la=1+this.la|0;return a}catch(b){throw b;}};X.prototype.$classData=v({Fc:0},!1,"scala.collection.ArrayOps$ArrayIterator",{Fc:1,P:1,a:1,H:1,l:1,m:1,d:1});function Y(a){this.Q=0;this.Jc=a;this.Va=0;this.Q=a.i()}Y.prototype=new S;Y.prototype.constructor=Y;Y.prototype.r=function(){return this.Q};Y.prototype.k=function(){return 0<this.Q};
Y.prototype.j=function(){if(0<this.Q){var a=this.Jc.n(this.Va);this.Va=1+this.Va|0;this.Q=-1+this.Q|0;return a}return ib().U.j()};Y.prototype.$classData=v({Ic:0},!1,"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{Ic:1,P:1,a:1,H:1,l:1,m:1,d:1});function sb(){this.Gb=null;this.Ya=!1;rb=this;new Pc(this)}sb.prototype=new p;sb.prototype.constructor=sb;sb.prototype.$classData=v({Tc:0},!1,"scala.collection.immutable.ArraySeq$",{Tc:1,a:1,Vd:1,Pd:1,Nd:1,Qd:1,d:1});var rb;
function M(a,b,c){this.La=a;this.jb=b;this.kb=c}M.prototype=new p;M.prototype.constructor=M;f=M.prototype;f.N=function(){return new V(this)};f.o=function(){return Cb(this)};f.h=function(){return pb(this)};f.z=function(){return 3};f.B=function(){return"Tag"};f.A=function(a){switch(a){case 0:return this.La;case 1:return this.jb;case 2:return this.kb;default:throw new U(""+a);}};f.$classData=v({fc:0},!1,"tyrian.Tag",{fc:1,a:1,Ka:1,Vb:1,v:1,ga:1,d:1});function ed(){}ed.prototype=new p;
ed.prototype.constructor=ed;function fd(){}fd.prototype=ed.prototype;function gd(){this.zb=null;this.Ra=0}gd.prototype=new fd;gd.prototype.constructor=gd;function hd(){}hd.prototype=gd.prototype;gd.prototype.h=function(){return this.zb};gd.prototype.o=function(){return this.Ra};function Wb(){}Wb.prototype=new p;Wb.prototype.constructor=Wb;f=Wb.prototype;f.N=function(){return new V(this)};f.o=function(){return 853194735};f.h=function(){return"EmptyAttribute"};f.z=function(){return 0};f.B=function(){return"EmptyAttribute"};
f.A=function(a){throw new U(""+a);};f.$classData=v({Ub:0},!1,"tyrian.EmptyAttribute$",{Ub:1,a:1,Ja:1,v:1,ga:1,d:1,yb:1,Bc:1,Cd:1});var Vb;function id(){}id.prototype=new dd;id.prototype.constructor=id;function jd(){}jd.prototype=id.prototype;id.prototype.h=function(){return this.K()+"(\x3cnot computed\x3e)"};function ub(){this.Ra=0;this.zb="Object";lb();this.Ra=ka(this)}ub.prototype=new hd;ub.prototype.constructor=ub;
ub.prototype.$classData=v({Dc:0},!1,"scala.reflect.ManifestFactory$ObjectManifest$",{Dc:1,Id:1,Hd:1,a:1,Gd:1,Fd:1,Ed:1,Jd:1,d:1,v:1});var tb;function kd(){}kd.prototype=new dd;kd.prototype.constructor=kd;function ld(){}ld.prototype=kd.prototype;
kd.prototype.o=function(){var a=Db();if(this&&this.$classData&&this.$classData.w.Ta)a:{var b=a.ja;a=this.i();switch(a){case 0:a=H(b^0);break a;case 1:a=b;b=this.n(0);a=H(G(a,E(F(),b))^1);break a;default:var c=this.n(0),d=E(F(),c);c=b=G(b,d);var g=this.n(1);g=E(F(),g);var e=g-d|0;for(d=2;d<a;){b=G(b,g);var h=this.n(d);h=E(F(),h);if(e!==(h-g|0)){b=G(b,h);for(d=1+d|0;d<a;)c=this.n(d),b=G(b,E(F(),c)),d=1+d|0;a=H(b^a);break a}g=h;d=1+d|0}a=H(G(G(c,e),g))}}else if(this instanceof md){a=a.ja;d=0;g=a;b=c=
h=e=0;for(var n=this;!n.e();){var r=n.f();n=n.g();r=E(F(),r);g=G(g,r);switch(e){case 0:b=r;e=1;break;case 1:h=r-c|0;e=2;break;case 2:h!==(r-c|0)&&(e=3)}c=r;d=1+d|0}2===e?(d=h,a=H(G(G(G(a,b),d),c))):a=H(g^d)}else a:if(b=a.ja,a=this.q(),a.k())if(c=a.j(),a.k()){d=a.j();e=E(F(),c);c=b=G(b,e);g=E(F(),d);e=g-e|0;for(d=2;a.k();){b=G(b,g);h=a.j();h=E(F(),h);if(e!==(h-g|0)){b=G(b,h);for(d=1+d|0;a.k();)c=a.j(),b=G(b,E(F(),c)),d=1+d|0;a=H(b^d);break a}g=h;d=1+d|0}a=H(G(G(c,e),g))}else a=H(G(b,E(F(),c))^1);else a=
H(b^0);return a};kd.prototype.h=function(){return Ua(this,this.K()+"(",", ",")")};kd.prototype.e=function(){return 0===this.M(0)};function nd(){}nd.prototype=new jd;nd.prototype.constructor=nd;function sd(){}sd.prototype=nd.prototype;function td(){this.za=null}td.prototype=new sd;td.prototype.constructor=td;function ud(){}ud.prototype=td.prototype;td.prototype.n=function(a){return this.za.n(a)};td.prototype.i=function(){return this.za.i()};td.prototype.e=function(){return this.za.e()};
function vd(a){this.za=a}vd.prototype=new ud;vd.prototype.constructor=vd;f=vd.prototype;f.q=function(){return new Y(this)};f.Z=function(){return"IndexedSeqView"};f.M=function(a){var b=this.i();return b===a?0:b<a?-1:1};f.r=function(){return this.i()};f.$classData=v({Hc:0},!1,"scala.collection.IndexedSeqView$Id",{Hc:1,Ud:1,Ld:1,Md:1,O:1,a:1,R:1,l:1,T:1,m:1,S:1,Wd:1,d:1,Td:1,V:1,Sd:1,Ua:1});function wd(){}wd.prototype=new ld;wd.prototype.constructor=wd;function xd(){}xd.prototype=wd.prototype;
function yd(){}yd.prototype=new ld;yd.prototype.constructor=yd;function zd(){}zd.prototype=yd.prototype;
function Ad(a,b,c,d,g){b.b=""+b.b+c;if(!a.s)b.b+="\x3cnot computed\x3e";else if(!a.e()){c=T(a).f();b.b=""+b.b+c;c=a;var e=Q(T(a));if(c!==e&&(!e.s||T(c)!==T(e))&&(c=e,e.s&&!e.e()))for(e=Q(T(e));c!==e&&e.s&&!e.e()&&T(c)!==T(e);){b.b=""+b.b+d;var h=T(c).f();b.b=""+b.b+h;c=Q(T(c));e=Q(T(e));e.s&&!e.e()&&(e=Q(T(e)))}if(!e.s||e.e()){for(;c!==e;)b.b=""+b.b+d,a=T(c).f(),b.b=""+b.b+a,c=Q(T(c));c.s||(b.b=""+b.b+d,b.b+="\x3cnot computed\x3e")}else{h=a;for(a=0;;){var n=h,r=e;if(n!==r&&T(n)!==T(r))h=Q(T(h)),e=
Q(T(e)),a=1+a|0;else break}h=c;n=e;(h===n||T(h)===T(n))&&0<a&&(b.b=""+b.b+d,a=T(c).f(),b.b=""+b.b+a,c=Q(T(c)));for(;;)if(a=c,h=e,a!==h&&T(a)!==T(h))b.b=""+b.b+d,a=T(c).f(),b.b=""+b.b+a,c=Q(T(c));else break;b.b=""+b.b+d;b.b+="\x3ccycle\x3e"}}b.b=""+b.b+g;return b}function Nc(a){this.Jb=null;this.$a=!1;this.Ib=a;this.ab=this.s=!1}Nc.prototype=new xd;Nc.prototype.constructor=Nc;f=Nc.prototype;f.Z=function(){return"LinearSeq"};f.i=function(){for(var a=this,b=0;!a.e();)b=1+b|0,a=a.g();return b};
f.M=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.e()?0:1;break a}if(b.e()){a=-1;break a}c=1+c|0;b=b.g()}return a};f.n=function(a){return Qc(this,a)};function T(a){if(!a.$a&&!a.$a){if(a.ab)throw a=new R,y(a,"self-referential LazyList or a derivation thereof has no more elements"),a;a.ab=!0;try{var b=(0,a.Ib.nd)()}finally{a.ab=!1}a.s=!0;a.Ib=null;a.Jb=b;a.$a=!0}return a.Jb}f.e=function(){return T(this)===Bc()};f.r=function(){return this.s&&this.e()?0:-1};f.f=function(){return T(this).f()};
function Mc(a){var b=a,c=a;for(b.e()||(b=Q(T(b)));c!==b&&!b.e();){b=Q(T(b));if(b.e())break;b=Q(T(b));if(b===c)break;c=Q(T(c))}return a}f.q=function(){return this.s&&this.e()?ib().U:new Sc(this)};f.K=function(){return"LazyList"};f.va=function(a,b,c,d){Mc(this);Ad(this,a.u,b,c,d);return a};f.h=function(){var a=new z;Wa(a);a.b="LazyList";return Ad(this,a,"(",", ",")").b};f.J=function(a){return Qc(this,a|0)};f.ob=function(a){return 0>=a?this:this.s&&this.e()?jb().Hb:Oc(jb(),this,a)};f.g=function(){return Q(T(this))};
f.$classData=v({Zc:0},!1,"scala.collection.immutable.LazyList",{Zc:1,Ba:1,ka:1,O:1,a:1,R:1,l:1,T:1,m:1,S:1,ma:1,fa:1,I:1,V:1,v:1,Ga:1,Da:1,Ha:1,Kb:1,Cb:1,Db:1,Lb:1,d:1});function Z(){}Z.prototype=new xd;Z.prototype.constructor=Z;function Bd(){}Bd.prototype=Z.prototype;Z.prototype.Z=function(){return"IndexedSeq"};Z.prototype.M=function(a){var b=this.i();return b===a?0:b<a?-1:1};Z.prototype.r=function(){return this.i()};Z.prototype.K=function(){return"ArraySeq"};function Cd(){this.Y=null}
Cd.prototype=new xd;Cd.prototype.constructor=Cd;function Dd(){}f=Dd.prototype=Cd.prototype;f.Z=function(){return"IndexedSeq"};f.M=function(a){var b=this.i();return b===a?0:b<a?-1:1};f.r=function(){return this.i()};f.i=function(){return this instanceof Ed?this.Za:this.Y.c.length};f.q=function(){return Yc()===this?kb().Nb:new Vc(this,this.i(),0)};f.K=function(){return"Vector"};function vb(a){this.Ca=a}vb.prototype=new Bd;vb.prototype.constructor=vb;f=vb.prototype;f.i=function(){return this.Ca.c.length};
f.n=function(a){return this.Ca.c[a]};f.o=function(){var a=Db();a:{var b=this.Ca;var c=a.ja;D();a=Ia(La(),b);switch(a){case 0:b=H(c^0);break a;case 1:a=c;b=nb(D(),b,0);b=H(G(a,E(F(),b))^1);break a;default:var d=nb(D(),b,0),g=E(F(),d);d=c=G(c,g);var e=nb(D(),b,1);e=E(F(),e);var h=e-g|0;for(g=2;g<a;){c=G(c,e);var n=nb(D(),b,g);n=E(F(),n);if(h!==(n-e|0)){c=G(c,n);for(g=1+g|0;g<a;)d=nb(D(),b,g),c=G(c,E(F(),d)),g=1+g|0;b=H(c^a);break a}e=n;g=1+g|0}b=H(G(G(d,h),e))}}return b};f.q=function(){return new X(this.Ca)};
f.J=function(a){return this.n(a|0)};f.$classData=v({Uc:0},!1,"scala.collection.immutable.ArraySeq$ofRef",{Uc:1,Xd:1,Ba:1,ka:1,O:1,a:1,R:1,l:1,T:1,m:1,S:1,ma:1,fa:1,I:1,V:1,v:1,Ga:1,Da:1,Ha:1,Vc:1,Ta:1,Ua:1,Xc:1,eb:1,Xa:1,Wa:1,Rd:1,d:1});function md(){}md.prototype=new xd;md.prototype.constructor=md;function Fd(){}f=Fd.prototype=md.prototype;f.q=function(){return new Rc(this)};f.Z=function(){return"LinearSeq"};f.n=function(a){return Qc(this,a)};f.e=function(){return this===B()};
function Gd(a,b){if(b instanceof md){if(a.e())a=b;else if(!b.e()){var c=new N(b.f(),a),d=c;for(b=b.g();!b.e();){var g=new N(b.f(),a);d=d.x=g;b=b.g()}a=c}return a}if(0===b.r())return a;c=b.q();if(c.k()){for(b=d=new N(c.j(),a);c.k();)g=new N(c.j(),a),b=b.x=g;return d}return a}f.i=function(){for(var a=this,b=0;!a.e();)b=1+b|0,a=a.g();return b};f.M=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.e()?0:1;break a}if(b.e()){a=-1;break a}c=1+c|0;b=b.g()}return a};f.K=function(){return"List"};
f.J=function(a){return Qc(this,a|0)};f.ob=function(a){a:for(var b=this;;){if(0>=a||b.e())break a;a=-1+a|0;b=b.g()}return b};function Hd(){this.Y=null}Hd.prototype=new Dd;Hd.prototype.constructor=Hd;function Id(){}Id.prototype=Hd.prototype;function Ed(){this.Y=null;this.Za=0}Ed.prototype=new Id;Ed.prototype.constructor=Ed;function Jd(){}Jd.prototype=Ed.prototype;function N(a,b){this.Fb=a;this.x=b}N.prototype=new Fd;N.prototype.constructor=N;f=N.prototype;f.f=function(){return this.Fb};f.B=function(){return"::"};
f.z=function(){return 2};f.A=function(a){switch(a){case 0:return this.Fb;case 1:return this.x;default:throw F(),new U(""+a);}};f.N=function(){return new W(this)};f.g=function(){return this.x};f.$classData=v({Sc:0},!1,"scala.collection.immutable.$colon$colon",{Sc:1,cd:1,Ba:1,ka:1,O:1,a:1,R:1,l:1,T:1,m:1,S:1,ma:1,fa:1,I:1,V:1,v:1,Ga:1,Da:1,Ha:1,Kb:1,Cb:1,Db:1,Lb:1,Pc:1,Xa:1,Wa:1,eb:1,Eb:1,d:1,ga:1});function Kd(){Ld=this;B();B()}Kd.prototype=new Fd;Kd.prototype.constructor=Kd;f=Kd.prototype;
f.Na=function(){throw new yc("head of empty list");};f.r=function(){return 0};f.q=function(){return ib().U};f.B=function(){return"Nil"};f.z=function(){return 0};f.A=function(a){F();throw new U(""+a);};f.N=function(){return new W(this)};f.g=function(){throw new zc("tail of empty list");};f.f=function(){this.Na()};
f.$classData=v({gd:0},!1,"scala.collection.immutable.Nil$",{gd:1,cd:1,Ba:1,ka:1,O:1,a:1,R:1,l:1,T:1,m:1,S:1,ma:1,fa:1,I:1,V:1,v:1,Ga:1,Da:1,Ha:1,Kb:1,Cb:1,Db:1,Lb:1,Pc:1,Xa:1,Wa:1,eb:1,Eb:1,d:1,ga:1});var Ld;function B(){Ld||(Ld=new Kd);return Ld}function Md(){this.Y=null;this.Za=0;var a=$a().Ob;$a();this.Za=0;this.Y=a}Md.prototype=new Jd;Md.prototype.constructor=Md;function Nd(a){return new U(a+" is out of bounds (empty vector)")}Md.prototype.J=function(a){throw Nd(a|0);};
Md.prototype.n=function(a){throw Nd(a);};Md.prototype.$classData=v({jd:0},!1,"scala.collection.immutable.Vector0$",{jd:1,Yd:1,ae:1,$d:1,Ba:1,ka:1,O:1,a:1,R:1,l:1,T:1,m:1,S:1,ma:1,fa:1,I:1,V:1,v:1,Ga:1,Da:1,Ha:1,Vc:1,Ta:1,Ua:1,Xc:1,eb:1,Xa:1,Wa:1,Eb:1,d:1});var Od;function Yc(){Od||(Od=new Md);return Od}function Va(){this.u=null}Va.prototype=new zd;Va.prototype.constructor=Va;f=Va.prototype;f.Z=function(){return"IndexedSeq"};f.q=function(){var a=new vd(this);return new Y(a)};
f.M=function(a){var b=this.u.i();return b===a?0:b<a?-1:1};f.i=function(){return this.u.i()};f.r=function(){return this.u.i()};f.h=function(){return this.u.b};f.e=function(){return 0===this.u.i()};f.J=function(a){return new da(this.u.b.charCodeAt(a|0))};f.n=function(a){return new da(this.u.b.charCodeAt(a))};
f.$classData=v({ld:0},!1,"scala.collection.mutable.StringBuilder",{ld:1,be:1,ka:1,O:1,a:1,R:1,l:1,T:1,m:1,S:1,ma:1,fa:1,I:1,V:1,v:1,ke:1,ie:1,le:1,ee:1,Oa:1,je:1,ce:1,fe:1,de:1,ge:1,Ta:1,Ua:1,he:1,lc:1,d:1});ba=new k(0,0);xa.Qb=ba;
mdoc_js_run0=function(){Pa||(Pa=new Oa);ad();var a=Nb("font-family","Arial, Helvetica, sans-serif");Ec||(Ec=new Dc);a=new Ub("style",a);ad();D();ad();var b=qb(D(),new (x(Fb).p)([(ad(),new O("HTML fragment rendered by Tyrian on the server."))])),c=lb().ia;A();b=Gd(B(),b);b=qb(0,new (x(Fb).p)([new M("b",c,b)]));c=lb().ia;A();b=Gd(B(),b);c=new M("p",c,b);ad();a=qb(D(),new (x(Eb).p)([a]));D();ad();b=x(Fb).p;var d=lb().ia;lb();var g=qb(D(),new (x(bd).p)([(ad(),new O("Hello, world!"))]));g=Gd(B(),g);c=
qb(0,new b([c,new M("p",d,g)]));A();a=Gd(B(),a);A();c=Gd(B(),c);a=new M("div",a,c);$b||($b=new Zb);c=Sb;Qb||(Qb=new Pb);c(Qb,a)};
}).call(this);
