let mdoc_js_run0;
(function(){
'use strict';var d,aa=Object.freeze({esVersion:6,assumingES6:!0,productionMode:!0,linkerVersion:"1.10.0",fileLevelThis:this}),ba;function ca(a){for(var b in a)return b}function h(a){this.Db=a}h.prototype.toString=function(){return String.fromCharCode(this.Db)};var ea=function da(a,b,c){var g=new a.w(b[c]);if(c<b.length-1){a=a.wa;c+=1;for(var f=g.c,k=0;k<f.length;k++)f[k]=da(a,b,c)}return g};
function fa(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"number"!==typeof a||a===a&&Math.fround(a)!==a?"java.lang.Double":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.ne():a instanceof l?"java.lang.Long":a instanceof h?"java.lang.Character":a&&a.$classData?a.$classData.name:
null.Ta.name}}function ha(a,b){switch(typeof a){case "string":return a===b;case "number":return Object.is(a,b);case "boolean":return a===b;case "undefined":return a===b;default:return a&&a.$classData||null===a?b=a.n(b):a instanceof l?b instanceof l?(a=m(a),b=m(b),b=a.u===b.u&&a.t===b.t):b=!1:b=a instanceof h?b instanceof h?q(a)===q(b):!1:r.prototype.n.call(a,b),b}}
function ia(a){switch(typeof a){case "string":return t(a);case "number":return ja(a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a=a.q():a instanceof l?(a=m(a),a=a.u^a.t):a=a instanceof h?q(a):r.prototype.q.call(a),a}}function ka(a){return void 0===a?"undefined":a.toString()}var la=0,ma=new WeakMap;
function na(a){switch(typeof a){case "string":return t(a);case "number":return ja(a);case "bigint":var b=0;for(a<BigInt(0)&&(a=~a);a!==BigInt(0);)b^=Number(BigInt.asIntN(32,a)),a>>=BigInt(32);return b;case "boolean":return a?1231:1237;case "undefined":return 0;case "symbol":return a=a.description,void 0===a?0:t(a);default:if(null===a)return 0;b=ma.get(a);void 0===b&&(la=b=la+1|0,ma.set(a,b));return b}}function q(a){return null===a?0:a.Db}function m(a){return null===a?ba:a}function r(){}
r.prototype.constructor=r;function u(){}u.prototype=r.prototype;r.prototype.q=function(){return na(this)};r.prototype.n=function(a){return this===a};r.prototype.i=function(){var a=this.q();return fa(this)+"@"+(+(a>>>0)).toString(16)};r.prototype.toString=function(){return this.i()};function v(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=null}else this.c=a}v.prototype=new u;v.prototype.constructor=v;function oa(){}oa.prototype=v.prototype;
function pa(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=!1}else this.c=a}pa.prototype=new u;pa.prototype.constructor=pa;function qa(a){this.c="number"===typeof a?new Uint16Array(a):a}qa.prototype=new u;qa.prototype.constructor=qa;function ra(a){this.c="number"===typeof a?new Int8Array(a):a}ra.prototype=new u;ra.prototype.constructor=ra;function sa(a){this.c="number"===typeof a?new Int16Array(a):a}sa.prototype=new u;sa.prototype.constructor=sa;
function ta(a){this.c="number"===typeof a?new Int32Array(a):a}ta.prototype=new u;ta.prototype.constructor=ta;function ua(a){if("number"===typeof a){this.c=Array(a);for(var b=0;b<a;b++)this.c[b]=ba}else this.c=a}ua.prototype=new u;ua.prototype.constructor=ua;function va(a){this.c="number"===typeof a?new Float32Array(a):a}va.prototype=new u;va.prototype.constructor=va;function wa(a){this.c="number"===typeof a?new Float64Array(a):a}wa.prototype=new u;wa.prototype.constructor=wa;
function w(){this.w=void 0;this.ua=this.wa=this.v=null;this.va=0;this.fc=null;this.Q="";this.R=this.ta=this.gb=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function x(a,b,c,e){var g=new w;g.v={};g.fc=a;g.Q=b;g.R=f=>f===g;g.name=c;g.isPrimitive=!0;g.isInstance=()=>!1;void 0!==e&&(g.ta=xa(g,e));return g}
function y(a,b,c,e){var g=new w,f=ca(a);g.v=e;g.Q="L"+c+";";g.R=k=>!!k.v[f];g.name=c;g.isInterface=b;g.isInstance=k=>!!(k&&k.$classData&&k.$classData.v[f]);return g}function xa(a,b,c){var e=new w;b.prototype.$classData=e;var g="["+a.Q;e.w=b;e.v={a:1,kb:1,b:1};e.wa=a;e.ua=a;e.va=1;e.Q=g;e.name=g;e.isArrayClass=!0;e.R=c||(f=>e===f);e.isInstance=f=>f instanceof b;return e}
function ya(a){function b(n){if("number"===typeof n){this.c=Array(n);for(var p=0;p<n;p++)this.c[p]=null}else this.c=n}var c=new w;b.prototype=new oa;b.prototype.constructor=b;var e=a.ua||a,g=a.va+1;b.prototype.$classData=c;var f="["+a.Q;c.w=b;c.v={a:1,kb:1,b:1};c.wa=a;c.ua=e;c.va=g;c.Q=f;c.name=f;c.isArrayClass=!0;var k=n=>{var p=n.va;return p===g?e.R(n.ua):p>g&&e===z};c.R=k;c.isInstance=n=>{n=n&&n.$classData;return!!n&&(n===c||k(n))};return c}function A(a){a.ta||(a.ta=ya(a));return a.ta}
function za(a){a.gb||(a.gb=new Aa(a));return a.gb}w.prototype.isAssignableFrom=function(a){return this===a||this.R(a)};w.prototype.checkCast=function(){};w.prototype.getSuperclass=function(){return this.Tc?za(this.Tc):null};w.prototype.getComponentType=function(){return this.wa?za(this.wa):null};w.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=A(b);return ea(b,a,0)};var z=new w;z.v={a:1};z.Q="Ljava.lang.Object;";z.R=a=>!a.isPrimitive;z.name="java.lang.Object";
z.isInstance=a=>null!==a;z.ta=xa(z,v,a=>{var b=a.va;return 1===b?!a.ua.isPrimitive:1<b});r.prototype.$classData=z;x(void 0,"V","void",void 0);x(!1,"Z","boolean",pa);x(0,"C","char",qa);x(0,"B","byte",ra);x(0,"S","short",sa);x(0,"I","int",ta);var Ba=x(null,"J","long",ua);x(0,"F","float",va);x(0,"D","double",wa);function Aa(a){this.Ta=a}Aa.prototype=new u;Aa.prototype.constructor=Aa;Aa.prototype.i=function(){return(this.Ta.isInterface?"interface ":this.Ta.isPrimitive?"":"class ")+this.Ta.name};
Aa.prototype.$classData=y({Cc:0},!1,"java.lang.Class",{Cc:1,a:1});function Ca(){this.Hb=this.Ua=this.ya=null;Da=this;this.ya=new ArrayBuffer(8);this.Ua=new Int32Array(this.ya,0,2);new Float32Array(this.ya,0,2);this.Hb=new Float64Array(this.ya,0,1);this.Ua[0]=16909060;new Int8Array(this.ya,0,8)}Ca.prototype=new u;Ca.prototype.constructor=Ca;function Ea(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;a.Hb[0]=b;return(a.Ua[0]|0)^(a.Ua[1]|0)}
Ca.prototype.$classData=y({Dc:0},!1,"java.lang.FloatingPointBits$",{Dc:1,a:1});var Da;function Fa(){Da||(Da=new Ca);return Da}
function Ga(){this.Jb=this.lb=null;Ha=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.lb=a;this.Jb=null}Ga.prototype=new u;Ga.prototype.constructor=Ga;function Ia(a,b,c){null!==a.lb?(Ja||(Ja=new Ka),a=a.lb,La||(La=new Ma),b=La.Lb.call(a,b)?a[b]:c):b=Ia(a.Jb,b,c);return b}Ga.prototype.$classData=y({Jc:0},!1,"java.lang.System$SystemProperties$",{Jc:1,a:1});var Ha;function Ka(){}Ka.prototype=new u;Ka.prototype.constructor=Ka;Ka.prototype.$classData=y({Oc:0},!1,"java.lang.Utils$",{Oc:1,a:1});var Ja;function Ma(){this.Lb=null;La=this;this.Lb=Object.prototype.hasOwnProperty}
Ma.prototype=new u;Ma.prototype.constructor=Ma;Ma.prototype.$classData=y({Pc:0},!1,"java.lang.Utils$Cache$",{Pc:1,a:1});var La;function Na(){}Na.prototype=new u;Na.prototype.constructor=Na;function Oa(a,b){if(b instanceof v||b instanceof pa||b instanceof qa||b instanceof ra||b instanceof sa||b instanceof ta||b instanceof ua||b instanceof va||b instanceof wa)return b.c.length;a=new Pa;B(a,"argument type mismatch");throw a;}Na.prototype.$classData=y({Qc:0},!1,"java.lang.reflect.Array$",{Qc:1,a:1});
var Qa;function Ra(){Qa||(Qa=new Na);return Qa}function Sa(){}Sa.prototype=new u;Sa.prototype.constructor=Sa;Sa.prototype.$classData=y({Rc:0},!1,"java.util.Arrays$",{Rc:1,a:1});var Ta;function Ua(){}Ua.prototype=new u;Ua.prototype.constructor=Ua;Ua.prototype.$classData=y({gc:0},!1,"mdocjs$",{gc:1,a:1});var Va;function l(a,b){this.u=a;this.t=b}l.prototype=new u;l.prototype.constructor=l;l.prototype.n=function(a){return a instanceof l?this.u===a.u&&this.t===a.t:!1};
l.prototype.q=function(){return this.u^this.t};l.prototype.i=function(){Wa();var a=this.u,b=this.t;return b===a>>31?""+a:0>b?"-"+Xa(-a|0,0!==a?~b:-b|0):Xa(a,b)};l.prototype.$classData=y({yc:0},!1,"org.scalajs.linker.runtime.RuntimeLong",{yc:1,a:1});
function Xa(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+Math.clz32(1E9)|0)-(0!==b?Math.clz32(b):32+Math.clz32(a)|0)|0,e=c,g=0===(32&e)?1E9<<e:0;e=0===(32&e)?5E8>>>(31-e|0)|0|0<<e:1E9<<e;var f=a,k=b;for(a=b=0;0<=c&&0!==(-2097152&k);){var n=f,p=k,G=g,Y=e;if(p===Y?(-2147483648^n)>=(-2147483648^G):(-2147483648^p)>=(-2147483648^Y))n=k,p=e,k=f-g|0,n=(-2147483648^k)>(-2147483648^f)?-1+(n-p|0)|0:n-p|0,f=k,k=n,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;n=e>>>1|0;g=g>>>1|0|e<<31;e=n}c=k;if(0===
c?-1147483648<=(-2147483648^f):-2147483648<=(-2147483648^c))c=4294967296*k+ +(f>>>0),f=c/1E9,g=f/4294967296|0,e=b,b=f=e+(f|0)|0,a=(-2147483648^f)<(-2147483648^e)?1+(a+g|0)|0:a+g|0,f=c%1E9|0;c=""+f;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function Ya(){this.Pa=0}Ya.prototype=new u;Ya.prototype.constructor=Ya;function Za(a,b,c){return 0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0)}
Ya.prototype.$classData=y({zc:0},!1,"org.scalajs.linker.runtime.RuntimeLong$",{zc:1,a:1});var $a;function Wa(){$a||($a=new Ya);return $a}function ab(a,b,c,e){if(a.e())a=""+b+e;else{var g=a.Qa,f=new bb;f.C=cb(new C);a=g.call(a,f,b,c,e).C.d}return a}function db(a,b,c,e,g){var f=b.C;0!==(c.length|0)&&(f.d=""+f.d+c);a=a.l();if(a.j())for(c=a.g(),f.d=""+f.d+c;a.j();)f.d=""+f.d+e,c=a.g(),f.d=""+f.d+c;0!==(g.length|0)&&(f.d=""+f.d+g);return b}
function eb(){this.dc=null;fb=this;this.dc=new v(0);new (A(A(z)).w)(0);new (A(A(A(z))).w)(0);new (A(A(A(A(z)))).w)(0);new (A(A(A(A(A(z))))).w)(0);new (A(A(A(A(A(A(z)))))).w)(0)}eb.prototype=new u;eb.prototype.constructor=eb;eb.prototype.$classData=y({Vd:0},!1,"scala.collection.immutable.VectorStatics$",{Vd:1,a:1});var fb;function gb(){fb||(fb=new eb);return fb}function hb(){}hb.prototype=new u;hb.prototype.constructor=hb;
hb.prototype.$classData=y({yd:0},!1,"scala.collection.package$$colon$plus$",{yd:1,a:1});var ib;function jb(){}jb.prototype=new u;jb.prototype.constructor=jb;jb.prototype.$classData=y({zd:0},!1,"scala.collection.package$$plus$colon$",{zd:1,a:1});var kb;function lb(){}lb.prototype=new u;lb.prototype.constructor=lb;lb.prototype.$classData=y({cd:0},!1,"scala.math.Ordered$",{cd:1,a:1});var mb;
function nb(){this.Ba=null;ob=this;pb||(pb=new qb);pb||(pb=new qb);rb||(rb=new sb);tb||(tb=new ub);D();vb();this.Ba=E();wb||(wb=new xb);kb||(kb=new jb);ib||(ib=new hb);yb||(yb=new zb);Ab();Bb();Cb||(Cb=new Db);Eb||(Eb=new Fb);Gb||(Gb=new Hb);Ib||(Ib=new Jb);Kb||(Kb=new Lb);Mb||(Mb=new Nb);mb||(mb=new lb);Ob||(Ob=new Pb);Qb||(Qb=new Rb);Sb||(Sb=new Tb);Ub||(Ub=new Vb)}nb.prototype=new u;nb.prototype.constructor=nb;nb.prototype.$classData=y({ed:0},!1,"scala.package$",{ed:1,a:1});var ob;
function Wb(){ob||(ob=new nb);return ob}function Xb(){}Xb.prototype=new u;Xb.prototype.constructor=Xb;function Yb(a,b,c){if(b===c)c=!0;else if(Zb(b))a:if(Zb(c))c=$b(b,c);else{if(c instanceof h){if("number"===typeof b){c=+b===q(c);break a}if(b instanceof l){a=m(b);b=a.t;c=q(c);c=a.u===c&&b===c>>31;break a}}c=null===b?null===c:ha(b,c)}else c=b instanceof h?ac(b,c):null===b?null===c:ha(b,c);return c}
function $b(a,b){if("number"===typeof a){a=+a;if("number"===typeof b)return a===+b;if(b instanceof l){var c=m(b);b=c.u;c=c.t;return a===Za(Wa(),b,c)}return!1}if(a instanceof l){c=m(a);a=c.u;c=c.t;if(b instanceof l){b=m(b);var e=b.t;return a===b.u&&c===e}return"number"===typeof b?(b=+b,Za(Wa(),a,c)===b):!1}return null===a?null===b:ha(a,b)}
function ac(a,b){if(b instanceof h)return q(a)===q(b);if(Zb(b)){if("number"===typeof b)return+b===q(a);if(b instanceof l){b=m(b);var c=b.t;a=q(a);return b.u===a&&c===a>>31}return null===b?null===a:ha(b,a)}return null===a&&null===b}Xb.prototype.$classData=y({de:0},!1,"scala.runtime.BoxesRunTime$",{de:1,a:1});var bc;function cc(){bc||(bc=new Xb);return bc}function dc(){}dc.prototype=new u;dc.prototype.constructor=dc;
function ec(a,b,c){if(b instanceof v||b instanceof ta||b instanceof wa||b instanceof ua||b instanceof va)return b.c[c];if(b instanceof qa)return new h(b.c[c]);if(b instanceof ra||b instanceof sa||b instanceof pa)return b.c[c];if(null===b)throw new F;throw new fc(b);}function gc(a){H();var b=a.M();return ab(b,a.F()+"(",",",")")}function hc(a,b){return null===b?null:0===b.c.length?(ic||(ic=new jc),a=ic,kc||(kc=new lc),a.tb||a.tb||(a.Wb=new mc(new v(0)),a.tb=!0),a.Wb):new mc(b)}
dc.prototype.$classData=y({ge:0},!1,"scala.runtime.ScalaRunTime$",{ge:1,a:1});var nc;function H(){nc||(nc=new dc);return nc}function oc(){}oc.prototype=new u;oc.prototype.constructor=oc;
function I(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=Wa();if(-0x7fffffffffffffff>a){b.Pa=-2147483648;var c=0}else if(0x7fffffffffffffff<=a)b.Pa=2147483647,c=-1;else{c=a|0;var e=a/4294967296|0;b.Pa=0>a&&0!==c?-1+e|0:e}b=b.Pa;a=Za(Wa(),c,b)===a?c^b:Ea(Fa(),a)}return a}return b instanceof l?(a=m(b),b=new l(a.u,a.t),a=b.u,b=b.t,b===a>>31?a:a^b):ia(b)}function pc(a,b){throw new J(""+b);}
oc.prototype.$classData=y({je:0},!1,"scala.runtime.Statics$",{je:1,a:1});var qc;function K(){qc||(qc=new oc);return qc}function rc(){}rc.prototype=new u;rc.prototype.constructor=rc;function sc(a){tc||(tc=new rc);return a instanceof uc?a.Ja:a}rc.prototype.$classData=y({ce:0},!1,"scala.scalajs.runtime.package$",{ce:1,a:1});var tc;function vc(){}vc.prototype=new u;vc.prototype.constructor=vc;function wc(){}wc.prototype=vc.prototype;
function L(a,b){a=xc(a,b);return-430675100+Math.imul(5,a<<13|a>>>19|0)|0}function xc(a,b){b=Math.imul(-862048943,b);b=Math.imul(461845907,b<<15|b>>>17|0);return a^b}function M(a){a=Math.imul(-2048144789,a^(a>>>16|0));a=Math.imul(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function yc(a){zc();var b=a.D();if(0===b)return t(a.F());var c=L(-889275714,t(a.F()));for(var e=0;e<b;){var g=a.E(e);c=L(c,I(K(),g));e=1+e|0}return M(c^b)}
var Ac=y({eb:0},!0,"tyrian.Attr",{eb:1,a:1}),Bc=y({fb:0},!0,"tyrian.Elem",{fb:1,a:1});function N(a){if(null===a)throw new F;}N.prototype=new u;N.prototype.constructor=N;N.prototype.$classData=y({mc:0},!1,"tyrian.HtmlAttributes$AttributeNameBoolean",{mc:1,a:1});function Fc(a){if(null===a)throw new F;}Fc.prototype=new u;Fc.prototype.constructor=Fc;Fc.prototype.$classData=y({nc:0},!1,"tyrian.HtmlAttributes$AttributeNameDouble",{nc:1,a:1});function O(a){if(null===a)throw new F;}O.prototype=new u;
O.prototype.constructor=O;O.prototype.$classData=y({oc:0},!1,"tyrian.HtmlAttributes$AttributeNameInt",{oc:1,a:1});function P(a){if(null===a)throw new F;}P.prototype=new u;P.prototype.constructor=P;P.prototype.$classData=y({pc:0},!1,"tyrian.HtmlAttributes$AttributeNameString",{pc:1,a:1});function Gc(a){if(null===a)throw new F;}Gc.prototype=new u;Gc.prototype.constructor=Gc;Gc.prototype.$classData=y({qc:0},!1,"tyrian.HtmlAttributes$PropertyNameBoolean",{qc:1,a:1});
function Hc(a){if(null===a)throw new F;}Hc.prototype=new u;Hc.prototype.constructor=Hc;Hc.prototype.$classData=y({rc:0},!1,"tyrian.HtmlAttributes$PropertyNameDouble",{rc:1,a:1});function Ic(a){if(null===a)throw new F;}Ic.prototype=new u;Ic.prototype.constructor=Ic;Ic.prototype.$classData=y({sc:0},!1,"tyrian.HtmlAttributes$PropertyNameString",{sc:1,a:1});function Jc(){Kc=this;Lc("","")}Jc.prototype=new u;Jc.prototype.constructor=Jc;
function Lc(a,b){Kc||(Kc=new Jc);return""===a?""===b?"":Mc(b)?b:b+";":""===b?Mc(a)?a:a+";":a+":"+b+";"}Jc.prototype.$classData=y({tc:0},!1,"tyrian.Style$package$Style$",{tc:1,a:1});var Kc;function Nc(){this.Cb=null;Oc=this;this.Cb=new Pc(a=>""===a?a:" "+a)}Nc.prototype=new u;Nc.prototype.constructor=Nc;
function Qc(a,b){if(b instanceof Q){var c=a.Cb,e=b.Ma,g=(()=>p=>{if(p instanceof Rc)p=p.Ka+'\x3d"'+p.La+'"';else if(Sc||(Sc=new Tc),p===Sc)p="";else throw new fc(p);return p})(a);if(e===E())g=E();else{var f=e.f(),k=f=new R(g(f),E());for(e=e.h();e!==E();){var n=e.f();n=new R(g(n),E());k=k.J=n;e=e.h()}g=f}f=g;a:for(;;)if(f.e()){g=E();break}else if(k=f.f(),g=f.h(),""===k===!0)f=g;else for(;;){if(g.e())g=f;else{if(""===g.f()!==!0){g=g.h();continue}k=g;g=new R(f.f(),E());e=f.h();for(f=g;e!==k;)n=new R(e.f(),
E()),f=f.J=n,e=e.h();for(e=k=k.h();!k.e();){if(""===k.f()===!0){for(;e!==k;)n=new R(e.f(),E()),f=f.J=n,e=e.h();e=k.h()}k=k.h()}e.e()||(f.J=e)}break a}c=c.ca(ab(g,""," ",""));k=b.Na;a=(p=>G=>{if(G instanceof S)return G.Oa;if(G&&G.$classData&&G.$classData.v.kc)return Qc(p,G);throw new fc(G);})(a);if(k===E())a=E();else{g=k.f();f=g=new R(a(g),E());for(k=k.h();k!==E();)e=k.f(),e=new R(a(e),E()),f=f.J=e,k=k.h();a=g}a=ab(a,"","","");return"\x3c"+b.sa+c+"\x3e"+a+"\x3c/"+b.sa+"\x3e"}throw new fc(b);}
Nc.prototype.$classData=y({wc:0},!1,"tyrian.runtime.Render$",{wc:1,a:1});var Oc;function Uc(){}Uc.prototype=new u;Uc.prototype.constructor=Uc;Uc.prototype.$classData=y({xc:0},!1,"tyrian.runtime.TyrianSSR$",{xc:1,a:1});var Vc;
function Wc(a){0===(32&a.Sa)<<24>>24&&0===(32&a.Sa)<<24>>24&&(a.Gb=new ta(new Int32Array([1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822])),a.Sa=(32|a.Sa)<<24>>24);return a.Gb}function Xc(){this.Gb=null;this.Sa=0}Xc.prototype=new u;Xc.prototype.constructor=Xc;
Xc.prototype.$classData=y({Bc:0},!1,"java.lang.Character$",{Bc:1,a:1,b:1});var Yc;function Zc(a){throw new $c('For input string: "'+a+'"');}function ad(){}ad.prototype=new u;ad.prototype.constructor=ad;ad.prototype.$classData=y({Fc:0},!1,"java.lang.Integer$",{Fc:1,a:1,b:1});var bd;function Zb(a){return"number"===typeof a||a instanceof l}function B(a,b){a.Kb=b;a.Kc=null;a.Lc=!0;a.Mc=!0;a.Fb()}
class cd extends Error{constructor(){super();this.Kc=this.Kb=null;this.Mc=this.Lc=!1}Ra(){return this.Kb}Fb(){"[object Error]"!==Object.prototype.toString.call(this)&&void 0!==Error.captureStackTrace&&Error.captureStackTrace(this)}i(){var a=fa(this),b=this.Ra();return null===b?a:a+": "+b}q(){return r.prototype.q.call(this)}n(a){return r.prototype.n.call(this,a)}get message(){var a=this.Ra();return null===a?"":a}get name(){return fa(this)}toString(){return this.i()}}function dd(){}dd.prototype=new u;
dd.prototype.constructor=dd;dd.prototype.$classData=y({Uc:0},!1,"scala.Array$",{Uc:1,a:1,b:1});var ed;function xb(){}xb.prototype=new u;xb.prototype.constructor=xb;xb.prototype.i=function(){return"::"};xb.prototype.$classData=y({Bd:0},!1,"scala.collection.immutable.$colon$colon$",{Bd:1,a:1,b:1});var wb;function Fb(){}Fb.prototype=new u;Fb.prototype.constructor=Fb;Fb.prototype.$classData=y({Qd:0},!1,"scala.collection.immutable.Range$",{Qd:1,a:1,b:1});var Eb;function Db(){}Db.prototype=new u;
Db.prototype.constructor=Db;Db.prototype.$classData=y({Xd:0},!1,"scala.collection.mutable.StringBuilder$",{Xd:1,a:1,b:1});var Cb;function Jb(){}Jb.prototype=new u;Jb.prototype.constructor=Jb;Jb.prototype.$classData=y({$c:0},!1,"scala.math.Fractional$",{$c:1,a:1,b:1});var Ib;function Lb(){}Lb.prototype=new u;Lb.prototype.constructor=Lb;Lb.prototype.$classData=y({ad:0},!1,"scala.math.Integral$",{ad:1,a:1,b:1});var Kb;function Nb(){}Nb.prototype=new u;Nb.prototype.constructor=Nb;
Nb.prototype.$classData=y({bd:0},!1,"scala.math.Numeric$",{bd:1,a:1,b:1});var Mb;function fd(){}fd.prototype=new u;fd.prototype.constructor=fd;function gd(){}gd.prototype=fd.prototype;fd.prototype.i=function(){return"\x3cfunction0\x3e"};function hd(){}hd.prototype=new u;hd.prototype.constructor=hd;function id(){}id.prototype=hd.prototype;hd.prototype.i=function(){return"\x3cfunction1\x3e"};function jd(a){this.Ab=a}jd.prototype=new u;jd.prototype.constructor=jd;jd.prototype.i=function(){return""+this.Ab};
jd.prototype.$classData=y({ee:0},!1,"scala.runtime.IntRef",{ee:1,a:1,b:1});function kd(a){this.Bb=a}kd.prototype=new u;kd.prototype.constructor=kd;kd.prototype.i=function(){return""+this.Bb};kd.prototype.$classData=y({fe:0},!1,"scala.runtime.ObjectRef",{fe:1,a:1,b:1});function Rb(){}Rb.prototype=new u;Rb.prototype.constructor=Rb;Rb.prototype.$classData=y({gd:0},!1,"scala.util.Either$",{gd:1,a:1,b:1});var Qb;function Tb(){}Tb.prototype=new u;Tb.prototype.constructor=Tb;Tb.prototype.i=function(){return"Left"};
Tb.prototype.$classData=y({hd:0},!1,"scala.util.Left$",{hd:1,a:1,b:1});var Sb;function Vb(){}Vb.prototype=new u;Vb.prototype.constructor=Vb;Vb.prototype.i=function(){return"Right"};Vb.prototype.$classData=y({id:0},!1,"scala.util.Right$",{id:1,a:1,b:1});var Ub;
function md(){this.Rb=this.Ca=0;nd=this;this.Ca=t("Seq");this.Rb=t("Map");t("Set");var a=Wb().Ba,b=this.Rb,c=0,e=0,g=0,f=1;for(a=a.l();a.j();){var k=a.g();k=I(K(),k);c=c+k|0;e^=k;f=Math.imul(f,1|k);g=1+g|0}b=L(b,c);b=L(b,e);b=xc(b,f);M(b^g)}md.prototype=new wc;md.prototype.constructor=md;md.prototype.$classData=y({jd:0},!1,"scala.util.hashing.MurmurHash3$",{jd:1,Ae:1,a:1});var nd;function zc(){nd||(nd=new md);return nd}class od extends cd{}function pd(){}pd.prototype=new u;
pd.prototype.constructor=pd;function qd(){}qd.prototype=pd.prototype;function rd(){}rd.prototype=new u;rd.prototype.constructor=rd;function sd(){}sd.prototype=rd.prototype;function td(){this.G=null;ud=this;this.G=new vd}td.prototype=new u;td.prototype.constructor=td;td.prototype.$classData=y({rd:0},!1,"scala.collection.Iterator$",{rd:1,a:1,I:1,b:1});var ud;function D(){ud||(ud=new td);return ud}function wd(){}wd.prototype=new u;wd.prototype.constructor=wd;
wd.prototype.jb=function(){throw new xd("head of empty lazy list");};function T(){throw new yd("tail of empty lazy list");}wd.prototype.f=function(){this.jb()};wd.prototype.$classData=y({Kd:0},!1,"scala.collection.immutable.LazyList$State$Empty$",{Kd:1,a:1,Pe:1,b:1});var zd;function Ad(){zd||(zd=new wd);return zd}function Hb(){}Hb.prototype=new u;Hb.prototype.constructor=Hb;Hb.prototype.$classData=y({Zc:0},!1,"scala.math.Equiv$",{Zc:1,a:1,se:1,b:1});var Gb;function Pb(){}Pb.prototype=new u;
Pb.prototype.constructor=Pb;Pb.prototype.$classData=y({dd:0},!1,"scala.math.Ordering$",{dd:1,a:1,te:1,b:1});var Ob;function Bd(a){this.$d=a}Bd.prototype=new gd;Bd.prototype.constructor=Bd;Bd.prototype.$classData=y({Zd:0},!1,"scala.scalajs.runtime.AnonFunction0",{Zd:1,cf:1,a:1,ke:1});function Pc(a){this.be=a}Pc.prototype=new id;Pc.prototype.constructor=Pc;Pc.prototype.ca=function(a){return(0,this.be)(a)};Pc.prototype.$classData=y({ae:0},!1,"scala.scalajs.runtime.AnonFunction1",{ae:1,df:1,a:1,ba:1});
function Cd(){(Dd=this)||(Dd=new Cd)}Cd.prototype=new u;Cd.prototype.constructor=Cd;Cd.prototype.i=function(){return"Attribute"};Cd.prototype.$classData=y({ic:0},!1,"tyrian.Attribute$",{ic:1,a:1,Pb:1,Yc:1});var Dd;class U extends od{}U.prototype.$classData=y({H:0},!1,"java.lang.RuntimeException",{H:1,K:1,L:1,a:1,b:1});function cb(a){a.d="";return a}function C(){this.d=null}C.prototype=new u;C.prototype.constructor=C;C.prototype.i=function(){return this.d};
C.prototype.k=function(){return this.d.length|0};C.prototype.$classData=y({Ic:0},!1,"java.lang.StringBuilder",{Ic:1,a:1,Ac:1,oe:1,b:1});function Ed(){}Ed.prototype=new u;Ed.prototype.constructor=Ed;function V(){}d=V.prototype=Ed.prototype;d.l=function(){return this};d.e=function(){return!this.j()};d.xa=function(a){return this.cb(a,-1)};d.cb=function(a,b){a=0<a?a:0;b=0>b?-1:b<=a?0:b-a|0;return 0===b?D().G:new Fd(this,a,b)};d.i=function(){return"\x3citerator\x3e"};
d.Qa=function(a,b,c,e){return db(this,a,b,c,e)};d.m=function(){return-1};function qb(){Gd||(Gd=new Hd)}qb.prototype=new sd;qb.prototype.constructor=qb;qb.prototype.$classData=y({pd:0},!1,"scala.collection.Iterable$",{pd:1,qd:1,a:1,I:1,b:1});var pb;function Id(){}Id.prototype=new u;Id.prototype.constructor=Id;function Jd(){}Jd.prototype=Id.prototype;
function Kd(a,b){var c=a.m();if(-1!==c){var e=b.m();c=-1!==e&&c!==e}else c=!1;if(c)return!1;a:{a=a.l();for(b=b.l();a.j()&&b.j();)if(!Yb(cc(),a.g(),b.g())){b=!1;break a}b=a.j()===b.j()}return b}function Hd(){vb()}Hd.prototype=new sd;Hd.prototype.constructor=Hd;Hd.prototype.$classData=y({Gd:0},!1,"scala.collection.immutable.Iterable$",{Gd:1,qd:1,a:1,I:1,b:1});var Gd;function Ld(){this.Xb=null;Md=this;this.Xb=Nd(new Od(new Bd(()=>Ad())))}Ld.prototype=new u;Ld.prototype.constructor=Ld;
function Pd(a,b,c){return new Od(new Bd(((e,g)=>()=>{for(var f=e.Bb,k=g.Ab;0<k&&!f.e();)f=T(W(f)),e.Bb=f,k=-1+k|0,g.Ab=k;return W(f)})(new kd(b),new jd(c))))}Ld.prototype.$classData=y({Id:0},!1,"scala.collection.immutable.LazyList$",{Id:1,a:1,la:1,I:1,b:1});var Md;function Ab(){Md||(Md=new Ld);return Md}function zb(){}zb.prototype=new u;zb.prototype.constructor=zb;zb.prototype.$classData=y({Sd:0},!1,"scala.collection.immutable.Stream$",{Sd:1,a:1,la:1,I:1,b:1});var yb;class Pa extends U{}
Pa.prototype.$classData=y({Ib:0},!1,"java.lang.IllegalArgumentException",{Ib:1,H:1,K:1,L:1,a:1,b:1});class J extends U{constructor(a){super();B(this,a)}}J.prototype.$classData=y({Ec:0},!1,"java.lang.IndexOutOfBoundsException",{Ec:1,H:1,K:1,L:1,a:1,b:1});class F extends U{constructor(){super();B(this,null)}}F.prototype.$classData=y({Gc:0},!1,"java.lang.NullPointerException",{Gc:1,H:1,K:1,L:1,a:1,b:1});class yd extends U{constructor(a){super();B(this,a)}}
yd.prototype.$classData=y({Nc:0},!1,"java.lang.UnsupportedOperationException",{Nc:1,H:1,K:1,L:1,a:1,b:1});class xd extends U{constructor(a){super();B(this,a)}}xd.prototype.$classData=y({Sc:0},!1,"java.util.NoSuchElementException",{Sc:1,H:1,K:1,L:1,a:1,b:1});
class fc extends U{constructor(a){super();this.Mb=null;this.mb=!1;this.Va=a;B(this,null)}Ra(){if(!this.mb&&!this.mb){if(null===this.Va)var a="null";else try{a=ka(this.Va)+" (of class "+fa(this.Va)+")"}catch(b){if(tc||(tc=new rc),null!==(b instanceof cd?b:new uc(b)))a="an instance of class "+fa(this.Va);else throw b;}this.Mb=a;this.mb=!0}return this.Mb}}fc.prototype.$classData=y({Vc:0},!1,"scala.MatchError",{Vc:1,H:1,K:1,L:1,a:1,b:1});function Qd(){}Qd.prototype=new u;Qd.prototype.constructor=Qd;
function Rd(){}Rd.prototype=Qd.prototype;Qd.prototype.e=function(){return this===Sd()};Qd.prototype.m=function(){return this.e()?0:1};Qd.prototype.l=function(){if(this.e())var a=D().G;else throw D(),new xd("None.get");return a};function X(a){this.Ob=this.Aa=0;this.Nb=null;if(null===a)throw sc(null);this.Nb=a;this.Aa=0;this.Ob=a.D()}X.prototype=new V;X.prototype.constructor=X;X.prototype.j=function(){return this.Aa<this.Ob};X.prototype.g=function(){var a=this.Nb.E(this.Aa);this.Aa=1+this.Aa|0;return a};
X.prototype.$classData=y({Xc:0},!1,"scala.Product$$anon$1",{Xc:1,T:1,a:1,N:1,o:1,r:1});function Td(){}Td.prototype=new qd;Td.prototype.constructor=Td;Td.prototype.$classData=y({ld:0},!1,"scala.collection.ClassTagSeqFactory$AnySeqDelegate",{ld:1,Ee:1,a:1,I:1,b:1,la:1});function vd(){}vd.prototype=new V;vd.prototype.constructor=vd;d=vd.prototype;d.j=function(){return!1};d.m=function(){return 0};d.cb=function(){return this};d.g=function(){throw new xd("next on empty iterator");};
d.$classData=y({sd:0},!1,"scala.collection.Iterator$$anon$19",{sd:1,T:1,a:1,N:1,o:1,r:1});function Ud(a){for(;0<a.W;)a.ja.j()?(a.ja.g(),a.W=-1+a.W|0):a.W=0}function Vd(a,b){if(0>a.A)return-1;a=a.A-b|0;return 0>a?0:a}function Fd(a,b,c){this.ja=a;this.A=c;this.W=b}Fd.prototype=new V;Fd.prototype.constructor=Fd;d=Fd.prototype;d.m=function(){var a=this.ja.m();if(0>a)return-1;a=a-this.W|0;a=0>a?0:a;if(0>this.A)return a;var b=this.A;return b<a?b:a};d.j=function(){Ud(this);return 0!==this.A&&this.ja.j()};
d.g=function(){Ud(this);return 0<this.A?(this.A=-1+this.A|0,this.ja.g()):0>this.A?this.ja.g():D().G.g()};d.cb=function(a,b){a=0<a?a:0;if(0>b)b=Vd(this,a);else if(b<=a)b=0;else if(0>this.A)b=b-a|0;else{var c=Vd(this,a);b=b-a|0;b=c<b?c:b}if(0===b)return D().G;this.W=this.W+a|0;this.A=b;return this};d.$classData=y({td:0},!1,"scala.collection.Iterator$SliceIterator",{td:1,T:1,a:1,N:1,o:1,r:1});function Wd(a,b){if(0>b)throw new J(""+b);a=a.Eb(b);if(a.e())throw new J(""+b);return a.f()}
function Xd(a,b){if(b&&b.$classData&&b.$classData.v.qb)a:for(;;){if(a===b){a=!0;break a}if((a.e()?0:!b.e())&&Yb(cc(),a.f(),b.f()))a=a.h(),b=b.h();else{a=a.e()&&b.e();break a}}else a=Kd(a,b);return a}function Yd(a){this.Xa=a}Yd.prototype=new V;Yd.prototype.constructor=Yd;Yd.prototype.j=function(){return!this.Xa.e()};Yd.prototype.g=function(){var a=this.Xa.f();this.Xa=this.Xa.h();return a};
Yd.prototype.$classData=y({wd:0},!1,"scala.collection.StrictOptimizedLinearSeqOps$$anon$1",{wd:1,T:1,a:1,N:1,o:1,r:1});function ub(){Bb()}ub.prototype=new Jd;ub.prototype.constructor=ub;ub.prototype.$classData=y({Ed:0},!1,"scala.collection.immutable.IndexedSeq$",{Ed:1,ud:1,a:1,la:1,I:1,b:1});var tb;function Zd(a){this.Ga=a}Zd.prototype=new V;Zd.prototype.constructor=Zd;Zd.prototype.j=function(){return!this.Ga.e()};
Zd.prototype.g=function(){if(this.Ga.e())return D().G.g();var a=W(this.Ga).f();this.Ga=T(W(this.Ga));return a};Zd.prototype.$classData=y({Jd:0},!1,"scala.collection.immutable.LazyList$LazyIterator",{Jd:1,T:1,a:1,N:1,o:1,r:1});function $d(){ae=this;E();E()}$d.prototype=new u;$d.prototype.constructor=$d;$d.prototype.$classData=y({Md:0},!1,"scala.collection.immutable.List$",{Md:1,a:1,xd:1,la:1,I:1,b:1});var ae;function vb(){ae||(ae=new $d)}
function be(a){a.y<=a.s&&D().G.g();a.Ia=1+a.Ia|0;for(var b=null;0===b.c.length;)a.Ia=1+a.Ia|0,b=null;a.$a=a.pa;var c=a.Od/2|0,e=a.Ia-c|0;a.aa=(1+c|0)-(0>e?-e|0:e)|0;c=a.aa;switch(c){case 1:a.O=b;break;case 2:a.Y=b;break;case 3:a.Z=b;break;case 4:a.$=b;break;case 5:a.oa=b;break;case 6:a.yb=b;break;default:throw new fc(c);}a.pa=a.$a+Math.imul(b.c.length,1<<Math.imul(5,-1+a.aa|0))|0;a.pa>a.P&&(a.pa=a.P);1<a.aa&&(a.Ha=-1+(1<<Math.imul(5,a.aa))|0)}
function ce(a,b,c){this.yb=this.oa=this.$=this.Z=this.Y=null;this.P=b;this.Od=c;this.O=a.qa;this.X=this.O.c.length;this.Ha=this.s=0;this.y=this.P;this.Ia=0;this.aa=1;this.$a=0;this.pa=this.X}ce.prototype=new u;ce.prototype.constructor=ce;d=ce.prototype;d.l=function(){return this};d.e=function(){return this.y<=this.s};d.i=function(){return"\x3citerator\x3e"};d.Qa=function(a,b,c,e){return db(this,a,b,c,e)};d.m=function(){return this.y-this.s|0};d.j=function(){return this.y>this.s};
d.g=function(){if(this.s===this.X){var a=(this.s-this.y|0)+this.P|0;a===this.pa&&be(this);if(1<this.aa){a=a-this.$a|0;var b=this.Ha^a;1024>b?this.O=this.Y.c[31&(a>>>5|0)]:(32768>b?this.Y=this.Z.c[31&(a>>>10|0)]:(1048576>b?this.Z=this.$.c[31&(a>>>15|0)]:(33554432>b?this.$=this.oa.c[31&(a>>>20|0)]:(this.oa=this.yb.c[a>>>25|0],this.$=this.oa.c[0]),this.Z=this.$.c[0]),this.Y=this.Z.c[0]),this.O=this.Y.c[0]);this.Ha=a}this.y=this.y-this.s|0;a=this.O.c.length;b=this.y;this.X=a<b?a:b;this.s=0}a=this.O.c[this.s];
this.s=1+this.s|0;return a};
d.xa=function(a){if(0<a){a=((this.s-this.y|0)+this.P|0)+a|0;var b=this.P;a=a<b?a:b;if(a===this.P)this.X=this.y=this.s=0;else{for(;a>=this.pa;)be(this);b=a-this.$a|0;if(1<this.aa){var c=this.Ha^b;1024>c||(32768>c||(1048576>c||(33554432>c||(this.oa=this.yb.c[b>>>25|0]),this.$=this.oa.c[31&(b>>>20|0)]),this.Z=this.$.c[31&(b>>>15|0)]),this.Y=this.Z.c[31&(b>>>10|0)]);this.O=this.Y.c[31&(b>>>5|0)];this.Ha=b}this.X=this.O.c.length;this.s=31&b;this.y=this.s+(this.P-a|0)|0;this.X>this.y&&(this.X=this.y)}}return this};
d.$classData=y({Nd:0},!1,"scala.collection.immutable.NewVectorIterator",{Nd:1,a:1,N:1,o:1,r:1,kb:1});function sb(){vb()}sb.prototype=new Jd;sb.prototype.constructor=sb;sb.prototype.$classData=y({Rd:0},!1,"scala.collection.immutable.Seq$",{Rd:1,ud:1,a:1,la:1,I:1,b:1});var rb;
function de(){this.bc=0;this.cc=null;ee=this;try{var a=Ia;Ha||(Ha=new Ga);var b=a(Ha,"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","250");bd||(bd=new ad);var c=null===b?0:b.length|0;0===c&&Zc(b);var e=65535&(b.charCodeAt(0)|0),g=(a=45===e)?2147483648:2147483647;e=a||43===e?1:0;e>=(b.length|0)&&Zc(b);for(var f=0;e!==c;){Yc||(Yc=new Xc);var k=Yc,n=65535&(b.charCodeAt(e)|0);if(256>n)var p=48<=n&&57>=n?-48+n|0:65<=n&&90>=n?-55+n|0:97<=n&&122>=n?-87+n|0:-1;else if(65313<=n&&65338>=
n)p=-65303+n|0;else if(65345<=n&&65370>=n)p=-65335+n|0;else{var G=Wc(k);Ta||(Ta=new Sa);b:for(var Y=G,ze=n,Cc=0,ld=Y.c.length;;){if(Cc===ld){var Dc=-1-Cc|0;break b}var Ec=(Cc+ld|0)>>>1|0,Ae=Y.c[Ec];if(ze<Ae)ld=Ec;else{if(Yb(cc(),ze,Ae)){Dc=Ec;break b}Cc=1+Ec|0}}Y=0>Dc?-2-Dc|0:Dc;if(0>Y)p=-1;else{var Be=n-Wc(k).c[Y]|0;p=9<Be?-1:Be}}var Ce=10>p?p:-1;f=10*f+Ce;(-1===Ce||f>g)&&Zc(b);e=1+e|0}}catch(ef){throw ef;}this.bc=a?-f|0:f|0;this.cc=new ce(fe(),0,0)}de.prototype=new u;de.prototype.constructor=de;
de.prototype.$classData=y({Td:0},!1,"scala.collection.immutable.Vector$",{Td:1,a:1,xd:1,la:1,I:1,b:1});var ee;function Bb(){ee||(ee=new de);return ee}function Z(a){this.ec=0;this.ie=a;this.db=0;this.ec=a.D()}Z.prototype=new V;Z.prototype.constructor=Z;Z.prototype.j=function(){return this.db<this.ec};Z.prototype.g=function(){var a=this.ie.E(this.db);this.db=1+this.db|0;return a};Z.prototype.$classData=y({he:0},!1,"scala.runtime.ScalaRunTime$$anon$1",{he:1,T:1,a:1,N:1,o:1,r:1});
function Rc(a,b){this.Ka=a;this.La=b}Rc.prototype=new u;Rc.prototype.constructor=Rc;d=Rc.prototype;d.M=function(){return new X(this)};d.q=function(){return yc(this)};d.n=function(a){return this===a?!0:a instanceof Rc?this.Ka===a.Ka&&this.La===a.La:!1};d.i=function(){return gc(this)};d.D=function(){return 2};d.F=function(){return"Attribute"};d.E=function(a){if(0===a)return this.Ka;if(1===a)return this.La;throw new J(""+a);};d.$classData=y({hc:0},!1,"tyrian.Attribute",{hc:1,a:1,eb:1,z:1,S:1,b:1});
function ge(){he=this;new P(this,"accept");new P(this,"accesskey");new P(this,"action");new P(this,"alt");new P(this,"autocomplete");new P(this,"charset");new P(this,"cite");new P(this,"class");new P(this,"class");new P(this,"class");new P(this,"class");new P(this,"class");new P(this,"cols");new O(this,"cols");new P(this,"colspan");new O(this,"colspan");new P(this,"colspan");new O(this,"colspan");new P(this,"content");new P(this,"contenteditable");new N(this,"contenteditable");new P(this,"contenteditable");
new N(this,"contenteditable");new P(this,"coords");new P(this,"data");new P(this,"datetime");new P(this,"datetime");new P(this,"dir");new P(this,"dirname");new P(this,"draggable");new N(this,"draggable");new P(this,"enctype");new P(this,"enctype");new P(this,"for");new P(this,"for");new P(this,"for");new P(this,"form");new P(this,"formaction");new P(this,"formaction");new P(this,"headers");new P(this,"height");new O(this,"height");new P(this,"high");new Fc(this,"high");new P(this,"href");new P(this,
"hreflang");new P(this,"hreflang");new P(this,"http");new P(this,"id");new P(this,"kind");new P(this,"label");new P(this,"lang");new P(this,"list");new P(this,"low");new Fc(this,"low");new P(this,"max");new O(this,"max");new P(this,"maxlength");new O(this,"maxlength");new P(this,"maxlength");new O(this,"maxlength");new P(this,"media");new P(this,"method");new P(this,"min");new O(this,"min");new P(this,"multiple");new P(this,"muted");new P(this,"name");new P(this,"optimum");new Fc(this,"optimum");
new P(this,"pattern");new P(this,"placeholder");new P(this,"poster");new P(this,"preload");new P(this,"rel");new P(this,"rows");new O(this,"rows");new P(this,"rowspan");new O(this,"rowspan");new P(this,"rowspan");new O(this,"rowspan");new P(this,"scope");new P(this,"shape");new P(this,"size");new O(this,"size");new P(this,"sizes");new P(this,"span");new O(this,"span");new P(this,"spellcheck");new N(this,"spellcheck");new P(this,"spellcheck");new N(this,"spellcheck");new P(this,"src");new P(this,"srcdoc");
new P(this,"srcdoc");new P(this,"srclang");new P(this,"srclang");new P(this,"srcset");new P(this,"srcset");new P(this,"start");new O(this,"start");new P(this,"step");new O(this,"step");new P(this,"style");new P(this,"tabindex");new O(this,"tabindex");new P(this,"tabindex");new O(this,"tabindex");new P(this,"target");new P(this,"title");new P(this,"translate");new P(this,"type");new P(this,"type");new P(this,"type");new P(this,"type");new P(this,"usemap");new P(this,"usemap");new P(this,"width");new O(this,
"width");new P(this,"wrap");new Ic(this,"value");new Hc(this,"value");new Gc(this,"value")}ge.prototype=new u;ge.prototype.constructor=ge;ge.prototype.$classData=y({lc:0},!1,"tyrian.Html$",{lc:1,a:1,me:1,le:1,Pb:1,re:1});var he;function ie(){he||(he=new ge)}function S(a){this.Oa=a}S.prototype=new u;S.prototype.constructor=S;d=S.prototype;d.M=function(){return new X(this)};d.q=function(){return yc(this)};d.n=function(a){return this===a?!0:a instanceof S?this.Oa===a.Oa:!1};d.i=function(){return gc(this)};
d.D=function(){return 1};d.F=function(){return"Text"};d.E=function(a){if(0===a)return this.Oa;throw new J(""+a);};var je=y({vc:0},!1,"tyrian.Text",{vc:1,a:1,fb:1,z:1,S:1,b:1});S.prototype.$classData=je;function ja(a){a=+a;return Ea(Fa(),a)}class $c extends Pa{constructor(a){super();B(this,a)}}$c.prototype.$classData=y({Hc:0},!1,"java.lang.NumberFormatException",{Hc:1,Ib:1,H:1,K:1,L:1,a:1,b:1});
function t(a){for(var b=0,c=1,e=-1+(a.length|0)|0;0<=e;)b=b+Math.imul(65535&(a.charCodeAt(e)|0),c)|0,c=Math.imul(31,c),e=-1+e|0;return b}function Mc(a){return";"===a.substring((a.length|0)-1|0)}function ke(){}ke.prototype=new Rd;ke.prototype.constructor=ke;d=ke.prototype;d.F=function(){return"None"};d.D=function(){return 0};d.E=function(a){return pc(K(),a)};d.M=function(){return new Z(this)};d.q=function(){return 2433880};d.i=function(){return"None"};
d.$classData=y({Wc:0},!1,"scala.None$",{Wc:1,pe:1,a:1,o:1,S:1,z:1,b:1});var le;function Sd(){le||(le=new ke);return le}function me(){}me.prototype=new u;me.prototype.constructor=me;function ne(){}ne.prototype=me.prototype;me.prototype.da=function(){return this.ra()};me.prototype.Qa=function(a,b,c,e){return db(this,a,b,c,e)};me.prototype.m=function(){return-1};function oe(a){this.Fa=0;this.Sb=a;this.U=0;H();a=this.Sb;this.Fa=Oa(Ra(),a)}oe.prototype=new V;oe.prototype.constructor=oe;d=oe.prototype;
d.m=function(){return this.Fa-this.U|0};d.j=function(){return this.U<this.Fa};d.g=function(){try{var a=ec(H(),this.Sb,this.U);this.U=1+this.U|0;return a}catch(b){throw b;}};d.xa=function(a){if(0<a){a=this.U+a|0;if(0>a)a=this.Fa;else{var b=this.Fa;a=b<a?b:a}this.U=a}return this};d.$classData=y({kd:0},!1,"scala.collection.ArrayOps$ArrayIterator",{kd:1,T:1,a:1,N:1,o:1,r:1,b:1});function pe(a){this.x=0;this.od=a;this.V=0;this.x=a.k()}pe.prototype=new V;pe.prototype.constructor=pe;d=pe.prototype;d.m=function(){return this.x};
d.j=function(){return 0<this.x};d.g=function(){if(0<this.x){var a=this.od.p(this.V);this.V=1+this.V|0;this.x=-1+this.x|0;return a}return D().G.g()};d.xa=function(a){0<a&&(this.V=this.V+a|0,a=this.x-a|0,this.x=0>a?0:a);return this};d.cb=function(a,b){a=0>a?0:a>this.x?this.x:a;b=(0>b?0:b>this.x?this.x:b)-a|0;this.x=0>b?0:b;this.V=this.V+a|0;return this};d.$classData=y({nd:0},!1,"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{nd:1,T:1,a:1,N:1,o:1,r:1,b:1});
function jc(){this.Wb=null;this.tb=!1;ic=this;new Td(this)}jc.prototype=new u;jc.prototype.constructor=jc;jc.prototype.$classData=y({Cd:0},!1,"scala.collection.immutable.ArraySeq$",{Cd:1,a:1,Le:1,Fe:1,De:1,Ge:1,b:1});var ic;function Q(a,b,c){this.sa=a;this.Ma=b;this.Na=c}Q.prototype=new u;Q.prototype.constructor=Q;d=Q.prototype;d.M=function(){return new X(this)};d.q=function(){return yc(this)};
d.n=function(a){if(this===a)return!0;if(a instanceof Q){if(this.sa===a.sa){var b=this.Ma,c=a.Ma;b=null===b?null===c:b.n(c)}else b=!1;if(b)return b=this.Na,a=a.Na,null===b?null===a:b.n(a)}return!1};d.i=function(){return gc(this)};d.D=function(){return 3};d.F=function(){return"Tag"};d.E=function(a){switch(a){case 0:return this.sa;case 1:return this.Ma;case 2:return this.Na;default:throw new J(""+a);}};d.$classData=y({uc:0},!1,"tyrian.Tag",{uc:1,a:1,fb:1,kc:1,z:1,S:1,b:1});function qe(){}
qe.prototype=new u;qe.prototype.constructor=qe;function re(){}re.prototype=qe.prototype;class uc extends U{constructor(a){super();this.Ja=a;B(this,null)}Ra(){return ka(this.Ja)}Fb(){}F(){return"JavaScriptException"}D(){return 1}E(a){return 0===a?this.Ja:pc(K(),a)}M(){return new Z(this)}q(){return yc(this)}n(a){if(this===a)return!0;if(a instanceof uc){var b=this.Ja;a=a.Ja;return Yb(cc(),b,a)}return!1}}
uc.prototype.$classData=y({Yd:0},!1,"scala.scalajs.js.JavaScriptException",{Yd:1,H:1,K:1,L:1,a:1,b:1,S:1,z:1});function se(){this.Qb=null;this.nb=0}se.prototype=new re;se.prototype.constructor=se;function te(){}te.prototype=se.prototype;se.prototype.i=function(){return this.Qb};se.prototype.n=function(a){return this===a};se.prototype.q=function(){return this.nb};function Tc(){}Tc.prototype=new u;Tc.prototype.constructor=Tc;d=Tc.prototype;d.M=function(){return new X(this)};d.q=function(){return 853194735};
d.i=function(){return"EmptyAttribute"};d.D=function(){return 0};d.F=function(){return"EmptyAttribute"};d.E=function(a){throw new J(""+a);};d.$classData=y({jc:0},!1,"tyrian.EmptyAttribute$",{jc:1,a:1,eb:1,z:1,S:1,b:1,Pb:1,Yc:1,qe:1});var Sc;function ue(){}ue.prototype=new ne;ue.prototype.constructor=ue;function ve(){}ve.prototype=ue.prototype;ue.prototype.i=function(){return this.da()+"(\x3cnot computed\x3e)"};function lc(){this.nb=0;this.Qb="Object";Sd();Wb();za(z);this.nb=na(this)}lc.prototype=new te;
lc.prototype.constructor=lc;lc.prototype.$classData=y({fd:0},!1,"scala.reflect.ManifestFactory$ObjectManifest$",{fd:1,ye:1,xe:1,a:1,we:1,ve:1,ue:1,ze:1,b:1,z:1});var kc;function we(a,b){return a===b?!0:b&&b.$classData&&b.$classData.v.ka&&b.ib(a)?a.Da(b):!1}function xe(){}xe.prototype=new ne;xe.prototype.constructor=xe;function ye(){}d=ye.prototype=xe.prototype;d.ib=function(){return!0};d.n=function(a){return we(this,a)};
d.q=function(){var a=zc();if(this&&this.$classData&&this.$classData.v.ob)a:{var b=a.Ca;a=this.k();switch(a){case 0:a=M(b^0);break a;case 1:a=b;b=this.p(0);a=M(L(a,I(K(),b))^1);break a;default:var c=this.p(0),e=I(K(),c);c=b=L(b,e);var g=this.p(1);g=I(K(),g);var f=g-e|0;for(e=2;e<a;){b=L(b,g);var k=this.p(e);k=I(K(),k);if(f!==(k-g|0)){b=L(b,k);for(e=1+e|0;e<a;)c=this.p(e),b=L(b,I(K(),c)),e=1+e|0;a=M(b^a);break a}g=k;e=1+e|0}a=M(L(L(c,f),g))}}else if(this instanceof De){a=a.Ca;e=0;g=a;b=c=k=f=0;for(var n=
this;!n.e();){var p=n.f();n=n.h();p=I(K(),p);g=L(g,p);switch(f){case 0:b=p;f=1;break;case 1:k=p-c|0;f=2;break;case 2:k!==(p-c|0)&&(f=3)}c=p;e=1+e|0}2===f?(e=k,a=M(L(L(L(a,b),e),c))):a=M(g^e)}else a:if(b=a.Ca,a=this.l(),a.j())if(c=a.g(),a.j()){e=a.g();f=I(K(),c);c=b=L(b,f);g=I(K(),e);f=g-f|0;for(e=2;a.j();){b=L(b,g);k=a.g();k=I(K(),k);if(f!==(k-g|0)){b=L(b,k);for(e=1+e|0;a.j();)c=a.g(),b=L(b,I(K(),c)),e=1+e|0;a=M(b^e);break a}g=k;e=1+e|0}a=M(L(L(c,f),g))}else a=M(L(b,I(K(),c))^1);else a=M(b^0);return a};
d.i=function(){return ab(this,this.da()+"(",", ",")")};d.e=function(){return 0===this.ea(0)};d.Da=function(a){return Kd(this,a)};function Ee(){}Ee.prototype=new ve;Ee.prototype.constructor=Ee;function Fe(){}Fe.prototype=Ee.prototype;function Ge(){this.Wa=null}Ge.prototype=new Fe;Ge.prototype.constructor=Ge;function He(){}He.prototype=Ge.prototype;Ge.prototype.p=function(a){return this.Wa.p(a)};Ge.prototype.k=function(){return this.Wa.k()};Ge.prototype.e=function(){return this.Wa.e()};
function Ie(a){this.Wa=a}Ie.prototype=new He;Ie.prototype.constructor=Ie;d=Ie.prototype;d.l=function(){return new pe(this)};d.ra=function(){return"IndexedSeqView"};d.ea=function(a){var b=this.k();return b===a?0:b<a?-1:1};d.m=function(){return this.k()};d.$classData=y({md:0},!1,"scala.collection.IndexedSeqView$Id",{md:1,Ke:1,Be:1,Ce:1,fa:1,a:1,ga:1,o:1,ia:1,r:1,ha:1,Me:1,b:1,Je:1,ma:1,Ie:1,pb:1});function Je(){}Je.prototype=new ye;Je.prototype.constructor=Je;function Ke(){}Ke.prototype=Je.prototype;
function Le(a,b){return b&&b.$classData&&b.$classData.v.vb?a.k()===b.k():!0}function Me(a,b){if(b&&b.$classData&&b.$classData.v.vb){if(a===b)return!0;var c=a.k(),e=c===b.k();if(e){var g=0,f=a.hb(),k=b.hb();f=f<k?f:k;k=c>>31;var n=f>>>31|0|f>>31<<1;for(f=(k===n?(-2147483648^c)>(-2147483648^f<<1):k>n)?f:c;g<f&&e;)e=Yb(cc(),a.p(g),b.p(g)),g=1+g|0;if(g<c&&e)for(a=a.l().xa(g),b=b.l().xa(g);e&&a.j();)e=Yb(cc(),a.g(),b.g())}return e}return Kd(a,b)}function Ne(){}Ne.prototype=new ye;
Ne.prototype.constructor=Ne;function Oe(){}Oe.prototype=Ne.prototype;
function Pe(a,b,c,e,g){b.d=""+b.d+c;if(!a.B)b.d+="\x3cnot computed\x3e";else if(!a.e()){c=W(a).f();b.d=""+b.d+c;c=a;var f=T(W(a));if(c!==f&&(!f.B||W(c)!==W(f))&&(c=f,f.B&&!f.e()))for(f=T(W(f));c!==f&&f.B&&!f.e()&&W(c)!==W(f);){b.d=""+b.d+e;var k=W(c).f();b.d=""+b.d+k;c=T(W(c));f=T(W(f));f.B&&!f.e()&&(f=T(W(f)))}if(!f.B||f.e()){for(;c!==f;)b.d=""+b.d+e,a=W(c).f(),b.d=""+b.d+a,c=T(W(c));c.B||(b.d=""+b.d+e,b.d+="\x3cnot computed\x3e")}else{k=a;for(a=0;;){var n=k,p=f;if(n!==p&&W(n)!==W(p))k=T(W(k)),f=
T(W(f)),a=1+a|0;else break}k=c;n=f;(k===n||W(k)===W(n))&&0<a&&(b.d=""+b.d+e,a=W(c).f(),b.d=""+b.d+a,c=T(W(c)));for(;;)if(a=c,k=f,a!==k&&W(a)!==W(k))b.d=""+b.d+e,a=W(c).f(),b.d=""+b.d+a,c=T(W(c));else break;b.d=""+b.d+e;b.d+="\x3ccycle\x3e"}}b.d=""+b.d+g;return b}function Od(a){this.Zb=null;this.wb=!1;this.Yb=a;this.xb=this.B=!1}Od.prototype=new Ke;Od.prototype.constructor=Od;d=Od.prototype;d.ra=function(){return"LinearSeq"};d.k=function(){for(var a=this,b=0;!a.e();)b=1+b|0,a=a.h();return b};
d.ea=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.e()?0:1;break a}if(b.e()){a=-1;break a}c=1+c|0;b=b.h()}return a};d.p=function(a){return Wd(this,a)};d.Da=function(a){return Xd(this,a)};function W(a){if(!a.wb&&!a.wb){if(a.xb)throw a=new U,B(a,"self-referential LazyList or a derivation thereof has no more elements"),sc(a);a.xb=!0;try{var b=(0,a.Yb.$d)()}finally{a.xb=!1}a.B=!0;a.Yb=null;a.Zb=b;a.wb=!0}return a.Zb}d.e=function(){return W(this)===Ad()};
d.m=function(){return this.B&&this.e()?0:-1};d.f=function(){return W(this).f()};function Nd(a){var b=a,c=a;for(b.e()||(b=T(W(b)));c!==b&&!b.e();){b=T(W(b));if(b.e())break;b=T(W(b));if(b===c)break;c=T(W(c))}return a}d.l=function(){return this.B&&this.e()?D().G:new Zd(this)};d.da=function(){return"LazyList"};d.Qa=function(a,b,c,e){Nd(this);Pe(this,a.C,b,c,e);return a};d.i=function(){var a=new C;cb(a);a.d="LazyList";return Pe(this,a,"(",", ",")").d};d.ca=function(a){return Wd(this,a|0)};
d.Eb=function(a){return 0>=a?this:this.B&&this.e()?Ab().Xb:Pd(Ab(),this,a)};d.h=function(){return T(W(this))};d.$classData=y({Hd:0},!1,"scala.collection.immutable.LazyList",{Hd:1,Ya:1,Ea:1,fa:1,a:1,ga:1,o:1,ia:1,r:1,ha:1,ka:1,za:1,ba:1,ma:1,z:1,ab:1,Za:1,bb:1,$b:1,qb:1,Tb:1,ac:1,b:1});function Qe(){}Qe.prototype=new Ke;Qe.prototype.constructor=Qe;function Re(){}d=Re.prototype=Qe.prototype;d.ib=function(a){return Le(this,a)};d.Da=function(a){return Me(this,a)};d.ra=function(){return"IndexedSeq"};
d.ea=function(a){var b=this.k();return b===a?0:b<a?-1:1};d.m=function(){return this.k()};d.da=function(){return"ArraySeq"};d.hb=function(){return 2147483647};function Se(){this.qa=null}Se.prototype=new Ke;Se.prototype.constructor=Se;function Te(){}d=Te.prototype=Se.prototype;d.ib=function(a){return Le(this,a)};d.Da=function(a){return Me(this,a)};d.ra=function(){return"IndexedSeq"};d.ea=function(a){var b=this.k();return b===a?0:b<a?-1:1};d.m=function(){return this.k()};
d.k=function(){return this instanceof Ue?this.ub:this.qa.c.length};d.l=function(){return fe()===this?Bb().cc:new ce(this,this.k(),0)};d.da=function(){return"Vector"};d.hb=function(){return Bb().bc};function mc(a){this.na=a}mc.prototype=new Re;mc.prototype.constructor=mc;d=mc.prototype;d.k=function(){return this.na.c.length};d.p=function(a){return this.na.c[a]};
d.q=function(){var a=zc();a:{var b=this.na;var c=a.Ca;H();a=Oa(Ra(),b);switch(a){case 0:b=M(c^0);break a;case 1:a=c;b=ec(H(),b,0);b=M(L(a,I(K(),b))^1);break a;default:var e=ec(H(),b,0),g=I(K(),e);e=c=L(c,g);var f=ec(H(),b,1);f=I(K(),f);var k=f-g|0;for(g=2;g<a;){c=L(c,f);var n=ec(H(),b,g);n=I(K(),n);if(k!==(n-f|0)){c=L(c,n);for(g=1+g|0;g<a;)e=ec(H(),b,g),c=L(c,I(K(),e)),g=1+g|0;b=M(c^a);break a}f=n;g=1+g|0}b=M(L(L(e,k),f))}}return b};
d.n=function(a){if(a instanceof mc){ed||(ed=new dd);a:{var b=this.na;a=a.na;if(b===a)b=!0;else if(b.c.length!==a.c.length)b=!1;else{for(var c=b.c.length,e=0;e<c;){if(!Yb(cc(),b.c[e],a.c[e])){b=!1;break a}e=1+e|0}b=!0}}}else b=we(this,a);return b};d.l=function(){return new oe(this.na)};d.ca=function(a){return this.p(a|0)};
d.$classData=y({Dd:0},!1,"scala.collection.immutable.ArraySeq$ofRef",{Dd:1,Ne:1,Ya:1,Ea:1,fa:1,a:1,ga:1,o:1,ia:1,r:1,ha:1,ka:1,za:1,ba:1,ma:1,z:1,ab:1,Za:1,bb:1,vb:1,ob:1,pb:1,Fd:1,zb:1,sb:1,rb:1,He:1,b:1});function De(){}De.prototype=new Ke;De.prototype.constructor=De;function Ve(){}d=Ve.prototype=De.prototype;d.l=function(){return new Yd(this)};d.ra=function(){return"LinearSeq"};d.p=function(a){return Wd(this,a)};d.Da=function(a){return Xd(this,a)};d.e=function(){return this===E()};
function We(a,b){if(b instanceof De){if(a.e())a=b;else if(!b.e()){var c=new R(b.f(),a),e=c;for(b=b.h();!b.e();){var g=new R(b.f(),a);e=e.J=g;b=b.h()}a=c}return a}if(0===b.m())return a;c=b.l();if(c.j()){for(b=e=new R(c.g(),a);c.j();)g=new R(c.g(),a),b=b.J=g;return e}return a}d.k=function(){for(var a=this,b=0;!a.e();)b=1+b|0,a=a.h();return b};d.ea=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.e()?0:1;break a}if(b.e()){a=-1;break a}c=1+c|0;b=b.h()}return a};d.da=function(){return"List"};
d.n=function(a){var b;if(a instanceof De)a:for(b=this;;){if(b===a){b=!0;break a}var c=b.e(),e=a.e();if(c||e||!Yb(cc(),b.f(),a.f())){b=c&&e;break a}b=b.h();a=a.h()}else b=we(this,a);return b};d.ca=function(a){return Wd(this,a|0)};d.Eb=function(a){a:for(var b=this;;){if(0>=a||b.e())break a;a=-1+a|0;b=b.h()}return b};function Xe(){this.qa=null}Xe.prototype=new Te;Xe.prototype.constructor=Xe;function Ye(){}Ye.prototype=Xe.prototype;function Ue(){this.qa=null;this.ub=0}Ue.prototype=new Ye;
Ue.prototype.constructor=Ue;function Ze(){}Ze.prototype=Ue.prototype;function R(a,b){this.Vb=a;this.J=b}R.prototype=new Ve;R.prototype.constructor=R;d=R.prototype;d.f=function(){return this.Vb};d.F=function(){return"::"};d.D=function(){return 2};d.E=function(a){switch(a){case 0:return this.Vb;case 1:return this.J;default:return pc(K(),a)}};d.M=function(){return new Z(this)};d.h=function(){return this.J};
d.$classData=y({Ad:0},!1,"scala.collection.immutable.$colon$colon",{Ad:1,Ld:1,Ya:1,Ea:1,fa:1,a:1,ga:1,o:1,ia:1,r:1,ha:1,ka:1,za:1,ba:1,ma:1,z:1,ab:1,Za:1,bb:1,$b:1,qb:1,Tb:1,ac:1,vd:1,sb:1,rb:1,zb:1,Ub:1,b:1,S:1});function $e(){af=this;E();E()}$e.prototype=new Ve;$e.prototype.constructor=$e;d=$e.prototype;d.jb=function(){throw new xd("head of empty list");};d.m=function(){return 0};d.l=function(){return D().G};d.F=function(){return"Nil"};d.D=function(){return 0};d.E=function(a){return pc(K(),a)};
d.M=function(){return new Z(this)};d.h=function(){throw new yd("tail of empty list");};d.f=function(){this.jb()};d.$classData=y({Pd:0},!1,"scala.collection.immutable.Nil$",{Pd:1,Ld:1,Ya:1,Ea:1,fa:1,a:1,ga:1,o:1,ia:1,r:1,ha:1,ka:1,za:1,ba:1,ma:1,z:1,ab:1,Za:1,bb:1,$b:1,qb:1,Tb:1,ac:1,vd:1,sb:1,rb:1,zb:1,Ub:1,b:1,S:1});var af;function E(){af||(af=new $e);return af}function bf(){this.qa=null;this.ub=0;var a=gb().dc;gb();this.ub=0;this.qa=a}bf.prototype=new Ze;bf.prototype.constructor=bf;
bf.prototype.n=function(a){return this===a||!(a instanceof Se)&&we(this,a)};function cf(a){return new J(a+" is out of bounds (empty vector)")}bf.prototype.ca=function(a){throw cf(a|0);};bf.prototype.p=function(a){throw cf(a);};bf.prototype.$classData=y({Ud:0},!1,"scala.collection.immutable.Vector0$",{Ud:1,Oe:1,Re:1,Qe:1,Ya:1,Ea:1,fa:1,a:1,ga:1,o:1,ia:1,r:1,ha:1,ka:1,za:1,ba:1,ma:1,z:1,ab:1,Za:1,bb:1,vb:1,ob:1,pb:1,Fd:1,zb:1,sb:1,rb:1,Ub:1,b:1});var df;function fe(){df||(df=new bf);return df}
function bb(){this.C=null}bb.prototype=new Oe;bb.prototype.constructor=bb;d=bb.prototype;d.ra=function(){return"IndexedSeq"};d.l=function(){var a=new Ie(this);return new pe(a)};d.ea=function(a){var b=this.C.k();return b===a?0:b<a?-1:1};d.k=function(){return this.C.k()};d.m=function(){return this.C.k()};d.i=function(){return this.C.d};d.e=function(){return 0===this.C.k()};d.ca=function(a){return new h(65535&(this.C.d.charCodeAt(a|0)|0))};d.p=function(a){return new h(65535&(this.C.d.charCodeAt(a)|0))};
d.$classData=y({Wd:0},!1,"scala.collection.mutable.StringBuilder",{Wd:1,Se:1,Ea:1,fa:1,a:1,ga:1,o:1,ia:1,r:1,ha:1,ka:1,za:1,ba:1,ma:1,z:1,af:1,Ze:1,bf:1,Ve:1,kb:1,$e:1,Te:1,We:1,Ue:1,Xe:1,ob:1,pb:1,Ye:1,Ac:1,b:1});ba=new l(0,0);Ba.fc=ba;
mdoc_js_run0=function(){Va||(Va=new Ua);ie();var a=Lc("font-family","Arial, Helvetica, sans-serif");Dd||(Dd=new Cd);a=new Rc("style",a);ie();H();ie();var b=hc(H(),new (A(Bc).w)([(ie(),new S("HTML fragment rendered by Tyrian on the server."))])),c=Wb().Ba;vb();b=We(E(),b);b=hc(0,new (A(Bc).w)([new Q("b",c,b)]));c=Wb().Ba;vb();b=We(E(),b);c=new Q("p",c,b);ie();a=hc(H(),new (A(Ac).w)([a]));H();ie();b=A(Bc).w;var e=Wb().Ba;Wb();var g=hc(H(),new (A(je).w)([(ie(),new S("Hello, world!"))]));g=We(E(),g);
c=hc(0,new b([c,new Q("p",e,g)]));vb();a=We(E(),a);vb();c=We(E(),c);a=new Q("div",a,c);Vc||(Vc=new Uc);c=Qc;Oc||(Oc=new Nc);c(Oc,a)};
}).call(this);
