addSbtPlugin("org.scala-js"        % "sbt-scalajs"         % "1.16.0")
addSbtPlugin("org.typelevel"       % "sbt-tpolecat"        % "0.5.2")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalafix"        % "0.12.1")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"         % "0.4.0")
addSbtPlugin("ch.epfl.scala"       % "sbt-scalajs-bundler" % "0.21.1")
