addSbtPlugin("org.scala-js"              % "sbt-scalajs"         % "1.15.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("com.github.reibitto"       % "sbt-welcome"         % "0.3.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalajs-bundler" % "0.21.1")
